.travis.yml, CMakeLists.txt, Makefile, README.md
Added a top-level Makefile to simplify buliding, cleaning and CI setup.
=> Added top-level Makefile

CMakeLists.txt, README.md
Added badge for Core Infrastructure Initiative. Added some additional documentation.
=> Added CII Badge

.travis.yml, Dockerfile, README.md
Updated entrypoint. Added documentation for sharing build artefacts with host environment.
=> Made docker build environment more flexible

src/logger.cpp
changed the init function of the logging module to use stdout instead of
stderr
=> logging to stout

src/CMakeLists.txt, src/logger.cc, src/logger.h, src/main.cc, src/oauthtoken.cc, src/oauthtoken.h, src/oauthtoken_test.cc, src/servercon.cc, src/servercon.h, src/servercon_test.cc, src/ymlcfg.cc, src/ymlcfg.h
Changed code to be more compatible with "Google Style Guide" style
=> Re-format code to Google Style Guide

CONTRIBUTING.md
=> Link to Google C++ style guide

Dockerfile, src/CMakeLists.txt, src/events.cc, src/events.h, src/types.cc, src/types.h, tests/CMakeLists.txt, tests/config_test.cc, tests/events_test.cc
=>  #52 JSON Event parsing

src/httpclient.cc, src/httpclient.h
gcc-5.3.0 returns an error with current warning flags
=> Fix a shadowing issue

src/channel.h, src/commands.h, src/events.h, src/httpclient.cc, src/httpclient.h, src/interpreter.cc, src/interpreter.h, src/main.cc, src/sotahttpclient.cc, src/sotahttpclient.h, src/types.cc, src/types.h
=> prepare code for easy integrate with gateways

src/httpclient.cc, src/httpclient.h
=> Free curl_slist in destructor

Dockerfile, distribution/sota.service.cmake, src/CMakeLists.txt
=> added systemd file, and install target

src/sotahttpclient.cc, src/sotahttpclient.h, tests/httpsotaclient_test.cc
=> fixes crash on startup

src/sotarviclient.cc, third_party/rvi_lib/src/rvi.c
=> rvi_lib fixes for 32bit architecture

src/commandinterpreter.cc, src/httpclient.cc, src/httpclient.h, src/sotahttpclient.cc, src/sotahttpclient.h, tests/httpclient_test.cc, tests/httpsotaclient_test.cc
Also code is formatted according 160 columns
=> fixed problems with bad network, and implemented download resume

.clang-format, src/commandinterpreter.cc, src/commands.cc, src/config.cc, src/dbusgateway/dbusgateway.cc, src/dbusgateway/swlm.cc, src/events.cc, src/eventsinterpreter.cc, src/gatewaymanager.cc, src/httpclient.cc, src/logger.cc, src/main.cc, src/socketgateway.cc, src/sotahttpclient.cc, src/sotarviclient.cc, src/types.cc, tests/commands_test.cc, tests/config_test.cc, tests/events_test.cc, tests/httpclient_test.cc, tests/httpsotaclient_test.cc, tests/rvisotaclient_test.cc, tests/socketgateway_test.cc, third_party/jsoncpp/jsoncpp.cpp
There is no logical changes, all sources automatically formatted with clang-format
=> Sources formtatted with 160 columns

src/sotarviclient.cc, tests/CMakeLists.txt, tests/rvisotaclient_test.cc, third_party/rvi_lib/include/rvi.h, third_party/rvi_lib/src/rvi.c
=> Added verbose logging to rvi_lib

src/CMakeLists.txt, src/eventsinterpreter.cc, src/sotahttpclient.cc, src/sotahttpclient.h, src/sotarviclient.cc, tests/CMakeLists.txt, tests/httpclient_test.cc, tests/httpsotaclient_test.cc, tests/rvisotaclient_test.cc
Optimized build process because it is to boring, also simplified CmakeLists.txt
=> Much faster build, and simplified CmakeFiles.txt for tests

README.md
Signed-off-by: Gianpaolo Macario <gianpaolo_macario@mentor.com>
=> README.md: Small typo fix

src/CMakeLists.txt, tests/CMakeLists.txt
=> Add rvi headers to aktualizr lib, and boost chrono

CMakeLists.txt, dbus/org.genivi.SotaClient.conf, src/config.cc, src/dbusgateway/dbusgateway.cc, src/logger.h, src/main.cc, src/socketgateway.cc, src/sotarviclient.cc, tests/CMakeLists.txt, tests/config_test.cc, tests/config_tests.toml, tests/dbusgateway_test.cc, tests/rvisotaclient_test.cc, tests/swm_test.cc, third_party/rvi_lib/src/rvi.c
Various fixes to enable integration with GENIVI Software Loading Manager and GDP
=> GDP Support

CMakeLists.txt, dbus/org.genivi.SotaClient.conf, src/config.cc, src/dbusgateway/dbusgateway.cc, src/logger.h, src/main.cc, src/socketgateway.cc, src/sotarviclient.cc, tests/CMakeLists.txt, tests/config_test.cc, tests/config_tests.toml, tests/dbusgateway_test.cc, tests/rvisotaclient_test.cc, tests/swm_test.cc, third_party/rvi_lib/CMakeLists.txt, third_party/rvi_lib/libjwt/CMakeLists.txt, third_party/rvi_lib/src/rvi.c
=> Statically link libjwt

config/conf.json, config/config.toml.example, src/sotarviclient.cc, tests/rvisotaclient_test.cc, third_party/rvi_lib/include/rvi.h, third_party/rvi_lib/src/rvi.c
Also removed vin parameter from config and corrected client config path to work out of box
=> Overwritting device id from our config.

codecov.yml, coverage.sh, src/CMakeLists.txt, tests/CMakeLists.txt
Also fix the tests when OSTree is disabled
=> Remove deleted files from CMakeLists

src/dbusgateway/dbusgateway.cc
Previous PR mistakenly wasn't include the second place where we use new dbus API
=> Do not use newer API, second place

.travis.yml, scripts/test.sh, src/config.h, src/crypto.cc, src/events.cc, src/main.cc, src/sotauptaneclient.h, tests/httpsotaclient_test.cc, tests/rvisotaclient_test.cc, tests/uptane_test.cc, third_party/rvi_lib/src/rvi.c
Set up the CI builds to build (in parallel) against Ubuntu and Debian stable, then add some fixes to make the build pass
=> Debian stable builds

codecov.yml, scripts/coverage.sh, src/sotauptaneclient.cc, tests/test_data/director/root.json, tests/test_data/repo/root.json, tests/uptane_test.cc
Tirned on ostree and uptane tests compilation on CI
=> improved uptane tests

config/config.toml.example, src/config.cc, src/config.h, src/eventsinterpreter.cc, src/httpclient.cc, src/httpclient.h, src/ostree.cc, src/ostree.h, src/sotahttpclient.cc, src/sotauptaneclient.cc, src/types.cc, src/types.h, tests/uptane_test.cc
this PR fixes uptane bugs for old and new API, also it implements ostree installation using API and allows to use ostree  in test environment.
=> Big Uptane/Ostree fix

src/httpclient.cc, src/sotahttpclient.cc, tests/httpclient_test.cc
This PR fixes old api problem.
Also there is small fix for polling.
=> Fix setting right headers for post and put methods

README.md
Nicer README.md, and a new badge to boot. We love badges.
=> Updated to use standard-readme format

src/sotarviclient.cc, tests/rvisotaclient_test.cc
Please check this fix, because I was not able to setup rvi server.
=> Fixes #176 issue

src/CMakeLists.txt, src/config.cc, src/config.h, src/dbusgateway/dbusgateway.cc, src/dbusgateway/dbusgateway.h, src/dbusgateway/swlm.cc, src/gatewaymanager.cc, src/main.cc, tests/CMakeLists.txt, tests/config_test.cc
This is useful to avoid a line like:
export DBUS_SESSION_BUS_ADDRESS="unix:path=/var/run/dbus/system_bus_socket"
=> Add option to connect to D-Bus's System Bus

src/config.cc, src/config.h, src/main.cc, src/sotauptaneclient.cc, src/sotauptaneclient.h, src/uptane/tufrepository.cc, src/uptane/uptanerepository.cc, src/uptane/uptanerepository.h, tests/uptane_test.cc
Added possibility to downgrade.
Some code refactoring.
=> Compatibility with current server implementation,

src/config.cc, src/config.h, src/sotauptaneclient.cc
"custom.uri" field in targets.json is outdated.
Patch to cope with URI proliferation in config is coming.
=> Add uptane.ostree_server option

src/config.cc, src/config.h, src/main.cc, src/uptane/tufrepository.cc
This option is wrong and unuseful
=> Remove downgrade option

src/config.cc, src/eventsinterpreter.cc, src/httpclient.cc, src/main.cc, src/ostree.cc, src/sotahttpclient.cc, src/sotahttpclient.h, src/uptane/uptanerepository.cc, tests/uptane_test.cc
Siplified code by removing retry logic, which was added to http class.
=> Added option --poll-once,

config/config.toml.example, src/config.cc, src/config.h, src/ostree.cc, src/sotauptaneclient.cc, src/uptane/tufrepository.cc, src/uptane/uptanerepository.cc, tests/config_tests.toml, tests/config_tests_prov.toml, tests/config_tests_prov_bad.toml, tests/uptane_test.cc
renamed certificates_path to certificates_directory  and added more verbose error message
=> renamed certificates_path to certificates_directory 

src/utils.cc
happy-Baumkuchen-123 doesn't look as nice as happy-baumkuchen-123
=> Make pet names lower case

src/httpclient.cc, src/httpclient.h, src/sotahttpclient.cc, src/sotauptaneclient.cc, src/uptane/tufrepository.cc, src/uptane/uptanerepository.cc, src/utils.h, tests/httpclient_test.cc, tests/httpsotaclient_test.cc, tests/uptane_test.cc
=> Http now returns HttpResponse class that contains all needed data

CMakeLists.txt, scripts/test.sh, src/CMakeLists.txt, tests/CMakeLists.txt
format sources with clang format
=> qa now depends on the tests

CMakeLists.txt, Dockerfile, Dockerfile.deb-stable, Dockerfile.deb-unstable, src/CMakeLists.txt, src/config.cc, src/httpclient.cc, src/sotauptaneclient.cc, src/uptane/exceptions.h, src/uptane/role.cc, src/uptane/root.cc, src/uptane/secondary.cc, src/uptane/tuf.cc, src/uptane/tuf.h, src/uptane/tufrepository.cc, src/uptane/tufrepository.h, src/uptane/uptanerepository.cc, src/uptane/uptanerepository.h, src/utils.cc, src/utils.h, tests/CMakeLists.txt, tests/tuf/sample1/root.json, tests/tuf/sample1/snapshot.json, tests/tuf/sample1/targets.json, tests/tuf/sample1/timestamp.json, tests/tuf_test.cc, tests/uptane_test.cc, tests/uptane_vector_tests.cc
The goal is to create a set of classes modeled around the concepts in TUF
=> Refactor TUF implementation

CMakeLists.txt, Dockerfile, Dockerfile.deb-stable, Dockerfile.deb-unstable, src/CMakeLists.txt, src/config.cc, src/config.h, src/ostree.cc, src/ostree.h, src/sotauptaneclient.cc, tests/CMakeLists.txt, tests/ostree_test.cc, tests/uptane_test.cc
Fixed issue with wrong installed packages request
=> Implemented unpacking zip credentials

src/uptane/secondary.cc
Resolves [PRO-3472](https://advancedtelematic.atlassian.net/browse/PRO-3472).
@patriotyk: the director doesn't support sha512 digests yet
=> Remove unsupported sha512 digest

src/config.cc, src/crypto.cc, src/crypto.h, src/httpclient.h, src/uptane/exceptions.h, src/uptane/root.cc, src/uptane/tuf.h, src/uptane/tufrepository.cc, src/uptane/tufrepository.h, src/uptane/uptanerepository.cc, tests/run_vector_tests.sh, tests/uptane_test.cc, tests/uptane_vector_tests.cc
also here is PR with targets path fix and PRO-3455 issue
=> Uptane vectors update

src/uptane/tuf.h, src/uptane/uptanerepository.cc, src/uptane/uptanerepository.h, tests/test_data/targets_hasupdates.json, tests/test_data/targets_noupdates.json, tests/uptane_test.cc
Allow redirects for image files
=> Change update logic to same as in python implementation

src/crypto.h, src/httpclient.cc, src/httpclient.h, src/uptane/tuf.cc, src/uptane/tuf.h, src/uptane/tufrepository.cc, src/uptane/tufrepository.h, tests/test_data/secondary_firmware.txt, tests/uptane_test.cc, tests/uptane_vector_tests.cc
Implemented multi part hasher
Right targets comparison
=> Skip download if file is greater than length in target

src/aktualizr.cc, src/main.cc, tests/CMakeLists.txt, tests/missing_ostree_repo.toml
I told that it is created, but I just realized that haven't created it.
=> test ostree and exit if it is not configured

src/crypto.cc, src/crypto.h, src/sotauptaneclient.cc, src/uptane/uptanerepository.cc, src/utils.cc, src/utils.h, tests/config_tests_prov.toml, tests/crypto_test.cc, tests/uptane_test.cc, tests/utils_test.cc
A partial solution until [PRO-3630](https://advancedtelematic.atlassian.net/browse/PRO-3630) is implemented.
=> Make device registration and ECU registration independent for more robustness

scripts/coverage.sh, src/aktualizr.cc, src/aktualizr.h, src/crypto.cc, src/crypto.h, src/ostree.cc, tests/CMakeLists.txt, tests/aktualizr.supp, tests/build_with_options, tests/dbusgateway_test.cc, tests/httpclient_test.cc, tests/run_vector_tests.sh, tests/socketgateway_test.cc, tests/uptane_test.cc, tests/uptane_vector_tests.cc
Instead of openssl use libsodium for hash functions
=> Fix memory leaks,

tests/config_test.cc, tests/uptane_ci_test.cc
Is the number 155 in  "\verify{\tst{155}}" comment  correct?
=> Check if aktualizr generates random ecu_serials

tests/get_open_port.py, tests/run_vector_tests.sh, tests/uptane_vector_tests.cc
This was only a problem for me when running locally with
CTEST_PARALLEL_LEVEL > 1, but it was annoying and made me concerned that
the problem could crop up in ugly ways in other places.
=> Specify ports to allow parallel uptane vector test runs.

tests/uptane_fake_http_test.cc
This PR fixes CI builds, please merge it, then restart existent PRs
=> Fix CI build

src/cert_provider/CMakeLists.txt
Partial revert of e297399fa59b5e49370f78a9ddac8fd2fe6cd39d.
=> No need to install cert_provider after all.

src/cert_provider/main.cc
We can just read it from the certificate now.
=> No need to copy device_id to device anymore.

src/uptane/secondary.cc, src/uptane/tufrepository.cc
This PR fixes updates for secondaries
=> Fixed secondary update

src/sotauptaneclient.cc
This PR adds understandable error message when installing non ostree package on ostree systems. But
I think we don't need allow to install such packages on ostree systems from web panel. We currently support only ostree packages for primaries so we could easily  implement it on the server.
=> Show correct message when installing non ostree image on ostree system

src/sotauptaneclient.cc
https://github.com/advancedtelematic/aktualizr/pull/365 didn't build in shovel environment. I'm not sure how it got through the CI.
=> Fix build failure

CMakeLists.txt, Dockerfile, Dockerfile.deb-unstable, Dockerfile.nop11, README.md, src/uptane/tufrepository.cc, tests/CMakeLists.txt, tests/implicit_writer_test.py, tests/sota_implicit_prov.toml
Pretty basic, so I'm open to suggestions if there's anything else I should check. The python script just checks the output files of implicit_writer and makes sure they match the expected values based on the inputs.
=> Feat/pro 3799/implicit writer test

src/implicit_writer/main.cc
Extracting root.crt from bootstrap.p12 doesn't work in some cases:
1. openssl (which we use for PKCS#11 case) doesn't work with root.crt stored in bootstrap credentials, it needs the issuer of client certicate there as well.
2. Bootstrap credentials don't contain the certificate for S3 servers and will therefore fail on staging environment (and on production when redirection to AWS is merged into production).
It is therefore convenient to have an option to suppress output of root.crt.
=> Add option for implicit-writer to skip writing root certificate

src/crypto.cc, src/crypto.h, src/p11engine.cc, src/p11engine.h, src/uptane/initialize.cc, src/utils.cc, src/utils.h, tests/crypto_test.cc, tests/uptane_test.cc, tests/utils_test.cc
device_id file is used in end-to-end tests.
=> Support extracting client certificate from PKCS#11 device

src/cert_provider/main.cc
This can be overridden with -d.
Previously -d was used for an optional local directory output. I moved
that to -l. Sorry for any confusion.
=> Change default target directory to /var/sota/token.

src/CMakeLists.txt, src/config.cc, src/config.h, src/uptane/initialize.cc, src/uptane/secondary.cc, src/uptane/secondary.h, src/uptane/secondaryconfig.cc, src/uptane/secondaryconfig.h, src/uptane/tuf.cc, tests/CMakeLists.txt, tests/httpfake.h, tests/tuf_test.cc, tests/uptane_ci_test.cc, tests/uptane_test.cc
This is really just a pretty basic path handling fixup, but along the way I fixed up a bunch of other stuff. This was one of those bugs where I think I had to learn everything the hard way.
=> Bugfix/pro 4187/secondary ecu paths

Dockerfile, Dockerfile.deb-stable, Dockerfile.deb-unstable, Dockerfile.nop11, scripts/push-sota-tools-image.sh, src/sota_tools/Dockerfile
This PR is most of the work in restoring a usable sota_tools docker image for the e2e team along with some reorganization of our main dockerfile collection.
=> Feat/pro 4238/sota tools docker

src/crypto.cc, src/p11engine.cc, src/sotauptaneclient.cc
Tested on qemux86-64 without softhsm.
Any suggestions on how to reduce code duplication are welcome.
=> Minor fixes in preparation for PRO-3630

CMakeLists.txt, src/sota_tools/CMakeLists.txt, src/sota_tools/authenticate.cc, src/sota_tools/garage_check.cc, src/sota_tools/treehub_server.cc, src/sota_tools/treehub_server.h
TreehubServer is responsible for authentication how it's done on the build machine (i.e. without a registered device), so I've made it do the job for accessing TUF repo as well. Which is of course a questionable solution.
=> Add garage-check utility

src/config.cc, src/uptane/legacysecondary.cc, src/uptane/legacysecondary.h, src/uptane/managedsecondary.cc, src/uptane/managedsecondary.h, src/uptane/secondaryconfig.h, src/uptane/virtualsecondary.cc, src/uptane/virtualsecondary.h, src/utils.cc, src/utils.h
Common functionality of legacy and virtual secondaries is isolated into ManagedSecondary class
=> Implement legacy secondaries

src/sotauptaneclient.cc, src/uptane/initialize.cc, src/uptane/uptanerepository.h, src/uptane/virtualsecondary.cc, tests/uptane_test.cc
Restored registering secondary ECUs on director
=> Fix uptane test

src/sota_tools/garage_check.cc
tufrepo.url only contains the base URL, full path needs to be appended
=> Fix path to targets.json

config/sota_autoprov.toml, config/sota_hsm_test.toml, config/sota_implicit_prov.toml
This will let us make non backwards compatible changes to configs
=> Move *.toml config files from meta-updater to aktualizr

src/utils.cc, tests/uptane_test.cc, tests/utils_test.cc
See #429 for the original PR.  This is a rebase of that, which we had to revert because of a conflict with #b51749304c
=> Improve test coverage

tests/uptane_test.cc
This fixes conflicts with #b51749304c "Refactor config to isolate storage
settings into StorageConfig"
=> Update tests to match changes to config

src/uptane/initialize.cc, tests/httpfake.h, tests/uptane_test.cc
Possibility of random ECU serial collisions is ignored from now on.
=> Restore backwards compatibility test

src/config.cc, src/logger.cc, src/main.cc, src/sotauptaneclient.cc, src/sotauptaneclient.h, src/uptane/initialize.cc, src/uptane/legacysecondary.cc, src/uptane/managedsecondary.cc, src/uptane/managedsecondary.h, src/uptane/secondaryinterface.h, src/uptane/virtualsecondary.cc, src/utils.cc, tests/uptane_ci_test.cc, tests/uptane_test.cc
This isn't really fully tested yet, but it does pass all the unit tests!
=> Feat/pro 3792/legacy init

src/cert_provider/main.cc, src/httpclient.cc
For now, just ignore subdirectories.
This is unintentionally sort of related to PRO-4525.
=> Use boost paths and fix problems with subdirectories.

docs/secondaries.svg
Change-Id: Ib19c107ef13a2d52302ff0c52139a7eb934bb50d
=> Add Anton's secondaries class diagram

src/sota_tools/ostree_hash.h
Test were already written!
(PRO-4592)
=> Remove TODO test comment about OSTreeHash::Parse

src/external_secondaries/CMakeLists.txt, src/external_secondaries/example_flasher.h, src/external_secondaries/make_ecu.h, src/external_secondaries/test_isotp_interface.cc, src/external_secondaries/test_isotp_interface.h
* Fix boost linking errors.
* Add all external_secondaries sources and headers to formatting function.
* Format the files.
* Remove unused macro.
=> Minor formatting and build fixes.

cmake-modules/FindSQLite3.cmake
We are not compatible with pre v3 sqlite
=> Prefer the more specific 'sqlite3' library name

config/storage/migrate.0.sql, config/storage/schema.0.sql, config/storage/schema.1.sql, src/aktualizr_info/main.cc, src/fsstorage.cc, src/fsstorage.h, src/invstorage.h, src/sotauptaneclient.cc, src/sqlstorage.cc, src/sqlstorage.h, tests/storage_common_test.cc
While finally testing the last SQLite work, I found a couple issues. They were actually relatively minor, but the typo fix makes this look like a big change.
=> Bugfix/pro 4623/store misconfigured

CMakeLists.txt, cmake-modules/CodeCoverage.cmake, tests/CMakeLists.txt
This PR also speedups coverage worker for a minute.
=> fix coverage issues

docs/hsm-provisioning.adoc
=> Add missing config item.

src/sota_tools/CMakeLists.txt
This gets things working on CI. QA doesn't seem to work.
=> Bump garage-sign version.

.travis.yml
That should hopefully start builds on version tags
=> Run travis for tags

.travis.yml
Another attempt to make travis deploy the releases
=> Add all_branches to travis.yml

src/ostree.cc, src/types.cc, src/types.h
Also clean up some path handling logic.
=> Always provide ca cert to ostree.

src/types.cc, src/types.h
Change-Id: I77298f3649188f39c185a58dc13bb4075df9e4b4
=> Remove dead code

.dockerignore, Dockerfile.test.16.04, scripts/build-ubuntu.sh
Fixes missing version and adds some new tests for the deb package
=> Fix releases (again)

config/schemas/migrate.2.sql, config/schemas/schema.2.sql, src/fsstorage.cc, src/fsstorage.h, src/invstorage.cc, src/invstorage.h, src/sotauptaneclient.cc, src/sqlstorage.cc, src/sqlstorage.h, src/uptane/tufrepository.cc, src/uptane/tufrepository.h, tests/storage_common_test.cc
This was a bit involved, good thing we have c++ 11 now
=> Store targets in db when using sqlstorage

src/crypto.cc
=> Generate 4096 bits RSA keys

docs/automatic-provisioning.adoc, docs/hsm-provisioning.adoc, docs/implicit-provisioning.adoc
This matches the discussiong in PRO-4807
Change-Id: I57ca6e8a637a83187d41cf52a3e1354f46db8776
=> Use '==' rather than '##', update locations of keys

src/ostree.cc
Should help preventing trying to pull an image every 10 seconds.
=> Don't pull OSTree ref if it is already in repo

src/sql_utils.h, src/sqlstorage.cc, src/sqlstorage.h, src/utils.cc, src/utils.h, tests/sqlstorage_test.cc, tests/utils_test.cc
=> Use statements + more helpers to refactor sql storage

config/sota_ubuntu.toml, src/deb.cc
Change-Id: If6d399ad25730f5a05789b60ca4fd79fe4ea016d
=> Fix Ubuntu sota.toml to enable Debian mode add logs

src/logging.cc
This might not be the best solution, but without it the systemd journal is useless.
Change-Id: I8c5f2ca0d76f69238bf21acbb7e224424ef8002e
=> Flush log messages

src/cert_provider/main.cc
The only viable solution I've found for getting `oe-selftest` to work with `cert_provider`.
=> Add option for bypassing strict host key checks.

src/config.h
Change-Id: I353a20f2326dc7132af3ef5c3406d1083d3729f6
=> Remove dead RviConfig code

docs/primary-secondary-protocol.adoc
This isn't meant to be complete. This PR is more here for review or at least a guideline for the initial development.
=> first pass at primary/secondary protocol

src/cert_provider/main.cc
And disallow specifying a target directory along with a config!
=> Make cert_provided use the storage path in config

tests/CMakeLists.txt, tests/run_import_clash_test.sh
Belated test for https://github.com/advancedtelematic/aktualizr/pull/599
=> Test for import/migrate path clashes

docs/deb-package-install.adoc
Extend the installation guide with examples.
=> deb-package-install.adoc: Add installation notes

src/cert_provider/main.cc
We started using relative paths like `token/root.crt` but these weren't handled by the tool
=> Correctly handle relative paths with cert_provider

CMakeLists.txt, src/aktualizr_secondary/CMakeLists.txt, src/aktualizr_secondary/main.cc, tests/CMakeLists.txt
Moved from https://github.com/advancedtelematic/aktualizr/pull/614, with one commit less.
Only a basic executable, without real functionality.
=> aktualizr-secondary basic target

docs/deb-package-install.adoc
Change-Id: I6a9a5a7144648ee9fb315f3997e784958ca1365d
=> Describe release process for Debian packages

src/opcuabridge/boostarch.h, src/opcuabridge/common.cc, src/opcuabridge/common.h, src/opcuabridge/currenttime.h, src/opcuabridge/ecuversionmanifestsigned.h, src/opcuabridge/filedata.h, src/opcuabridge/filelist.cc, src/opcuabridge/filelist.h, src/opcuabridge/imageblock.h, src/opcuabridge/imagefile.h, src/opcuabridge/imagerequest.h, src/opcuabridge/metadatafile.h, src/opcuabridge/metadatafiles.h, src/opcuabridge/signature.h, src/opcuabridge/utility.h, src/opcuabridge/versionreport.h, tests/opcuabridge_messaging_test.cc, tests/opcuabridge_server.cc, tests/opcuabridge_test_utils.cc
This will fix the build.  It passed CI because the changes that added these
files to clang-format were made in parallel to these changes.
Change-Id: I54c631137d6c60d2b1881bfafc11a991c52d5d55
=> Reformat with clang-format

CMakeLists.txt, Dockerfile, Dockerfile.deb-stable, Dockerfile.deb-unstable, Dockerfile.noostree, Dockerfile.nop11, cmake-modules/FindSystemd.cmake, src/aktualizr_secondary/CMakeLists.txt, src/aktualizr_secondary/aktualizr_secondary.cc, src/aktualizr_secondary/aktualizr_secondary.h, src/aktualizr_secondary/aktualizr_secondary_config.cc, src/aktualizr_secondary/aktualizr_secondary_ipc.h, src/aktualizr_secondary/main.cc, src/socket_activation/CMakeLists.txt, src/socket_activation/socket_activation.h, src/socket_activation/socket_activation_dummy.cc, src/socket_activation/socket_activation_systemd.cc, src/utils.cc, src/utils.h, tests/CMakeLists.txt, tests/aktualizr_secondary/protocol_test.cc
Based on #622.
The actual messages and parsing need to be done, for now please treat the content of `aktualizr_secondary_ipc.h` as a placeholder.
Not sure how to test this.
=> Secondary listening on TCP port

docs/debugging-tips.adoc
Change-Id: If1b50167b7b688fa9f174ebd6b19cdedd794e173
=> Add notes on using sslkeylog and wireshark

config/basic.toml, src/aktualizr_secondary/CMakeLists.txt, src/aktualizr_secondary/aktualizr_secondary.cc, src/aktualizr_secondary/aktualizr_secondary.h, src/aktualizr_secondary/aktualizr_secondary_config.cc, src/aktualizr_secondary/aktualizr_secondary_config.h, src/aktualizr_secondary/aktualizr_secondary_discovery.cc, src/aktualizr_secondary/aktualizr_secondary_discovery.h, src/aktualizr_secondary/main.cc, src/asn1-cer.h, src/asn1-cerstream.h, src/config.cc, src/utils.cc, src/utils.h, tests/CMakeLists.txt, tests/aktualizr_secondary/discovery_test.cc, tests/aktualizr_secondary/protocol_test.cc, tests/conf_test_aktualizr_info.toml, tests/utils_test.cc
Based on #632, I'll rebase it when merged.
Not entirely complete, it needs the hardware and serial ids of the secondary which, in turn, depends on the aktualizr secondary storage (should follow soon).
=> Secondary aktualizr discovery (secondary part)

src/bootstrap.cc, src/external_secondaries/CMakeLists.txt, src/utils.cc, src/utils.h, tests/CMakeLists.txt, tests/utils_test.cc
=> Archive refactor

src/aktualizr_secondary/aktualizr_secondary_discovery.cc, src/ipuptaneconnection.cc
Change-Id: I7ff8a873899b1b0f32ba4699ba4a1dd0e2726faf
=> Fix socket activation when UDP enabled

src/ipsecondarydiscovery.cc
Change-Id: I18a479e29bc6aba80854df89380157af3c4e4989
=> Adding logging

src/aktualizr_secondary/aktualizr_secondary.cc, src/aktualizr_secondary/aktualizr_secondary.h, src/aktualizr_secondary/aktualizr_secondary_config.cc, src/aktualizr_secondary/aktualizr_secondary_config.h, src/aktualizr_secondary/aktualizr_secondary_discovery.cc, src/aktualizr_secondary/aktualizr_secondary_discovery.h, src/config.h, src/ipsecondarydiscovery.cc, src/ipuptaneconnectionsplitter.cc, src/ipuptaneconnectionsplitter.h, src/utils.cc, src/utils.h, tests/aktualizr_secondary/discovery_test.cc, tests/fake_discovery/discovery_secondary.py, tests/ipsecondary_discovery_test.cc
- Remember discovered IP address and port
- Change package format accordingly
- Set default port numbers on primary to match those on secondary
=> Fix (some of) discovery issues

config/sota_autoprov_primary.toml
Change-Id: I4cc703dece09937eb273ffdb84a16b3b08176cd1
=> Add sample config file for Linux Secondaries

src/aktualizr_secondary/aktualizr_secondary.cc, src/aktualizr_secondary/aktualizr_secondary.h, src/ostree.cc, src/ostree.h, src/sotauptaneclient.cc, src/sotauptaneclient.h, src/uptane/ipuptanesecondary.cc, src/uptane/uptanerepository.cc, src/utils.cc, src/utils.h, tests/CMakeLists.txt, tests/aktualizr_secondary/uptane_test.cc, tests/ostree_test.cc, tests/utils_test.cc
I switched back to the archive format to stay in sync with the existing interface.
It still needs to be tested end to end with real provisioning.
=> Full credentials passing from primary to secondary

src/aktualizr_secondary/aktualizr_secondary.cc, src/aktualizr_secondary/aktualizr_secondary_discovery.cc, src/asn1-cer.cc, src/ipsecondarydiscovery.cc, src/ipuptaneconnection.cc, src/sotauptaneclient.cc, src/uptane/ipuptanesecondary.cc, tests/asn1_test.cc, tests/fake_discovery/discovery_secondary.py
With these changes provisioning mostly works for me except that I get a "Missing entity" error from the backend, which normally indicates that ECU registration was not successfull (although the registration itself returns 200 OK).
This issue can't be tracked down without @simao's help.
=> Fix more discovery issues

docs/linux-secondaries.adoc
Change-Id: I32a304ad568898e2c21b688e67e58e869c7fc761
=> Add basic docs on secondaries

src/ipuptaneconnection.cc
Change-Id: Iaa8c965df3d5db774f1d769b85eab86a72964c17
=> Log messages when parse fails

scripts/run_travis.py
Usage:
./scripts/run_travis.py -j JOB_ID -o run.sh
bash run.sh | ts "%F %H:%M:%.S"
=> Add tool to extract build process from .travis.yml

src/CMakeLists.txt, src/aktualizr_check_discovery/CMakeLists.txt, src/aktualizr_secondary/CMakeLists.txt, src/socket_activation/CMakeLists.txt, tests/CMakeLists.txt
Avoid issues with static libraries linking with each others halfway
=> Link socket_activation as an object library

src/p11engine.cc, src/utils.cc, src/utils.h, tests/utils_test.cc
And avoid computing array sizes in p11engine
=> Use hex conversion from boost

src/aktualizr_check_discovery/main.cc, src/sotauptaneclient.cc, src/uptane/initialize.cc, tests/uptane_test.cc
Also added similar functionality for aktualizr-check-discovery
=> Verify manifests from secondary on primary

Dockerfile, Dockerfile.deb-stable, Dockerfile.deb-testing, Dockerfile.nop11, README.adoc, scripts/get_garage_sign.py
urllib from standard library should be enough for our use case
=> Remove dependency on python3-requests

CMakeLists.txt, src/aktualizr_check_discovery/CMakeLists.txt, src/aktualizr_info/CMakeLists.txt, src/aktualizr_secondary/CMakeLists.txt, src/bootstrap.cc, src/cert_provider/main.cc, src/socketgateway.cc, src/uptane/initialize.cc, src/utilities/crypto.cc, src/utilities/crypto.h, tests/crypto_test.cc, tests/test_utils.cc, tests/uptane_ci_test.cc
Should allow to compile project without ostree and systemd under macos
=> Macos compile

src/bootstrap.cc, src/cert_provider/main.cc, src/uptane/initialize.cc, src/utilities/crypto.cc, src/utilities/crypto.h, src/utilities/keymanager.cc, src/utilities/p11engine.cc, src/utilities/p11engine.h, tests/crypto_test.cc
Freeing the right objects at the right time is tedious...
Based on #714.
=> Use automatic memory management for OpenSSL objects

src/uptane/root.cc
Change-Id: Ia75a5298c1e3390c7969ca8d7b4bd97a3ae285c9
=> Fix link error due to taking a reference to kMaxSignatures

.gitignore, .vscode/.gitignore, .vscode/launch.json, .vscode/tasks.json, config/sota_local.toml, docs/debugging-tips.adoc
Change-Id: I6f4dcdbb2dba2ceebc12279d8316dcb785238f68
=> Add docs for running locally

src/sotauptaneclient.cc, src/sotauptaneclient.h
Change-Id: Iffe7c508a56f7f9d03ceb7d01d7a5a7f5932ffe9
=> Only send network information when it changes

config/CMakeLists.txt
Is this too restrictive and/or unnecessary?
=> Set permissions of installed config files.

src/libaktualizr/crypto/crypto.h, src/libaktualizr/uptane/tuf.cc, src/libaktualizr/uptane/tuf.h, src/libaktualizr/uptane/uptanerepository.cc, src/libaktualizr/uptane/uptanerepository.h
Should fix both [PRO-4767](https://advancedtelematic.atlassian.net/browse/PRO-4767) and [PRO-4768](https://advancedtelematic.atlassian.net/browse/PRO-4768).
@heartsucker please confirm
=> Only check the highest priority hash

.gitmodules, CMakeLists.txt, src/load_tests/CMakeLists.txt
This also exposes some a warning-as-error in HdrHistogram
https://github.com/HdrHistogram/HdrHistogram_c/pull/55
=> Pull in HdrHistogram_c via git submodules

scripts/run_docker_test.sh
Can be used to easily reproduce our CI tests environments
=> Add a docker test helper script

CMakeLists.txt
Change-Id: I894ab64568a059497df9cc5f2a91df5e7b67186f
=> Only include HdrHistogram_c for load tests

src/aktualizr_info/main.cc, src/aktualizr_primary/main.cc, src/aktualizr_secondary/main.cc, src/libaktualizr/storage/fsstorage.cc, src/libaktualizr/storage/fsstorage.h, src/libaktualizr/storage/invstorage.cc, tests/prov_test.py
There are various fixes in here to fix up aktualizr-info with the new config directories changes.
=> Fixes for aktualizr-info

src/libaktualizr/crypto/crypto.cc
=> Remove attempt to squash a memory leak

src/aktualizr_secondary/aktualizr_secondary_config.cc, src/aktualizr_secondary/aktualizr_secondary_config.h, src/aktualizr_secondary/main.cc, src/libaktualizr/config/config.cc, src/libaktualizr/config/config.h, src/libaktualizr/logging/boost_logging.cc, src/libaktualizr/logging/logging.h, src/libaktualizr/utilities/config_utils.h, tests/CMakeLists.txt
Also share common code between secondary and primary configs
=> Parse configs for secondary in the same way as for primary

src/aktualizr_secondary/CMakeLists.txt, src/external_secondaries/test_isotp_interface.cc, src/libaktualizr/opcuabridge/CMakeLists.txt, src/libaktualizr/opcuabridge/common.cc, src/libaktualizr/opcuabridge/common.h, src/libaktualizr/opcuabridge/opcuabridgeclient.cc, src/libaktualizr/opcuabridge/opcuabridgeserver.cc, src/libaktualizr/uptane/CMakeLists.txt, tests/CMakeLists.txt
Suppress a few pointer arithmetic warnings
Fix location of open62541 library
Change-Id: I6991d5b55e0f3bb1610a9c9dbcffea5582b88d29
=> Fix OPC-UA build

src/aktualizr_secondary/CMakeLists.txt, tests/CMakeLists.txt
I'm going to recommend waiting to merge until https://github.com/advancedtelematic/aktualizr/pull/739/ is ready, because I don't want to make Serhiy's life harder with another million rebases. (Actually, since these tests would stay where they are, maybe it doesn't matter.)
=> More command line loglevel tests.

scripts/test.sh
This way, users will get a complete report of the static tests results
in the logs
=> Keep going while running format and tidy on CI

src/aktualizr_info/aktualizr_info_config.cc, src/aktualizr_info/aktualizr_info_config.h, src/aktualizr_secondary/CMakeLists.txt, src/aktualizr_secondary/aktualizr_secondary_config.cc, src/libaktualizr/config/config.cc, src/libaktualizr/utilities/config_utils.h, tests/CMakeLists.txt
AktualizrInfoConfig now inherits from BaseConfig just like the other configs.
=> Check that a config dir exists before using it.

Dockerfile, tests/CMakeLists.txt
Change-Id: Iddf0a1939f887aba1a8df345acd907f2a156bd48
=> Add missing entries to the 'build everything' test

Jenkinsfile
=> Cancel old Jenkins builds in PRs

src/aktualizr_secondary/uptane_test.cc, src/libaktualizr/primary/CMakeLists.txt, src/libaktualizr/primary/aktualizr.cc, src/libaktualizr/primary/reportqueue.cc, src/libaktualizr/primary/reportqueue.h, src/libaktualizr/primary/reportqueue_test.cc, src/libaktualizr/primary/sotauptaneclient.cc, src/libaktualizr/primary/sotauptaneclient.h, src/libaktualizr/uptane/uptane_ci_test.cc, src/libaktualizr/uptane/uptane_key_test.cc, src/libaktualizr/uptane/uptane_serial_test.cc, src/libaktualizr/uptane/uptane_test.cc, src/load_tests/check.cc, src/load_tests/provision.cc, tests/httpfake.h, tests/initializer_implicit_test.cc
No tests yet, waiting for confirmation of functionality and stylistic review.
=> Feat/ota 36/report download complete

src/aktualizr_repo/main.cc, src/aktualizr_repo/repo.cc, src/aktualizr_repo/repo.h, src/aktualizr_repo/repo_test.cc
Added snapshot role, fixed timestamp role format, added support for multiple targets in director targets metadata and ecuIdentifiers field in director targets.
I plan to use that to bring metadata in uptane tests closer to what we've got in the backend.
=> Add more features to aktualizr-repo

src/libaktualizr/storage/sql_utils.h, src/libaktualizr/storage/sqlstorage.cc, src/libaktualizr/storage/sqlstorage.h
This will have some effect on #821 as well. I thought about trying to rebase it myself and put this PR on top but I think @OYTIS will be more qualified to do that without making mistakes.
If merging this now would cause too much problem, we can let that sit here until #821 is ready.
=> Get rid of the old sql callback-based api

.travis.yml, CMakeLists.txt, Jenkinsfile, scripts/test.sh, src/libaktualizr/utilities/config_utils.h, src/load_tests/executor.h
So that it doesn't break in the future
=> Compile with clang on Debian testing

src/libaktualizr/primary/eventsinterpreter.cc, src/libaktualizr/primary/eventsinterpreter.h
Flatten everything so that it's clearer and less error-prone
The cascade of ifs was confusing, waiting to break some day.
This PR is probably oe-selftest worthy
=> Separate different running mode state machines

docs/Doxyfile.in, src/CMakeLists.txt, src/aktualizr_primary/main.cc, src/hmi_stub/CMakeLists.txt, src/hmi_stub/main.cc, src/libaktualizr/config/config.h, src/libaktualizr/crypto/crypto.cc, src/libaktualizr/primary/aktualizr.cc, src/libaktualizr/primary/aktualizr.h, src/libaktualizr/primary/commands.cc, src/libaktualizr/primary/commands.h, src/libaktualizr/primary/events.h, src/libaktualizr/primary/eventsinterpreter.cc, src/libaktualizr/primary/eventsinterpreter.h, src/libaktualizr/primary/eventsinterpreter_test.cc, src/libaktualizr/uptane/tuf.h, src/libaktualizr/utilities/types.h, src/sota_tools/deploy.h
There's a bit of cleaning up that could be done with the EventsInterpreter, and there is still some documentation to be done, but I'd like to solicit feedback on what I've got so far sooner rather than later.
=> Feat/ota 298/hmi api

src/libaktualizr/primary/eventsinterpreter.cc
Suppress an error, move some stuff from `ERROR` to `WARNING`
=> Review eventsinterpreter logging

src/aktualizr_primary/main.cc, src/libaktualizr/CMakeLists.txt, src/libaktualizr/campaign/CMakeLists.txt, src/libaktualizr/campaign/campaign.cc, src/libaktualizr/campaign/campaign.h, src/libaktualizr/campaign/campaign_test.cc, src/libaktualizr/campaign/test/campaigns_sample.json, src/libaktualizr/primary/commands.h, src/libaktualizr/primary/events.cc, src/libaktualizr/primary/events.h, src/libaktualizr/primary/eventsinterpreter.cc, src/libaktualizr/primary/eventsinterpreter.h, src/libaktualizr/primary/sotauptaneclient.cc, src/libaktualizr/utilities/types.cc, src/libaktualizr/utilities/types.h
Accessible from the CLI + the "new" exposed api
=> Add a new command, campaign_check

CMakeLists.txt, src/libaktualizr/package_manager/packagemanagerfake.cc, src/load_tests/stats.cc, src/sota_tools/rate_controller.h
isotp still has some issues but I do not care.
I'm not really sure why I bothered with this but it took two minutes to fix.
=> I fixed all of the complaints in our code found by the pedantic flag.

src/libaktualizr/primary/sotauptaneclient.cc
Fixed 'got new updates' problem.
=> Fix bug in tracking currently installed versions

Jenkinsfile
As already done on Travis (see #909 where Travis found some issues whereas Jenkins is silent)
=> Test with OPCUA on Jenkins

src/aktualizr_primary/main.cc
`aktualizr check` and `aktualizr --running-mode check` are equivalent
=> Make cli for `--running-mode` more user-friendly

.travis.yml
=> Fix Travis auto release upload

src/libaktualizr/storage/invstorage.cc
This fixes the case when you are testing locally and /var/sota is owned by root.
=> Don't try to read installed_versions is we don't have read permission.

src/libaktualizr/primary/sotauptaneclient.cc, src/libaktualizr/primary/sotauptaneclient.h, src/libaktualizr/uptane/exceptions.h, src/libaktualizr/uptane/fetcher.cc, tests/uptane_vector_tests.cc
This PR should pass all tests after rebasing tuf-vector-tests with my changes
=> Fix uptane_vector_tests to work properly

src/cert_provider/main.cc
=> Create target directory recursively if it doesn't exist

src/sota_tools/ostree_http_repo_test.cc, tests/sota_tools/treehub_deploy_server.py, tests/sota_tools/treehub_server.py, tests/test_utils.cc, tests/test_utils.h
The logic was already there for the fetch server, but we weren't using
it, so I just copied to the push server.
=> Test intermittently dropping HEAD requests to push server.

src/aktualizr_secondary/aktualizr_secondary.cc, src/cert_provider/main.cc, src/libaktualizr/bootstrap/bootstrap.cc, src/libaktualizr/config/config.cc, src/libaktualizr/config/config.h, src/libaktualizr/utilities/utils.cc, src/libaktualizr/utilities/utils.h, src/libaktualizr/utilities/utils_test.cc, src/load_tests/check.cc
Fixes advancedtelematic/meta-updater#420.
=> Fix/GitHub 420/gateway url newline

CHANGELOG.md, docs/configuration.adoc
If everything goes well, I'll set the tag on the merge commit of this PR.
Please report anything missing!
=> Prepair for 2018.13

config/secondary/virtualsec.json, config/sota_local.toml, docs/running-locally.adoc, docs/selectively-triggering-aktualizr.adoc
This is my method for really easy fake devices.
Would appreciate some proofreading (typos and going through the steps).
=> Document the creation of fake devices

src/libaktualizr/uptane/fetcher_test.cc
=> Make test_fetcher more stable

actions.md, config/sql/migration/migrate.12.sql, config/sql/schema.sql, src/aktualizr_secondary/CMakeLists.txt, src/aktualizr_secondary/aktualizr_secondary_common.cc, src/libaktualizr/bootloader/CMakeLists.txt, src/libaktualizr/bootloader/bootloader.cc, src/libaktualizr/bootloader/bootloader.h, src/libaktualizr/bootloader/bootloader_config.h, src/libaktualizr/bootloader/bootloader_test.cc, src/libaktualizr/package_manager/debianmanager_test.cc, src/libaktualizr/package_manager/ostreemanager.cc, src/libaktualizr/package_manager/ostreemanager.h, src/libaktualizr/package_manager/ostreemanager_test.cc, src/libaktualizr/package_manager/packagemanagerfactory.cc, src/libaktualizr/package_manager/packagemanagerfactory.h, src/libaktualizr/package_manager/packagemanagerfactory_test.cc, src/libaktualizr/primary/sotauptaneclient.cc, src/libaktualizr/storage/invstorage.h, src/libaktualizr/storage/sqlstorage.cc, src/libaktualizr/storage/sqlstorage.h
Not useful by itself, will need to be integrated closely to the ostree package manager.
=> Detect reboot

.gitmodules, scripts/make_ostree_sysroot.sh, src/libaktualizr/opcuabridge/CMakeLists.txt, src/libaktualizr/opcuabridge/opcuabridgediscoveryclient.cc, tests/ostree-scripts/README.md, tests/ostree-scripts/makedeployed.sh, tests/ostree-scripts/makephysical.sh
It now makes little sense to keep them separate
Sourced from 291cb196330ee28c6e126f9c31778c97cc1df2ae @advancedtelematic/ostreesysroot
=> Move ostree sysroot scripts to aktualizr repo

CHANGELOG.md, actions.md, src/aktualizr_secondary/opcuaserver_secondary_delegate.cc, src/libaktualizr/package_manager/debianmanager.h, src/libaktualizr/package_manager/ostreemanager.cc, src/libaktualizr/package_manager/ostreemanager.h, src/libaktualizr/package_manager/ostreemanager_test.cc, src/libaktualizr/package_manager/packagemanagerconfig.cc, src/libaktualizr/package_manager/packagemanagerconfig.h, src/libaktualizr/package_manager/packagemanagerfactory.cc, src/libaktualizr/package_manager/packagemanagerfake.cc, src/libaktualizr/package_manager/packagemanagerfake.h, src/libaktualizr/package_manager/packagemanagerinterface.h, src/libaktualizr/primary/aktualizr.h, src/libaktualizr/primary/aktualizr_test.cc, src/libaktualizr/primary/reportqueue.cc, src/libaktualizr/primary/reportqueue.h, src/libaktualizr/primary/sotauptaneclient.cc, src/libaktualizr/primary/sotauptaneclient.h, src/libaktualizr/storage/invstorage.h, src/libaktualizr/storage/sqlstorage.cc, src/libaktualizr/storage/sqlstorage.h, src/libaktualizr/uptane/uptane_ci_test.cc, src/libaktualizr/utilities/types.h
Based on #1016. Worked as PoC, will need to be more extensively tested.
=> Feat/ota 1569/manifest after reboot

partial/libuptiny/crypto_common.h, scripts/run_travis.py, scripts/selfupdate_server.py, src/aktualizr_repo/run/serve_repo.py, src/libaktualizr/crypto/crypto.cc, src/libaktualizr/primary/initializer.h
All of these were raised by https://lgtm.com/projects/g/advancedtelematic/aktualizr
=> Fix some minor code issues

src/libaktualizr/http/httpclient.cc
=> http: fix ownership issue in downloadAsync

src/libaktualizr/primary/sotauptaneclient.cc
Not sure how it could work, probably some tests are also missing.
=> primary: fix bug/typo in resume()

CMakeLists.txt, src/libaktualizr/logging/CMakeLists.txt, src/libaktualizr/logging/android_log_sink.cc, src/libaktualizr/logging/default_log_sink.cc, src/libaktualizr/logging/logging.cc, src/libaktualizr/logging/logging.h, src/libaktualizr/logging/logging_config.cc, src/libaktualizr/logging/logging_config.h
Signed-off-by: Maksim Beznos <maximbns@gmail.com>
=> Logging implementation revised

README.adoc
It's not really integrated with Genivi any more.
=> Don't mention GENIVI in the README.md

ci/gitlab/.gitlab-ci.yml
Signed-off-by: Kandasamy <manikandan.kandasamy@here.com>
=> Add support for GitLab Integration resolves OTA-1937

src/libaktualizr/primary/sotauptaneclient.cc, src/libaktualizr/uptane/uptane_test.cc
Signed-off-by: Serhiy Stetskovych <patriotyk@gmail.com>
=> Complain when tries to install target with unknown ECU ID

CHANGELOG.md, src/libaktualizr/storage/sqlstorage_base.cc
=> Tweak sql migration logs

.travis.yml, ci/gitlab/.gitlab-ci.yml, docker/Dockerfile-test-install.ubuntu.bionic, docker/Dockerfile-test-install.ubuntu.xenial, docker/Dockerfile.debian.testing, docker/Dockerfile.ubuntu.bionic, docker/Dockerfile.ubuntu.xenial
Mess with caching as we build images for different PRs all the time
=> Do not add source in testing docker images

ci/gitlab/.gitlab-ci.yml
=> Fix gitlab docker caching again

src/libaktualizr/primary/sotauptaneclient.cc
- the report in "Report not sent" does not exist anymore
- the putManifest disabled message sounds alarming, move it to DEBUG
=> Fix two log messsages

config/sota_hsm_prov.toml, config/sota_implicit_prov_ca.toml, docs/hsm-provisioning.adoc, docs/implicit-provisioning.adoc
See also https://github.com/advancedtelematic/ats-garage-docs/pull/76.
=> Fix/ota 2071/implicit prov docs

src/libaktualizr/bootloader/bootloader.cc
Otherwise it won't work...
Useful when running aktualizr as an unprivileged user on a system where it's also running as a service.
=> Check that reboot sentinel dir belongs to current user

src/libaktualizr/primary/aktualizr.h, src/libaktualizr/primary/sotauptaneclient.cc, src/libaktualizr/primary/sotauptaneclient.h, src/libaktualizr/uptane/imagesrepository.h, src/libaktualizr/uptane/tuf.cc, src/libaktualizr/uptane/tuf.h, src/libaktualizr/uptane/uptane_delegation_test.cc, tests/uptane_repo_generation/delegation_nested.sh
It is not a part of API yet, and probably shouldn't be
part of Uptane API ever. It is possible to introduce TUF
API in future.
Suggested-by: Andy Doan <doanac@beadoan.com>
=> Add iterator to loop over all targets in delegation tree

CHANGELOG.md
I'd like to make a new release for @stevana. Any objections?
=> Update changelog for a new release.

actions.md, src/aktualizr_primary/main.cc, src/hmi_stub/main.cc, src/libaktualizr/primary/aktualizr.h, src/libaktualizr/primary/aktualizr_test.cc, src/libaktualizr/primary/events.h, src/libaktualizr/primary/sotauptaneclient.h, src/libaktualizr/uptane/uptane_init_test.cc
=> OTA-1941: Tests: Hostname as hwd ID, Download progress reporting

src/libaktualizr/primary/aktualizr.cc, src/libaktualizr/primary/sotauptaneclient.cc
=> Don't send manifest & check for updates if there are pending updates

docs/README.adoc, docs/deb-package-install.adoc
=> Improve docs about release process.

scripts/get_garage_sign.py, src/sota_tools/CMakeLists.txt
Can be used for offline compilation and reproductible builds
=> Add option to directly supply a cli-xxx.tgz for garage-sign

scripts/run-valgrind.in
To make it configurable after configure and compile time
=> Add a valgrind bypass option in run-valgrind

partial/tests/targets/test.sh, tests/ostree-scripts/makedeployed.sh, tests/ostree-scripts/makephysical.sh
=> Use `bare-user-only` for ostree tests

tests/aktualizr.supp
Could be serious? Maybe we should fix it.
=> Suppress a boost 1.69.0 valgrind error

actions.md, scripts/test.sh, src/cert_provider/CMakeLists.txt, src/cert_provider/cert_provider_autoprov_test.cc, src/cert_provider/cert_provider_test.cc, src/cert_provider/cert_provider_test.h, src/cert_provider/main.cc, tests/test_utils.cc, tests/test_utils.h
=> OTA-1685: aktualizr-cert-provider tests

src/aktualizr_lite/main.cc, src/aktualizr_primary/main.cc, src/aktualizr_secondary/main.cc, src/cert_provider/main.cc, src/hmi_stub/main.cc
=> Align executables' exit status code across the project

src/aktualizr_info/aktualizr_info_test.cc, src/libaktualizr/http/httpclient_test.cc, src/libaktualizr/opcuabridge/opcuabridge_messaging_test.cc, src/libaktualizr/opcuabridge/opcuabridge_secondary_update_test.cc, src/libaktualizr/uptane/fetcher_death_test.cc, src/libaktualizr/uptane/fetcher_test.cc, src/libaktualizr/uptane/ipsecondary_discovery_test.cc, src/libaktualizr/uptane/uptane_network_test.cc, src/sota_tools/authenticate_test.cc, src/sota_tools/deploy_test.cc, src/sota_tools/ostree_http_repo_test.cc, src/sota_tools/ostree_object_test.cc, src/sota_tools/treehub_server_test.cc, tests/test_utils.cc, tests/test_utils.h
=> Use boost::process consistently across all tests

src/aktualizr_info/main.cc, src/aktualizr_repo/main.cc, src/cert_provider/main.cc, src/libaktualizr/storage/sqlstorage.cc, src/sota_tools/garage_check.cc, src/sota_tools/request_pool.cc
Signed-off-by: Eugene Smirnov <evgenii.smirnov@here.com>
=> Minor fixes to make clang-tidy-7 happy

docker/Dockerfile.ubuntu.xenial, scripts/build_ubuntu.sh
=> Switch to Stretch Debian release since Jessie is not supported

ci/gitlab/.gitlab-ci.yml, docker/Dockerfile.ubuntu.bionic
OTA-2461
Thanks to @kmanikandan-kmk, who did most of the work, it was just a matter of plugging things together.
=> Use credentials in GitLab CI

CHANGELOG.md
Hopefully if you are happy I can make the release tomorrow!
=> Update changelog with recent work.

.gitattributes, .travis.yml, scripts/make_src_archive.sh
Also build a full source archive! (Fixes #959)
Example here: https://github.com/advancedtelematic/aktualizr/releases/tag/2019.3-test (will remove when we'll have the proper 2019.3)
Sorry for all the noisy test releases...
=> Real fix for CI creds

docs/README.adoc, docs/deb-package-install.adoc
Mostly just listing 2019.3, but also fixing some small things about the process.
=> Update docs about releases.

docker/Dockerfile.ubuntu.xenial, src/libaktualizr/uptane/uptane_test.cc, tests/uptane_test_common.h
About 5x speedup on test_aktualizr!
=> Do not generate a ton of secondary keys during tests

tests/CMakeLists.txt, tests/fake_http_server/fake_test_server.py, tests/ipsecondary_test.py
=> OTA-2540: IP Secondary integration tests

src/libaktualizr/package_manager/ostreemanager_test.cc, tests/test_data/package.manifest
Remove tests/test_data/package.manifest
and generate test data on the fly
=> Remove tests/test_data/package.manifest

.travis.yml, Jenkinsfile, ci/gitlab/.gitlab-ci.yml, docker/Dockerfile.debian.testing, docs/Doxyfile.in, scripts/test.sh, src/libaktualizr/uptane/tuf.h
The zee_test branch is messy. I cleaned up something and lost something and merged something not mine. I have to give up that branch and create a new one, otherwise this is gonna take more of my time so I can't move to my new task. I'll practice using git in my spare time instead.Hope it's ok.
=> auto make docs

docs/README.adoc
It seems like every time I do this I find something wrong with the steps.
=> Add 2019.4 doc link and fix some bits of the process.

src/aktualizr_repo/main.cc
By the way, what kind of message would users be interested, and what kind of message would be probably just garbage?
=> an immature version just to make sure I'm on the right track

docs/README.adoc
=> Update README to reference to the new release doxygen doc

src/libaktualizr/primary/CMakeLists.txt
=> Disable test_aktualizr_fullostree on ptest

src/sota_tools/deploy_test.cc, src/sota_tools/server_credentials.cc, tests/sota_tools/treehub_server.py
=> OTA-2851: Support ostree refs posting by the test treehub server

ci/gitlab/.gitlab-ci.yml
See https://gitlab.com/gitlab-org/gitlab-runner/issues/4499
Cherry-picked from https://github.com/advancedtelematic/aktualizr/pull/1262 for fast-tracking.
=> Fix issue with gitlab and Docker 19

ci/gitlab/.gitlab-ci.yml
Will probably only enable it for master merge but it's enabled here for the test.
=> Launch ptest at the end of pipelines

docs/posix-secondaries-bitbaking.adoc
Based on a suggestion from @smilingwombat.
=> Note that wifi SSID is case sensitive.

src/aktualizr_info/main.cc
This will work even if there is no database or if it's busy, as long as
it falls back to a good state at some point.
That seems to be a reason why there was so many failures while waiting for provisioning on CI (on master at least).
Tried with a manual test on a local Linux, not yet on yocto.
=> Make aktualizr-info --wait-until-provisioned more robust

src/cert_provider/cert_provider_test.cc
=> Make the cert provider tests immuned to changes in an openssl format

ci/gitlab/.gitlab-ci.yml
Small rework of #1261.
One significant change is that the condition is now on a variable being present and not just "schedule". It makes it a bit more flexible: it's possible to launch this stage manually and it leaves the possibility to have schedules that don't include this test.
=> Veracode bis

.travis.yml
So that ccache can be built incrementally
=> Add a timeout for Travis runs

src/aktualizr_lite/main.cc
=> aktualizr-lite: Fix incorrect storing of ecu hwid

src/libaktualizr/package_manager/dockerappmanager.cc, src/libaktualizr/package_manager/dockerappmanager.h
=> docker-app: Fix clang-tidy warnings

ci/gitlab/.gitlab-ci.yml
Trigger otf tests on aktualizr and garage-deploy releases
=> Trigger otf pipeline on new releases

ci/gitlab/.gitlab-ci.yml
Properly add binaries to the veracode submission archieve.
=> Fix veracode packing

src/libaktualizr/package_manager/CMakeLists.txt, src/libaktualizr/uptane/CMakeLists.txt, src/sota_tools/CMakeLists.txt, tests/prov_test_common.py
Unclear why they should be needed in most cases
=> Remove some NO_VALGRIND test properties

docs/ota-client-guide/modules/ROOT/pages/add-ota-functonality-existing-yocto-project.adoc
The extra newline apparently matters.
See https://docs.ota.here.com/ota-client/dev/add-ota-functonality-existing-yocto-project.html for how it looks now.
=> Fix bulleted list formatting.

docs/ota-client-guide/modules/ROOT/nav.adoc, docs/ota-client-guide/modules/ROOT/pages/yocto-release-branches.adoc
Please review critically. I'm not sure I've done a great job explaining this.
=> Add doc about the considerations of changing release branches.

src/libaktualizr/uptane/uptanerepository.cc, tests/CMakeLists.txt, tests/fake_http_server/fake_test_server.py, tests/ipsecondary_test.py, tests/test_backend_failure.py, tests/test_fixtures.py
Signed-off-by: Mykhaylo Sul <ext-mykhaylo.sul@here.com>
=> OTA-2743: Initial set of negative tests aiming Director and Repo

docs/ota-client-guide/modules/ROOT/pages/release-process.adoc
=> Fix inaccurate homebrew release instructions

docs/ota-client-guide/modules/ROOT/pages/build-configuration.adoc
Stopgap measure until we have actual checks in place.
=> Note about spaces and apostrophes in OSTREE_BRANCHNAME.

tests/test_backend_failure.py, tests/test_fixtures.py
Signed-off-by: Mykhaylo Sul <ext-mykhaylo.sul@here.com>
=> OTA-2743: Use conditional variable for an installation result

src/aktualizr_lite/main.cc, src/libaktualizr/package_manager/docker_fake.sh, src/libaktualizr/package_manager/dockerappmanager.cc, src/libaktualizr/package_manager/dockerappmanager_test.cc, src/libaktualizr/primary/sotauptaneclient.h
These are 3 different fixes that should improve aktualizr-lite and docker-app support.
=> dockerapp fixups

ci/gitlab/.gitlab-ci.yml
=> DOCS: Exclude docs-only branches from a few more CI jobs

docs/ota-client-guide/modules/ROOT/nav.adoc, docs/ota-client-guide/modules/ROOT/pages/_partials/recommended-steps.adoc, docs/ota-client-guide/modules/ROOT/pages/build-agl.adoc, docs/ota-client-guide/modules/ROOT/pages/build-qemu.adoc, docs/ota-client-guide/modules/ROOT/pages/build-raspberry.adoc, docs/ota-client-guide/modules/ROOT/pages/pushing-updates.adoc, docs/ota-client-guide/modules/ROOT/pages/simulate-device-basic.adoc, docs/ota-client-guide/modules/ROOT/pages/software-management.adoc
Responding to initial feedback by Greg and Xavier
Also fixing small issue with :page-partial: not working if
underneath github note.
=> OTA-3746: Added fixes requested in feedback

docs/ota-client-guide/modules/ROOT/pages/install-garage-sign-deploy.adoc, docs/ota-client-guide/modules/ROOT/pages/intro-prod.adoc
note: I'd like to hold off on merging this until #1377 is in, so we can smoke test that trigger pipeline
=> DOCS: fix link to image cross-deployment page

docs/ota-client-guide/modules/ROOT/nav.adoc, docs/ota-client-guide/modules/ROOT/pages/_partials/recommended-steps.adoc, docs/ota-client-guide/modules/ROOT/pages/build-agl.adoc, docs/ota-client-guide/modules/ROOT/pages/build-qemu.adoc, docs/ota-client-guide/modules/ROOT/pages/build-raspberry.adoc, docs/ota-client-guide/modules/ROOT/pages/pushing-updates.adoc
Adding CTA and link to next step which guides the reader to try and upload some updates to sample software.
=> Adding CTA for next steps

ci/gitlab/.gitlab-ci.yml
@lbonn: I promise this is the last one :-P. (I will likely backport it, but I'll just push directly rather than spamming with PRs.)
=> DOCS: Also exclude docs/ branches from CI pipelines

tests/CMakeLists.txt
Currently failing and probably not worth fixing
=> Disable test_backend_failure on ptest

tests/ostree_mock.c
=> Fix runtime memory leaking in the ostree mock

src/aktualizr_lite/CMakeLists.txt, src/aktualizr_lite/helpers.cc, src/aktualizr_lite/helpers.h, src/aktualizr_lite/helpers_test.cc, src/aktualizr_lite/main.cc, src/aktualizr_lite/ostree_mock.cc
This change nets us a little more test coverage and sets things up so that we can add more in the future. The first change is just renaming a file. The second change adds in a little test coverage to the "liteClient" and the third change does a small refactor that's now a lot easier to test thanks to the first 2 changes.
=> aktualizr-lite: Move more code to "helpers" so it can be tested

src/libaktualizr/package_manager/dockerappmanager.cc
Hopefully this will help readers of the code understand things more
clearly.
=> dockerappmanager: Add some module level documentation

docs/ota-client-guide/modules/ROOT/pages/developer-tools.adoc
- Added adjective "conserve": Technically bandwidth isn't something that you want to minimize - your want to have as much of it as possible.
- "Footprint" needs an article, you can't say "it minimizes ... footprint" - added "your".
- Broke up very long sentence (still not happy with the final sentence "...file system deployments" sounds a bit vague but can't think of anything better right now...)
=> Misc Language fixes

tests/test_aktualizr_kill.py, tests/test_fixtures.py
Try to resolve the failures we get on CI.
There might be something else, stay tuned.
=> Fix test_aktualizr_kill

CHANGELOG.md, docs/README.adoc, docs/ota-client-guide/modules/ROOT/pages/_partials/aktualizr-version.adoc, docs/ota-client-guide/modules/ROOT/pages/release-process.adoc
~~It is also about time to merge https://github.com/advancedtelematic/aktualizr/pull/1356/, which  depends on https://github.com/advancedtelematic/aktualizr/pull/1412. (Would be nice to have https://github.com/advancedtelematic/aktualizr/pull/1410 as well if possible.)~~
=> Update changelog and other docs to 2019.9.

docs/ota-client-guide/modules/ROOT/pages/_partials/recommended-steps.adoc, docs/ota-client-guide/modules/ROOT/pages/account-setup.adoc, docs/ota-client-guide/modules/ROOT/pages/generate-devicecert.adoc, docs/ota-client-guide/modules/ROOT/pages/generatetest-devicecert.adoc
This relates to OTA-3884, to get the link checker passing.
=> DOCS: Prevent asciidoctor from auto-linkifying example urls

docs/ota-client-guide/modules/ROOT/pages/supported-boards.adoc
Also fix a syntax error and specify rough estimate of general RAM usage.
=> Update mininum RAM requirements.

scripts/make_src_archive.sh
=> Use upstream version of git-archive-all

tests/test_backend_failure.py, tests/test_fixtures.py
=> Add a test for aktualizr polling a "spoofed" repo

tests/test_backend_failure.py
=> Don't autostart aktualizr if started in the test body

include/libaktualizr-c.h, src/libaktualizr-c/libaktualizr-c.cc, src/libaktualizr-c/test/api-test.c
Signed-off-by: Mykola Chekhovoi <ext-mykola.chekhovoi@here.com>
=> Minor changes for OTA-3211. Aktualizr_free_target_name added

src/libaktualizr/primary/aktualizr_test.cc
Note, however, that if you were to check for updates between the two calls, that would most likely confuse the backend.
Note that this is meant to cover the case that was broken when https://github.com/advancedtelematic/aktualizr/blob/test/split-update/src/libaktualizr/primary/sotauptaneclient.cc#L896 was not guarded by the `if` clause. I still don't like dropping Targets metadata, but this proves that we can at least do it fairly  safely only if there are problems.
=> Test installing updates in separate calls.

src/libaktualizr/primary/reportqueue.cc
It was even appearing in the happy case
=> Fix a wrong scary log message

docs/ota-client-guide/modules/ROOT/nav.adoc, docs/ota-client-guide/modules/ROOT/pages/generate-devicecert.adoc, docs/ota-client-guide/modules/ROOT/pages/hsm-provisioning-example.adoc
I have been doing my tests on a desktop right now, this will probably need a quick tweak once I try it with a yocto-built image.
=> Document using an HSM with OpenSC

src/aktualizr_secondary/uptane_verification_test.cc
=> Run test_uptane_verification_test with ed25519

docs/ota-client-guide/modules/ROOT/pages/hsm-provisioning-example.adoc
As it currently stands on meta-updater master.
=> Document HSM integration with Yocto

src/libaktualizr/uptane/uptane_test.cc
Some events were missed when buffered together
=> Fix flaky Uptane.ProvisionOnServer

docs/ota-client-guide/modules/ROOT/examples/virtualsec.json, docs/ota-client-guide/modules/ROOT/pages/simulate-device-basic.adoc
Cherry-pick of https://github.com/advancedtelematic/aktualizr/pull/1505/, but for this branch, only update the example in the docs.
=> Use a bool type instead of a string in the virtual secondary config

docs/ota-client-guide/modules/ROOT/nav.adoc, docs/ota-client-guide/modules/ROOT/pages/virtual-secondaries.adoc
Signed-off-by: amma <awuraaamma.okyere-boateng@here.com>
=> Virtual Secondaries page added

CONTRIBUTING.md, docs/doxygen/Doxyfile.in
Removed some redundant/obvious/irrelevant bits and added some more detail to reflect our current standards and preferences.
This is still up for discussion, so if you disagree with any of this or think something is missing, please speak up.
=> Update code contribution guidelines.

docs/ota-client-guide/modules/ROOT/pages/add-ota-functonality-existing-yocto-project.adoc
Additional information added to third point of "add-ota-functionality-existing-yocto-project.adoc".
Signed-off-by: amma <awuraaamma.okyere-boateng@here.com>
=> Edit of third point in integration process

docs/ota-client-guide/modules/ROOT/nav.adoc, docs/ota-client-guide/modules/ROOT/pages/_partials/why-different-prov-methods.adoc, docs/ota-client-guide/modules/ROOT/pages/client-provisioning-methods.adoc, docs/ota-client-guide/modules/ROOT/pages/deploy-checklist.adoc, docs/ota-client-guide/modules/ROOT/pages/enable-device-cred-provisioning.adoc, docs/ota-client-guide/modules/ROOT/pages/generate-devicecert.adoc, docs/ota-client-guide/modules/ROOT/pages/generate-selfsigned-root.adoc, docs/ota-client-guide/modules/ROOT/pages/pki.adoc, docs/ota-client-guide/modules/ROOT/pages/provide-root-cert.adoc
Revision of Device provisioning page and addition of the page as a sub-level to Security page.
=> Revision of Provisioning page

docs/ota-client-guide/modules/ROOT/pages/add-ota-functonality-existing-yocto-project.adoc
=> DOCS: Fix invalid anchor tag; content was moved to another page

CHANGELOG.md, docs/README.adoc, docs/ota-client-guide/modules/ROOT/pages/_partials/aktualizr-version.adoc
=> Update the changelog and versions for 2020.2

docs/ota-client-guide/modules/ROOT/pages/posix-secondaries-bitbaking.adoc
=> OTA-4388: Add SECONDARY_UPDATE_TYPE description to the doc

CONTRIBUTING.md
Also improve some other bits about Jira and CI.
=> CONTRIBUTING: clarify TODO comments.

src/virtual_secondary/managedsecondary.h
=> changing access specifiers in managed secondary interface

src/libaktualizr/package_manager/docker_fake.sh, src/libaktualizr/package_manager/dockerapp_bundles.cc, src/libaktualizr/package_manager/dockerapp_standalone.cc, src/libaktualizr/package_manager/dockerappmanager.cc, src/libaktualizr/package_manager/dockerappmanager.h, src/libaktualizr/package_manager/dockerappmanager_test.cc
This brings in 2 changes we've been running in our aktualizr tree for a few months now.
=> dockerapp updates

scripts/publish_github_docs.sh, scripts/publish_github_rls.py
* more retries when using the github api
* do not trip if the doc release has no work to do
=> Fix some edge cases in the release scripts

docs/ota-client-guide/modules/ROOT/pages/account-setup.adoc
Reverts advancedtelematic/aktualizr#1580
=> Revert "Add the Additional environments subsection"

docs/ota-client-guide/modules/ROOT/pages/account-setup.adoc
In a separate section, describe that, instead of creating multiple
accounts, users can create additional env using only
one account. Add a beta icon to that feature.
Relates-to: OTA-4601
Note: this is being re-opened because the previous PR was merged prematurely. @houcros will merge this once the corresponding server feature is live.
=> OTA-4601 Add the Additional environments subsection

README.adoc, docs/ota-client-guide/modules/ROOT/pages/release-process.adoc
=> OTA-4594: update the doc on brewing aktualizr on MacOS

ci/gitlab/.gitlab-ci.yml, docs/ota-client-guide/modules/ROOT/pages/release-process.adoc
Bump a formula PR for the tap at the end of the OSX release job.
=> OTA-4594: Bump formula PR for the tap

docs/ota-client-guide/modules/ROOT/nav.adoc, docs/ota-client-guide/modules/ROOT/pages/debugging-tips.adoc, docs/ota-client-guide/modules/ROOT/pages/reporting-problems.adoc
This came out of a discussion with our support team.
=> New doc about getting useful information when reporting problems.

ci/gitlab/.gitlab-ci.yml
=> ci: trigger the osx build job unconditionally

src/libaktualizr/storage/sqlstorage.cc
If the ECU serial is not found, that isn't necessarily an error. During initialization, it is in fact expected.
=> Improve logging during database initialization.

ci/gitlab/.gitlab-ci.yml
=> fix: update the formula with a new version before bottling a new release

docs/ota-client-guide/modules/ROOT/pages/release-process.adoc
=> DOCS: add explicit instructions for editing antora.yml to release docs

docs/ota-client-guide/antora.yml
=> DOCS: Remove latest tag from 2020.3-docs branch

src/libaktualizr/package_manager/dockerappmanager.cc, src/libaktualizr/package_manager/dockerappmanager_test.cc
Fix a copy paste bug introduced by:
https://github.com/advancedtelematic/aktualizr/commit/48613a90263ee2b022e4568abf157157e4beab81
=> pacman: Fix docker prune configuration handling

CMakeLists.txt, thirdparty.spdx
Mostly just bringing up to speed, although a few are still a bit vaguely defined.
=> Updates to the versions of dependencies.

docs/ota-client-guide/modules/ROOT/pages/deb-package-install.adoc, docs/ota-client-guide/modules/ROOT/pages/generating-provisioning-credentials.adoc, docs/ota-client-guide/modules/ROOT/pages/yocto.adoc
=> DOCS: Some asciidoc cleanups to prep for analytics

docs/ota-client-guide/modules/ROOT/nav.adoc, docs/ota-client-guide/modules/ROOT/pages/upload-large-binary.adoc
A step by step guide on how to upload large binary files using the `garage-sign` tool.
Relates-to: OTA-5002
Signed-off-by: amma <awuraaamma.okyere-boateng@here.com>
=> New page on how to upload a large binary file

ci/gitlab/.gitlab-ci.yml
These errors are really getting annoying...
=> Try to solve clone error for package tests

src/libaktualizr/uptane/imagerepository.cc
Fixes https://github.com/advancedtelematic/aktualizr/issues/1692. Thanks for catching this @mike-sul!
=> imagerepository.cc: Fix typo.

docs/ota-client-guide/modules/ROOT/pages/build-configuration.adoc
See https://github.com/advancedtelematic/meta-updater/pull/728.
=> Document OSTREE_DEVICETREE.

CHANGELOG.md
Tagging a few extra people to make sure the text about upgrading is appropriately understandable.
=> CHANGELOG: update and include a warning about updating Secondaries.

src/virtual_secondary/managedsecondary.h
Tested with libaktualizr-demo-app
=> ManagedSecondary: allow child classes to use SecondaryProvider

ci/gitlab/.gitlab-ci.yml
Signed-off-by: Robert Danitz <robert.danitz@here.com>
=> checkout submodules on aktualizr-app image build

actions.md
I know this is obsolete, but for what it does cover, I want it to be accurate.
=> actions.md: Minor updates to reflect current state.

.github/workflows/update-docker.yml
Hopefully will fix https://github.com/advancedtelematic/aktualizr/runs/873458617.
=> Fix a typo in naming the Ubuntu Focal dockerfile.

docs/ota-client-guide/modules/ROOT/pages/use-your-own-deviceid.adoc
* Change the Developer Guide version to 2020.8.
* Modify the instruction on how to create a custom device ID.
Relates-to: OTA-5118
=> Change the guide version & modify 1 instruction

docs/ota-client-guide/modules/ROOT/nav.adoc, docs/ota-client-guide/modules/ROOT/pages/change-signature-thresholds.adoc, docs/ota-client-guide/modules/ROOT/pages/garage-sign-reference.adoc, docs/ota-client-guide/modules/ROOT/pages/keep-local-repo-on-external-storage.adoc, docs/ota-client-guide/modules/ROOT/pages/remove-sw-version.adoc, docs/ota-client-guide/modules/ROOT/pages/upload-large-binary.adoc
Document how to:
* Remove a sw version.
* Store keys on external storage.
* Use signature thresholds.
Relates-to: OTA-5062
=> Garage-sign documentation

src/libaktualizr/CMakeLists.txt
=> an installation of libaktualizr

docs/ota-client-guide/modules/ROOT/pages/aktualizr-config-options.adoc
Mention that users should not use `/` as a path in config.
Relates-to: OTA-5095
=> Add info on the aktualizr config options page

src/aktualizr_secondary/CMakeLists.txt, src/cert_provider/CMakeLists.txt, src/libaktualizr-c/CMakeLists.txt, src/libaktualizr/CMakeLists.txt, src/libaktualizr/config/CMakeLists.txt, src/libaktualizr/config/base_config.cc, src/libaktualizr/config/config.cc
@kbushgit can you confirm that my separation of a few functions into base_config.cc still works for external users of libaktualizr?
=> Fix/ota 4544/secondary libs

CMakeLists.txt, src/virtual_secondary/virtualsecondary.h
A couple of minor clean-ups I spotted while browsing the code. I hope these are useful!
=> Minor cleanups

docs/ota-client-guide/modules/ROOT/pages/supported-boards.adoc
We forgot to add it here when the PR was merged. Also fix some other minor changes in meta-updater.
=> supported-boards.adoc: Add NXP LS1043ARDB.

src/aktualizr_get/main.cc
- Remove checking "command" option
- Make "--url/-u" mandatory
Signed-off-by: Mike Sul <mikesul.eng@gmail.com>
=> aktualizr-get: fix the issue with param check

src/aktualizr_get/get.cc, src/aktualizr_get/get.h, src/aktualizr_get/get_test.cc, src/aktualizr_get/main.cc
=> aktualizr-get: Allow passing HTTP headers

docs/ota-client-guide/modules/ROOT/nav.adoc, docs/ota-client-guide/modules/ROOT/pages/finding-unsigned-metadata.adoc, docs/ota-client-guide/modules/ROOT/pages/garage-sign-reference.adoc
Update of documentation according to [comment](https://saeljira.it.here.com/browse/OTA-5253?focusedCommentId=4816454&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-4816454) and 5.2. Exposing payload of [Integration document](https://confluence.in.here.com/display/OTA/Integration+of+Garage+Tools+with+Customer+KeyManagement+System)
=> Add "Find the unsigned Root and Targets metadata" page to docs

docs/ota-client-guide/modules/ROOT/pages/garage-sign-reference.adoc
List all of the garage-sign-related instructions on the reference page.
Relates-to: OTA-5253
=> Add a link

CHANGELOG.md, docs/README.adoc, docs/ota-client-guide/antora.yml, docs/ota-client-guide/modules/ROOT/nav.adoc, docs/ota-client-guide/modules/ROOT/pages/_partials/aktualizr-version.adoc, docs/ota-client-guide/modules/ROOT/pages/aktualizr-config-options.adoc, docs/ota-client-guide/modules/ROOT/pages/finding-unsigned-metadata.adoc, docs/ota-client-guide/modules/ROOT/pages/garage-sign-reference.adoc
=> Feat/prep 2020.10

docs/ota-client-guide/modules/ROOT/pages/sign-with-external-signature.adoc
Signed-off-by: Viktor Molitskyi <ext-viktor.molitskyi@here.com>
=> OTA-5369 Update `sign with external signature` example script

docs/ota-client-guide/modules/ROOT/pages/build-configuration.adoc
=> Fix 404 error for broken URLs in 2020.10-docs

docs/ota-client-guide/modules/ROOT/pages/build-configuration.adoc
=> Fix other 404 error for broken URLs in docs

docs/ota-client-guide/modules/ROOT/pages/ostree-and-treehub.adoc
=> Fix 503 error in atomic URL in 2020.8 docs

docs/ota-client-guide/modules/ROOT/pages/ostree-and-treehub.adoc
=> Fix 503 error in atomic URL

docs/ota-client-guide/modules/ROOT/pages/bsp-integration.adoc
Changed link.
Relates-To: OTA-5751
Signed-off-by: Vitalii Yevtushenko ext-vitalii.yevtushenko@here.com
=> Changed link to distroboot docs 

docs/ota-client-guide/modules/ROOT/pages/bsp-integration.adoc
Changed link.
Relates-To: OTA-5751
Signed-off-by: Vitalii Yevtushenko ext-vitalii.yevtushenko@here.com
=> Changed link to distroboot docs

README.adoc, docs/ota-client-guide/modules/ROOT/pages/generate-devicecert.adoc, docs/ota-client-guide/modules/ROOT/pages/generate-selfsigned-root.adoc, docs/ota-client-guide/modules/ROOT/pages/release-process.adoc, docs/ota-client-guide/modules/ROOT/pages/simulate-device-basic.adoc
Cleaning up support for MacOS & Homebrew 
Relates-To: OTA-5608
Signed-off-by: Vitalii Yevtushenko ext-vitalii.yevtushenko@here.com
=> Cleaning up support for MacOS & Homebrew 

README.adoc, docs/ota-client-guide/modules/ROOT/pages/generate-devicecert.adoc, docs/ota-client-guide/modules/ROOT/pages/generate-selfsigned-root.adoc, docs/ota-client-guide/modules/ROOT/pages/release-process.adoc, docs/ota-client-guide/modules/ROOT/pages/simulate-device-basic.adoc
Cleaning up support for MacOS & Homebrew
Relates-To: OTA-5608
Signed-off-by: Vitalii Yevtushenko ext-vitalii.yevtushenko@here.com
=> Cleaning up support for MacOS & Homebrew

docs/ota-client-guide/modules/ROOT/pages/garage-sign-reference.adoc
Signed-off-by: Oleksii Hubrii <ext-oleksii.hubrii@here.com>
=> update garage-sign reference for aktualizr version 2020.10

docs/ota-client-guide/modules/ROOT/pages/add-meta-updater-to-vendors-sdk.adoc
Deleted not relevant link from Add meta-updater features to the vendor’s SDK page
Relates-To: OTA-5907
Signed-off-by: Yevtushenko, Vitalii <ext-vitalii.yevtushenko@here.com>
=> Deleted not relevant link 2020.8

docs/ota-client-guide/modules/ROOT/pages/add-meta-updater-to-vendors-sdk.adoc
Deleted not relevant link from Add meta-updater features to the vendor’s SDK page
Relates-To: OTA-5907
=> Deleted not relevant link master

docs/ota-client-guide/modules/ROOT/pages/rollback.adoc, docs/ota-client-guide/modules/ROOT/pages/troubleshooting-bsp-integration.adoc
=> Changed not relevant url 2020.10 

docs/ota-client-guide/modules/ROOT/pages/rollback.adoc, docs/ota-client-guide/modules/ROOT/pages/troubleshooting-bsp-integration.adoc
=> Changed not relevant url 2020.8

docs/ota-client-guide/modules/ROOT/pages/rollback.adoc, docs/ota-client-guide/modules/ROOT/pages/troubleshooting-bsp-integration.adoc
=> Changed not relevant url 2020.9

docs/ota-client-guide/modules/ROOT/pages/rollback.adoc, docs/ota-client-guide/modules/ROOT/pages/troubleshooting-bsp-integration.adoc
=> Changed not relevant url master 

docs/ota-client-guide/modules/ROOT/pages/rollback.adoc, docs/ota-client-guide/modules/ROOT/pages/troubleshooting-bsp-integration.adoc
=> Changed not relevant url 2020.10-docs

docs/ota-client-guide/modules/ROOT/pages/rollback.adoc, docs/ota-client-guide/modules/ROOT/pages/troubleshooting-bsp-integration.adoc
=> Changed not relevant url master

docs/ota-client-guide/modules/ROOT/pages/rollback.adoc, docs/ota-client-guide/modules/ROOT/pages/troubleshooting-bsp-integration.adoc
=> Changed not relevant url 2020.9-docs

docs/ota-client-guide/modules/ROOT/pages/rollback.adoc, docs/ota-client-guide/modules/ROOT/pages/troubleshooting-bsp-integration.adoc
=> Changed not relevant url 2020.8-docs

docs/ota-client-guide/modules/ROOT/pages/add-remove-targets-key.adoc
Signed-off-by: Oleksii Hubrii <ext-oleksii.hubrii@here.com>
=> OTA-5352 add page about how to add/remove key, set threshold

docs/ota-client-guide/modules/ROOT/pages/upload-large-binary.adoc
Signed-off-by: Oleksii Hubrii <ext-oleksii.hubrii@here.com>
=> OTA-6069 document targets.json size limit

docs/ota-client-guide/modules/ROOT/pages/garage-sign-reference.adoc, docs/ota-client-guide/modules/ROOT/pages/upload-large-binary.adoc
Signed-off-by: Oleksii Hubrii <ext-oleksii.hubrii@here.com>
=> OTA-5642 update targets upload and add-uploaded options

docs/ota-client-guide/modules/ROOT/pages/ostree-and-treehub.adoc, docs/ota-client-guide/modules/ROOT/pages/workflow-overview.adoc
Changed not relevant libOstree link.
Relates-To: OTA-6244
=>  Changed not relevant url 2020.9-docs

.github/workflows/ci.yml, scripts/test.sh
Added exception for folder /home/runner/work/aktualizr/aktualizr
Relates-To: OTA-6256
=> Fixed coverage and static checks jobs
