advancedtelematic/aktualizr

CMakeLists.txt

`compile_commands.json` is used by [rtags](https://github.com/Andersbakken/rtags) for code indexing.
Also removes superfluous comments for readability but if there is a style guide that requires them they can be kept.

Generate compile_commands.json

---

CMakeLists.txt

The following change allows to switch from Debug
to Release mode building the application through
-DCMAKE_BUILD_TYPE. The default mode remains
Debug.

CMakeLists.txt: Build Debug by default

---

CMakeLists.txt
src/CMakeLists.txt

Add variable STAGING_DIR_TARGET to set correct
paths to header files when building SOTA Client
with CommonAPI and DBus support in GENIVI
Development Platform through Yocto/OE's bitbake.

CMakeLists.txt: Support building through bitbake

---

.travis.yml
CMakeLists.txt
src/CMakeLists.txt
src/dbusgateway/dbusgateway.cc
src/dbusgateway/dbusgateway.h
src/gatewaymanager.cc
src/main.cc
tests/CMakeLists.txt
tests/fake_dbus_tools/swm.py
tests/session.conf
third_party/rvi_lib/CMakeLists.txt
third_party/rvi_lib/libjwt/CMakeLists.txt

This includes several changes to support building in Yocto
- Both RVI and SWM support are now behind a single BUILD_GENIVI flag
- All third_party dependencies are build with cmake
- A new flag disables building tests, to avoid a dependency on gtest/gmock

Refactor CMakeLists to support Yocto build

---

tests/httpclient_test.cc
tests/socketgateway_test.cc

Without this, a release build fails with warnings like:
error: ignoring return value of ‘int system(const char*)’

Explicitly check the results of system() calls

---

src/CMakeLists.txt

The GENIVI Yocto build gets a link error without this

Add boost chrono package

---

third_party/rvi_lib/src/rvi.c

This PR, setups maximum buffer size for default configuration of rvi_sota_server https://github.com/GENIVI/rvi_sota_server/blob/master/core/src/main/resources/application.conf 
64K for chunk and 2000 bytes for rest of message.

Workaround for bug with big chunks

---

third_party/jsoncpp/jsoncpp.cpp

This pull request removes single new line from generated string with FastWriter writer of JsonCpp parser.
By default, FastWriter writes json without any whitespaces(except end of the string), keys are sorted,  list items preserved with original order. 
Also I have tried Ukrainian symbols, and it sorts regarding to the Ukrainian alphabet.
And I have not  tested Double values. Do we will use them?

Removed new line at the and of generated string.

---

src/CMakeLists.txt
tests/CMakeLists.txt
tests/build_with_options
third_party/rvi_lib/libjwt/CMakeLists.txt

Change libjwt to use the modern method to find OpenSSL, and fix a build issue with -DBUILD_GENIVI=OFF.
This also adds a set of tests to build aktualizr with various configuration options.

Fix SSL linking issue when BUILD_GENIVI disabled

---

.dockerignore
.travis.yml
Dockerfile
README.md
codecov.yml
coverage.sh

This moves most of the logic for the code coverage build into coverage.sh, and
fixes up the Docker instructions in the README to work.

Tidy up CI docker build

---

src/main.cc

Gracefully terminate the applicaiton if RVI
support is enabled but RVI configurations are
missing.

main.cc: Handle missing RVI configurations

---

CMakeLists.txt

In-tree builds cause subtle errors with the test process because the tests
perform builds to check compilation succeeds with the different compile-time
options enabled.

Detect and refuse to build in-tree

---

src/config.cc
src/config.h
src/httpclient.h
src/ostree.cc
src/ostree.h
src/sotauptaneclient.cc
src/types.cc
src/types.h

The 'make qa' command was used to reformat, using clang-format-3.8

Reformat using clang-format

---

src/sotarviclient.cc

RVI_ERR_JSON_PART isn't actually an error: it means that we should call
rviProcessInput again.

Remove 5s sleep on partial messages

---

.gitignore

The Clion IDE uses cmake-build-debug as the default build directory. Replace a
wildcard match (which caught the real directory cmake-modules) with a specific
path in .gitignore.

Stop .gitignore skipping cmake-modules

---

src/ostree.cc
src/ostree.h
src/uptane/uptanerepository.cc
tests/uptane_test.cc

Normally one will need to set both ostree.sysroot and ostree.os when updating a directory, because in this case there will be no "currently booted" deployment.

Let OSTree sysroot be changed in config

---

src/ostree.cc

With this change end-to-end seems almost working.
The only problem remaining is that the garage isn't notified that our package was installed. I'll try to figure out why that can be the case tomorrow.

Convert refhash to the lowercase when creating OSTree package

---

src/config.cc
src/config.h
src/httpclient.cc
src/main.cc
src/uptane/tufrepository.cc
src/uptane/uptanerepository.cc
tests/config_test.cc
tests/uptane_test.cc

Add primary_ecu_hardware_id option instead of device.uuid
Construct default urls if repo,direcor, or ostree urls are empty

Overwrite server options and primary_ecu_serial from cmdline

---

src/config.cc
src/config.h

Since config.h is included in lots of places, reducing the number of files it
includes should reduce the number of large rebuilds.

Push utils.h header into the config.cc

---

src/logger.h

Most people would expect that the 'warning' log level is more serious than the
'info' log level.
Fixes: PRO-3290

Fix ordering of warning and info log levels

---

src/config.cc
src/config.h
src/uptane/uptanerepository.cc

Using dynamically generated pretty name for registering without storing it anywhere is probably not the right way to do the registration. This PR breaks picking a new name if the old one is busy, but it looks like a lesser evil for now.

Add uptane.device_id option

---

Dockerfile.deb-stable
Dockerfile.deb-unstable
src/sotauptaneclient.cc

Our CI builds are with Travis, so using an EU mirror should help the build
performance.  At the moment the default Debian mirror is throwing 500 errors
during the CI run.

Use Debian mirrors from Germany

---

third_party/rvi_lib/libjwt/CMakeLists.txt

If libjwt finds the 'check' binary then the build fails at cmake time.  Since
we don't use this, remove it.

Remove libjwt test code

---

Dockerfile.deb-stable

The Travis build is often getting 500 errors from the default Debian mirror
during the docker build.  Switch to using the German debian mirror instead.

Use German Debian mirror to try and avoid 500 error

---

.travis.yml

These images are build using an internal CI system at ATS, and pushed to
Dockerhub.  They are only used as a cache to speed up the build process, and
the correctness of the build does not depend on them being up-to-date.

Fetch pre-built Docker image

---

.travis.yml

Travis will still build PRs automatically, but we won't have a duplicate build
for both the branch and the PR.

Only build the master branch in CI by default

---

CMakeLists.txt
Dockerfile.deb-stable
README.md
scripts/check-formatting.sh
scripts/test.sh
src/CMakeLists.txt
tests/CMakeLists.txt

Solved by running a new make target (check-format) in test.sh, which fails if clang-format produces any output.

Bugfix/pro 3562/ci check format

---

CMakeLists.txt
src/commands.cc
src/commands.h
src/config.cc
src/config.h
src/events.cc
src/events.h
src/eventsinterpreter.cc
src/ostree.cc
src/ostree.h
src/sotarviclient.cc
src/sotauptaneclient.cc
src/sotauptaneclient.h
src/uptane/tuf.cc
src/uptane/tuf.h
src/uptane/tufrepository.cc
src/uptane/tufrepository.h
src/uptane/uptanerepository.cc
src/uptane/uptanerepository.h
tests/config_test.cc
tests/config_tests.toml
tests/config_tests_prov.toml
tests/config_tests_prov_bad.toml
tests/events_test.cc
tests/missing_ostree_repo.toml
tests/rvisotaclient_test.cc
tests/uptane_test.cc
tests/uptane_vector_tests.cc

Moves part of application logic from Uptane::Repository.
It is the beginning of a relatively big refactoring process. Final goals:
* Make Uptane::Repository a thin layer abstracting procedures related to downloading/verifying/pushing UPTANE metadata. All the installation should occur in application-related modules (mostly SotaUptaneClient).
* Partition Config so that each module uses only its own chunk.
* Make initialization procedure traceable, gather scattered initialization-related code from config.cc and uptane/uptanerepository.cc to a single class/function.
* Replace (almost) all interaction with filesystem with transactional writes to a DB (most likely sqlite3).
This PR just moves OSTree installation to SotaUptaneClient and makes Config slightly better partitioned.

Improve module isolation

---

src/main.cc
tests/CMakeLists.txt

Show user friendly error message and terminate the
application if the specified configuration file
does not exist.

main.cc: Exit if configuration file doesn't exist

---

src/config.h
src/crypto.cc
src/uptane/uptanerepository.cc
src/uptane/uptanerepository.h
tests/CMakeLists.txt
tests/config_test.cc
tests/config_tests.toml
tests/fake_ostree.cc
tests/run_vector_tests.sh
tests/uptane_ci_test.cc
tests/uptane_test.cc
tests/uptane_vector_tests.cc

To run tests  You need to run cmake with `SOTA_PACKED_CREDENTIALS="path_to_file.zip"` then run tests as usual  
Big coverage decrease is because we don't run real ostree class now. May be we need to add new tests to ostree tests, but this will require download ostree repo.

Ci provision

---

src/ostree.cc

This resulted in unbootable device when building AGL for RPi. And indefinitely growth of kernel command line is not what we'd like to see anyway.

Use kernel arguments from the bootconfig, not the whole /proc/cmdline

---

src/aktualizr.cc
src/aktualizr.h
src/httpclient.cc
src/httpclient.h
src/socketgateway.cc
src/socketgateway.h
tests/CMakeLists.txt
tests/aktualizr.supp
tests/dbusgateway_test.cc
tests/leak_test.cc
tests/run-valgrind.in

This series of changes fixes several memory leaks that were discovered by the final change, which runs most of the tests under valgrind.
The biggest change is add_aktualizr_test, which massively reduces the copy/paste required to introduce new tests.

Tidy test creation

---

src/CMakeLists.txt
src/config.cc
src/config.h
src/crypto.cc
src/crypto.h
src/fsstorage.cc
src/fsstorage.h
src/invstorage.h
src/sotauptaneclient.cc
src/uptane/initialize.cc
src/uptane/secondary.cc
src/uptane/secondary.h
src/uptane/testbusprimary.cc
src/uptane/testbusprimary.h
src/uptane/uptanerepository.cc
src/uptane/uptanerepository.h
src/utils.cc
src/utils.h
tests/CMakeLists.txt
tests/config_test.cc
tests/config_tests_device_id.toml
tests/crypto_test.cc
tests/fsstorage_test.cc
tests/uptane_test.cc
tests/utils_test.cc

Secondaries have become even a bit more messy, but they need a major refactoring. That's probably the next thing we should do.
Changes:
- deviceRegister() and ecuRegister() are merged into a single method called initialize()
- serial number and device ID generation (for both primaries and secondaries) is now a part of initialization
- Added clearXXX() functions to the storage to support repeated initialization.
- The only Crypto function still working with files is parseP12. It can be changed later for consistency (or when we decide to store bootstrap credentials in some database as well), but no urgent need yet.

A linear restartable initialization process

---

README.md

Prefer clang-format-3.8. google-mock is not necessary since it is
included as part of the repo.

Update aktualizr dependency list in readme.

---

src/sotauptaneclient.cc
src/sotauptaneclient.h
src/uptane/uptanerepository.h

This is a cleaner/simpler/better version of refactor/getPrimaryEcuVersion that doesn't change the ostree boundaries but still works for Vladimir's code.
Also, one step closer to removing 'friend class ::SotaUptaneClient' in uptanerepository.h.

Create getPrimaryEcuSerial to avoid accessing private member.

---

tests/httpfake.h
tests/uptane_test.cc
tests/uptane_vector_tests.cc

This doesn't remove all /tmp usage, just what I could find and fix in a few minutes' time.

Get rid of some /tmp files in tests.

---

tests/config_test.cc
tests/uptane_test.cc

Moved a couple out of uptane_test into config_test since they didn't
actually require uptane.

Label TST-184, TST-185, TST-186. Create TST-187.

---

src/uptane/initialize.cc
src/uptane/uptanerepository.h
tests/uptane_test.cc

As @christianhuggerATS pointed out, it's a pretty useless piece of code, we don't use device_id in the aktualizr. It might be convenient to have device_id accessible during the debugging though. If it needs to be merged is questionable.

Extract device_id from the certificate

---

src/ostree.cc
src/ostree.h
src/sotauptaneclient.cc
src/sotauptaneclient.h
tests/fake_ostree.cc
tests/ostree_test.cc

This PR _might_ fix [the problem with garbage package names](https://advancedtelematic.atlassian.net/browse/PRO-3825). I can't say if it really solves it because login to CI garage is currently broken, but at least it doesn't break existing functionality and makes code slightly cleaner: crashing with an exception on wrong Uptane metadata was not a good idea (yes, it was my code).

Return error to director on malformed refname

---

src/uptane/initialize.cc

Fixing a bug caught by @rdanitz

Add 1 to device_id length to accommodate trailing null.

---

tests/utils_test.cc

This is really helpful if switching between running tests as root and
non-root. Otherwise, root will leave a directory that non-root cannot
use.

Remove test directory after use.

---

src/cert_provider/main.cc

Not sure why these throw warnings in bitbake builds but not in anything
else. (What else is -Werror -Wall somehow overlooking!?)

Check return values of system calls.

---

.travis.yml
CMakeLists.txt
Dockerfile.gcc4
scripts/test.sh
src/crypto.h
src/sota_tools/authenticate.cc
src/sota_tools/ostree_ref.cc
src/sota_tools/ostree_ref.h
src/sotauptaneclient.cc
src/uptane/tuf.cc

Causes for incompatibilities
1. std::stringstream is not moveable in gcc v4.x
2. Enums are not namespaces (I've also encountered this error on newer versions of GCC).

Fixes to make sota-tools compatible with gcc v4.x (requirement from AGL/jsmoeller) and the respective test

---

src/sotauptaneclient.cc

A minor bug that currently breaks e2e with pkcs11

Don't prepend '/' to pkcs11 URI

---

src/httpclient.h
src/sota_tools/oauth2.cc

Of course as a variadic function it won't tell you anything, it will just make your code segfault in random places.

curl_easy_getinfo(CURLINFO_RESPONSE_CODE, ...) expexts long argument,  fix variable types accordingly

---

src/sota_tools/authenticate.cc

It's the name that is actually used in credentials.zip

Rename repo.url -> tufrepo.url

---

src/fsstorage.cc
tests/uptane_test.cc

'is_registered' is meant to indicate that ECUs are registered on the
backend, so no (other) local file can indicate the same. Current
behavior breaks certain scenarios where all these files are already
present at the time where aktualizr is called first time and also
decreases initialization robustness against interruptions. This commit
is basically reverting 4a9fb2b1b5d5d067b1bcd4675ce79433cd193039, so
migration from very old versions of aktualizr might be broken.

Don't set is_registered if the device really isn't

---

CMakeLists.txt

Build executable aktuakizr_info only if BUILD_OSTREE
is enabled. Otherwise building of aktuakizr_info
will fail due to  error: "‘class FSStorage’ has
no member named ‘loadMetadata’".

MakeLists.txt: Build aktuakizr_info if -DBUILD_OSTREE=ON

---

src/external_secondaries/validate_secondary_interface_test.cc

We're still stuck in C++03 so we must rely on boost for many things. We
still need to look into why we didn't catch this problem earlier.

Immediate fix for teamcity build failure.

---

CMakeLists.txt
src/external_secondaries/CMakeLists.txt
src/external_secondaries/validate_secondary_interface_test.cc
src/sota_tools/CMakeLists.txt
src/sota_tools/Dockerfile

* Do not tolerate GNU or other extensions.
* Build sota_tools with C++11.
* Revert 8aee6ac8e9dbef2e2dd290f4e74c2872c502177e and instead build aktualizr-validate-secondary-interface with C++11.
* Do not link with boost regex since we don't use it.

Enforce C++98/03 where it matters.

---

src/sotauptaneclient.cc
src/sotauptaneclient.h
src/uptane/managedsecondary.cc
src/uptane/managedsecondary.h
src/uptane/secondaryinterface.h
src/uptane/uptanerepository.cc
src/uptane/uptanerepository.h
tests/uptane_ci_test.cc

The client now appends operation_result to every manifest, backend's reaction should be tested. If it's OK with it, the second call to putManifest() can be removed.

Move updateSecondaries function to SotaUptaneClient

---

src/ostree.cc
src/ostree.h
src/sotauptaneclient.cc
tests/fake_ostree.cc

Maintaining consistency of branch names on remote server and on the device is an error-prone process and the branch name is not really required.

Do not use branch name when pulling OSTree commits

---

src/sota_tools/CMakeLists.txt
src/sota_tools/Dockerfile.debian.stable

This PR fixes two issues.
1) garage-deploy.deb first time creates without content from garage-sign.gz
2) It fixes PRO-4473

Fix garage-sign deb and added to docker tests

---

src/config.cc
src/config.h
src/uptane/legacysecondary.cc

Just in case someone ever included it.
This is also just a bit of a refactor to clean up that section of the code.

Tolerate (ignore) whitespace in api-version output.

---

src/aktualizr.h
src/config.cc
src/dbusgateway/dbusgateway.h
src/dbusgateway/swlm.h
src/eventsinterpreter.h
src/external_secondaries/example_interface.cc
src/fsstorage.cc
src/fsstorage.h
src/socketgateway.cc
src/socketgateway.h
src/sotarviclient.h
src/sotauptaneclient.cc
src/sotauptaneclient.h
src/sqlstorage.h
src/uptane/initialize.cc
src/uptane/secondaryinterface.h
src/uptane/tufrepository.h
src/uptane/uptanerepository.h

Also make all configs const references.
Currently if we detect variations in the list of secondary (or primary) serials, it just throws error messages.

Bugfix/pro 4531/persistent legacies

---

config/sota_implicit_prov.toml
src/implicit_writer/main.cc

Required to support _real_ implicit provisioning

Do not try to unpack boostrap credentials when no-root is specified

---

src/sota_tools/CMakeLists.txt

Supports "no_auth" in treehub.json

Bump gargage-sign version

---

CMakeLists.txt
src/external_secondaries/CMakeLists.txt

It's annoying to require initializing a bunch of submodules just to get CMake to run.

Add switch to control iso-tp build.

---

src/aktualizr.cc
src/sotauptaneclient.cc
src/sotauptaneclient.h
src/uptane/uptanerepository.cc
src/uptane/uptanerepository.h
tests/uptane_ci_test.cc
tests/uptane_key_test.cc
tests/uptane_serial_test.cc
tests/uptane_test.cc

SotaUptaneClient now requires both Storage and HttpClient as members, but at least they are just references and Storage is even const.
This isn't necessarily the best solution, but it is better than using friend. I'm open to further discussion on where to go from here.

Remove the dreaded "friend class ::SotaUptaneClient".

---

partial/machine/kea128/app/isotp_dispatch.c

The timeout is quite arbitrary, we need to read the standard more carefully to figure out what it should be.
Host side (test-isotp-interface) should be made more robust as well.

Add timeout for sending

---

tests/aktualizr.supp

These two classes of problem broke a large part of the valgrind checks on my machine.
I don't really know if these rules are too broad or too specific, but probably one of the twos.
(error samples in the commit messages)

Suppress some valgrind errors

---

src/dbusgateway/dbusgateway.cc
src/gatewaymanager.cc
src/invstorage.cc
tests/dbusgateway_test.cc
tests/swm_test.cc
tests/uptane_ci_test.cc
tests/uptane_implicit_test.cc
tests/uptane_key_test.cc
tests/uptane_network_test.cc
tests/uptane_serial_test.cc
tests/uptane_test.cc
tests/uptane_vector_tests.cc

Arguably nicer than manual wrapping of a `new ...`. Also, only does one
allocation for the object and the counter altogether.
Available since boost versions from 2014 and also part of the C++11
standard

Make use of boost::make_shared helper

---

README.adoc
src/sota_tools/deploy.cc
src/sota_tools/deploy.h
src/sota_tools/ostree_object.cc
src/sota_tools/request_pool.cc
src/sota_tools/request_pool.h
tests/CMakeLists.txt
tests/sota_tools/test-auth-plus-failure
tests/sota_tools/test-auth-plus-happy
tests/sota_tools/test-bad-option
tests/sota_tools/test-bare-mode-repo
tests/sota_tools/test-cacert-not-found
tests/sota_tools/test-cacert-used
tests/sota_tools/test-dry-run
tests/sota_tools/test-invalid-credentials
tests/sota_tools/test-invalid-repo
tests/sota_tools/test-missing-credentials
tests/sota_tools/test-missing-ref
tests/sota_tools/test-verbose-logging
tests/uptane_ci_test.cc
tests/uptane_test.cc

Note that the garage-push test-dry-run still succeeds at the moment even if the fetch fails. This is because of how the return code is calculated. We might consider changing that. Either way, the -n/--dry-run option is now much more useful.

Test/pro 4648/sota tools credentials

---

src/CMakeLists.txt
src/crypto.cc
src/crypto.h
src/httpclient.cc
src/ostree.h
src/p11engine.cc
src/p11engine.h
src/sotauptaneclient.cc
src/types.cc
src/types.h
src/uptane/cryptokey.cc
src/uptane/cryptokey.h
src/uptane/initialize.cc
src/uptane/managedsecondary.cc
src/uptane/uptanerepository.cc
src/uptane/uptanerepository.h
tests/CMakeLists.txt
tests/crypto_test.cc
tests/ostree_test.cc

I did it in another way that Phil suggested. The reason for this is that we have source flag for each key. So currently I just moved all pkcs11 related code to one class.

move all p11 dependant code to one place

---

Dockerfile.garage-tools

- add Java to enable garage-sign
- remove entrypoint so that any of the tools can be called the same way

Generalize garage-push docker image to garage tools

---

.travis.yml

The way @patriotyk originally implemented passing github tokens looks like the only officially supported one. Travis docs claim that the "secure" key cannot be used by anyone outside advancedtelematic.

Pass secret key as (encrypted) plaintext.

---

src/config.cc

Overlooked when axing the rest of rvi. Only comes up for implicit/hsm provisioning.

Remove writing rvi to config file.

---

src/utils.cc
tests/utils_test.cc

As mentioned in PRO-4721 and PRO-4722, TemporaryFile and
TemporaryDirectory were somewhat unsafe.
To solve this, we create a global temporary directory root for the
lifetime of the application, with restrictive permissions. The directory
is created in the OS' canonical temporary directory so that aktualizr
can eventually run under a lesser privileged user.

Provide safer temporary files and directories

---

CMakeLists.txt
src/external_secondaries/CMakeLists.txt
src/sota_tools/CMakeLists.txt
tests/CMakeLists.txt

Now is the time to move Aktualizr to C++11.  At the moment the core of the product compiles against C++98, although we require C++11 for some of the support utilities.
C++11 came in gcc around version 4.7, and Debian oldstable is currently at gcc 4.9, so I hope that we should be able to assume C++11 now.

Switch to C++11 by default

---

src/p11engine.cc
src/p11engine.h
src/uptane/cryptokey.cc
src/uptane/cryptokey.h
tests/crypto_test.cc
tests/uptane_crypto_test.cc
tests/uptane_test.cc

The new version drops P11Engine once it has no more users (practically once Uptane::Repository gets out of scope) thus allowing reinitialization in tests. I have a feeling that I'm reimplementing a shared pointer, so if you think it can be done better I'm open to suggestions.

Add P11EngineGuard to count existing P11 users

---

docs/CMakeLists.txt
src/CMakeLists.txt

This is necessary to get the meta-updater build to work correctly. Currently, the latest aktualizr fails.
Also make some installation directories relative so that things install correctly.

Only install docs if it was built.

---

scripts/test.sh

We had a bug where 'make install' was failing if the docs had not been built.
Add a test to ensure that this is caught during CI in the future

Test 'make install'

---

src/sqlstorage.cc
src/sqlstorage.h
tests/CMakeLists.txt
tests/sqlstorage_test.cc

Now only run as a separate test and not at every db init.
Note that `getTableSchemaFromDb` is now available as a public method to
make this work.
Following recommendations from PRO-4725

Move dbCheck out of main SQLStorage

---

src/external_secondaries/example_flasher.cc
src/httpclient.cc
tests/utils_test.cc

Previously it assumed if /var/sota existed it was good to use. Now it
actually checks for read-/writability before moving forward. This is
obviously still liable to fail if the filesystem changes before we
actually use it, but this is just an example that is also used for
testing.

Improve resilience of example_flasher logic.

---

src/crypto.cc

This reverts commit 66e846982494301ead72e6e940c0ed496fecb340.
See PRO-4851 for more discussion. 4096 bit RSA keys are about 4x slower than 2048, and this gets _really slow_ when the tests are run under valgrind:
time valgrind t_uptane
4096 => 4m33,349s
2048 => 0m28,607s
1024 => 0m12,138s

Revert "Generate 4096 bits RSA keys"

---

scripts/build-ubuntu.sh
src/sota_tools/CMakeLists.txt

This cleans up the dependencies in the .deb package as well.

Remove libostree and libdpkg dependencies for garage-deploy

---

README.adoc
config/systemd/aktualizr-ubuntu.service
docs/deb-package-install.adoc

The debian package blows away any changes to the systemd service
file, so we want to make it possible to add command line options
for secondaries or other custom configs.

Use an env file in .deb package systemd service file

---

src/sqlstorage.cc
tests/storage_common_test.cc

Theoretically, two targets with the same file names should be identical but for now, just write the file content again.

Allow double writes of targets in sql storage

---

src/deb.cc
tests/packagemanager_deb_tests.cc
tests/test_data/fake_dpkg/systemd-run

This is a partial fix that makes self-update on Aktualizr work, although we
should build a proper solution soon.  It does at least work end-to-end, and
unblocks the remaining testing.
Change-Id: I03d8c1dd461fd21c244145f641d808e8bbdfd450

Partial fix for PRO-4872

---

CMakeLists.txt

This is is normally autodetected based on the current cmake generator, and
overriding it causes the package build to fail when using ninja rather than
make. The docs say that 'few users will want to change this setting':
https://cmake.org/cmake/help/v3.0/module/CPack.html
Change-Id: Id66e01f00ca2f57f052d9d439d1087b226adeddf

Don't force CPACK_CMAKE_GENERATOR to make

---

src/logging.cc

Implement @patriotyk 's suggestion for a better way to flush messages from PR #582

Add a better fix to flush the log messages

---

config/sota_implicit_prov_ca.toml

FSStorage->SQLStorage migration logic breaks imports when `[import]` paths are the same as that of a (hardcoded) `[fsstorage]`.
Can't imagine a good fix for that, I think they should just always be set to be different.

Change paths of imported data to not intersect with fsstorage data

---

src/sota_tools/treehub_server.cc

The tufrepo.url file in my credentials.zip somehow had a trailing \n
making my bitbake's call to garage-check very difficult to debug.

garage-check: Handle \n's in tufrepo.url

---

src/config.cc
src/config.h
src/crypto.cc
src/crypto.h
src/invstorage.h
src/keymanager.cc
src/sotauptaneclient.cc
src/types.h
src/uptane/initialize.cc
src/uptane/managedsecondary.cc
src/uptane/secondaryconfig.h
src/uptane/secondaryinterface.h
src/uptane/uptanerepository.cc
src/uptane/uptanerepository.h
tests/config_tests_device_id.toml
tests/config_tests_prov.toml
tests/crypto_test.cc
tests/keymanager_test.cc

Running all uptane related tests with command `ctest -R test_uptane` gives me the following results:
```
RSA2048 : 120 secs
ED255519: 60 secs
```
So looks like ED25519 is much faster then RSA2048. 
But server doesnt support it, so we can not use it by default yet.

Add support and switch between of rsa2048, rsa4096 and ed25519 keys

---

src/packagemanagerfactory.h
src/uptane/tuf.h

Was considering two targets with a common hash as equals
I'm not entirely sure this was a bug. I'll push tests for this if you can confirm this is what it should do.

Fix Uptane::Target comparison operator

---

src/cert_provider/main.cc

If a config option is already an absolute path, do not prefix it with another path.
Also, remove a redunant mkdir.

Fix bug with redundant path prefixing.

---

src/ostree.cc
src/ostree.h

Should fix the 'Couldn't load sysroot bug'. I really hope that no user was affected.
Basically there was a leak of OstreeRepo objects that caused the process to run out of file descriptors after 15-30 minutes. I'm not sure if we can test for that.
This particular error would be not so fatal if aktualizr (SotaUptaneClient to be precise) just crashed upon receiving an exception, but if it is always the best thing to do is questionable.

Ensure that OstreeRepo is destroyed after use

---

src/sota_tools/treehub_server.cc
src/sota_tools/treehub_server.h

It turns out this is not actually necessary, but since it cleans things up a bit, I figure it's still an improvement worth holding on to.

Support noauth in garage-check.

---

src/fsstorage.cc
src/fsstorage.h
src/invstorage.cc
src/invstorage.h
src/sql_utils.h
src/sqlstorage.cc
src/sqlstorage.h
src/utils.cc
tests/CMakeLists.txt
tests/storage_atomic.cc
tests/storage_common_test.cc

Try to avoid the unsafe pattern:
```
remove(file)
<-- bad things can happen here
write(file, newContent)
```
Both in SQL db and on the file system.
Note that problems can still occur if (for example) a public/private key pair is updated partially. This is difficult to solve on the file system but it could be desirable to have a safe `storePair()` in the SQL case and removing `storePublic()` and `storePrivate()`

Fix some atomicity issues

---

.gitignore
CMakeLists.txt
Dockerfile
Dockerfile.deb-stable
Dockerfile.deb-unstable
Dockerfile.noostree
Dockerfile.nop11
cmake-modules/CodeCoverage.cmake
cmake-modules/FindAsn1c.cmake
codecov.yml
scripts/coverage.sh
scripts/test.sh
src/CMakeLists.txt
src/asn1-cer.cc
src/asn1-cer.h
src/asn1-cerstream.cc
src/asn1-cerstream.h
src/config.cc
src/config.h
tests/CMakeLists.txt
tests/asn1-reference/common.asn1
tests/asn1-reference/config/cryptosource.asn1
tests/asn1-reference/config/tlsconfig.asn1
tests/asn1_test.cc
tests/run_vector_tests.sh

Largely based on @lbonn's https://github.com/advancedtelematic/aktualizr/pull/509
Somewhat C-style, but it's hard to make binary serialization/deserialization differently. Testing against asn1cc requires quite a bit of boilerplate, because asn1cc only encodes/decodes to its own generated structures, not to our application level ones.
Right now only implemented for TlsConfig and only in tests, if we decide to give it a go, the rest can be implemented in a similar manner.

Add support for ASN.1 CER serialization/deserialization of config

---

config/aktualizr_secondary/config.toml.example
src/CMakeLists.txt
src/aktualizr_secondary/CMakeLists.txt
src/aktualizr_secondary/aktualizr_secondary_config.cc
src/aktualizr_secondary/aktualizr_secondary_config.h
src/aktualizr_secondary/main.cc
src/cert_provider/main.cc
src/config.cc
src/config.h
src/config_utils.h
src/crypto.h
src/external_secondaries/ecuinterface.h
src/external_secondaries/example_flasher.h
src/fsstorage.h
src/gateway.h
src/httpinterface.h
src/invstorage.h
src/main.cc
src/packagemanagerinterface.h
src/sqlstorage.h
src/utils.cc
src/utils.h
tests/CMakeLists.txt
tests/aktualizr_secondary/config_test.cc
tests/aktualizr_secondary/config_tests.toml
tests/config_test.cc
tests/httpclient_test.cc

Notes:
- the name of the executable was changed back to `aktualizr-follower`
- some utility functions were stripped back from `config.h` and put in `config_utils.h`
- config structures use C++11 member initializers

Aktualizr secondary config

---

CMakeLists.txt
src/CMakeLists.txt
src/asn1-cer.h
src/asn1-cerstream.h
src/config_utils.h
src/external_secondaries/CMakeLists.txt
src/opcuabridge/utility.h
src/socket_activation/CMakeLists.txt
src/socket_activation/socket_activation_dummy.cc
src/sota_tools/CMakeLists.txt
src/sql_utils.h

It's currently very easy to forget to add new source and headers to the static checks. It causes unclean files to be committed and unnecessary review back and forth.
Example: https://github.com/advancedtelematic/aktualizr/pull/620#issuecomment-371456780
CMake now tries to match the list of source files it can find with what was added to the checks.

Enforce source checks

---

src/aktualizr_secondary/aktualizr_secondary.cc
src/aktualizr_secondary/aktualizr_secondary.h
src/config.h
src/types.cc
src/types.h
src/uptane/initialize.cc
src/uptane/managedsecondary.h
src/uptane/secondaryinterface.h
tests/CMakeLists.txt
tests/aktualizr_secondary/update_test.cc

A dummy test also added. It's disabled now, when aktualizr_secondary is implemented it should be enabled and passing.
@riqkum Please use these callbacks as an interface on the secondary side. Approximate data transfer scheme could look like
```
SecondaryInterface.getManifest() <-> OPC-UA on primary <-> || <-> OPC-UA on secondary <-> AktualizrSecondary.getManifestResp()
```
(the same for other calls)

Add dummy implementation callbacks for aktualizr_secondary

---

scripts/test.sh
src/external_secondaries/CMakeLists.txt
src/external_secondaries/test_isotp_interface.cc

Also enable BUILD_ISOTP on CI builds so that we can catch problems faster.
(it is enabled in the yocto recipe but currently not on any CI configuration)

Fix linking issue with BUILD_ISOTP=ON

---

src/sota_tools/authenticate.cc
src/sota_tools/treehub_server.cc
src/sota_tools/treehub_server.h

The username and password methods used by the authenticate function
don't tell the TreeHubServer to update its method_. This changes makes
this a single API to work more like the SetCerts and SetToken methods
work.

treehub: Fix logic for HTTP basic auth

---

README.adoc
src/sota_tools/CMakeLists.txt

I'd still like to work on the automatic garage-sign version management, but in the meantime, I'm hoping this will fix some of the garage-sign problems we've seen lately.

Latest garage-sign (134) and add libsystemd-dev to README.

---

.clang-tidy
CMakeLists.txt
src/aktualizr_secondary/opcuaserver_secondary_delegate.h
src/external_secondaries/example_flasher.h
src/external_secondaries/test_isotp_interface.h
src/fsstorage.cc
src/opcuabridge/filedata.h
src/opcuabridge/metadatafiles.h
src/sota_tools/accumulator.h
src/sota_tools/ostree_dir_repo.h
src/sota_tools/ostree_hash.h
src/sota_tools/ostree_http_repo.h
src/sota_tools/ostree_repo.h
src/sotauptaneclient.h
src/sqlstorage.cc
src/uptane/opcuasecondary.cc
src/uptane/opcuasecondary.h
tests/uptane_test.cc

To also work when using a build directory outside the repository
Noticed the problem after #674. There was no problem in the option selection but only with the header controlling which header files to lint.
This is a bit ugly but looks like it now works in both cases.

Fix clang-tidy header filter regex

---

src/sota_tools/CMakeLists.txt

Both tools were installed via the standard install rule but were not
available in the garage-deploy debian package.
Signed-off-by: Ricardo Salveti <ricardo@opensourcefoundries.com>

Add garage-push and garage-check to the garage_deploy component

---

tests/uptane_test.cc

After moving from boost::thread to std::thread we exit from main loop by checking exit flag in every update run. The reason to do that was that std::thread doesn't support interrupting thread from main thread.
This PR speeding up running uptane_test by setting update interval to 1 second.

Decrease interval for runForever main cycle

---

Dockerfile.nop11
tests/aktualizr.supp

This was causing an annoying tendency for our nop11 builds to fail in CI. More information:
https://bugs.launchpad.net/ubuntu/+source/valgrind/+bug/1501545
https://stackoverflow.com/questions/37032339/valgrind-unrecognised-instruction

Pull newer valgrind that understands C++11 instructions.

---

docs/configuration.adoc

I'm sitting here with @OYTIS and we can't figure out what some of the options do. This PR is an attempt to sort out what everything does. @OYTIS says everything has a default, but it's not obvious where those come from. Also, some things are relative paths and some are absolute paths. That's also not obvious. And somethings are misnomers like `ipdiscovery_host` is actually a subject mask, not a host. Anyway. Here's as start. Someone else should push to this branch on top and fill in the rest.

Config documentation

---

src/aktualizr.cc
src/channel.h
src/eventsinterpreter.cc
src/eventsinterpreter.h
src/gatewaymanager.cc
src/gatewaymanager.h
src/socketgateway.cc
src/socketgateway.h
src/sotauptaneclient.cc
src/sotauptaneclient.h
tests/socketgateway_test.cc
tests/uptane_key_test.cc
tests/uptane_test.cc

Accumulation gets especially annoying when debugging aktualizr, but can also slow everything down if network connection is slow/unstable.

Trigger poll event in poll event processor to avoid accumulation of events

---

codecov.yml

Since 434ee8487599ea6f1a44c635e49f99b5f8e3a3ce, no need to rewrite paths

Fix codecov ignore and rewrites

---

tests/utils_test.cc

I checked the source of binary_from_base64 and it validates input characters, so I just added tests to test this functionality.

Add tests to be shure we validate incorrect base64 string

---

tests/sota_tools/test-verbose-logging

Only runs when credentials are enabled.

Fix garage-push test-verbose-logging.

---

CMakeLists.txt

This makes it appear in the GUI, and should help avoid bugs like #741, where the tests are run without the option enabled
Change-Id: Id7b2aecd56a32004f1ed0141c27eabf97d44248e

Add explicit option for SOTA_PACKED_CREDENTIALS

---

CMakeLists.txt
README.adoc
scripts/test.sh
tests/CMakeLists.txt

I've become convinced that it's made redundant by clang-tidy.
Investigation: https://stackoverflow.com/questions/49943781/does-clang-tidy-make-clang-check-redundant/

Don't run clang-check on `make qa` and CI

---

src/aktualizr_info/CMakeLists.txt
src/aktualizr_info/aktualizr_info_config.cc
src/aktualizr_info/aktualizr_info_config.h
src/aktualizr_info/main.cc
src/libaktualizr/config/config.h

This should keep aktualizr-info simpler and prevent some potential
conflicts between aktualizr and aktualizr-info usage of the config.

Create new minimalist AktualizrInfoConfig.

---

src/sota_tools/authenticate.cc

The --cacerts option is being ignored by the HTTP Basic code path in
authenticate.cc.

garage-push: Honor the --cacerts option with HTTP Basic

---

docs/configuration.adoc

I just realized this was never updated. This is a pretty basic explanation; is there a definitive source that we should link to for systemd-style configuration?

Basic explanation of systemd-style config support.

---

docs/hsm-provisioning.adoc

This is getting updated here because it's included in the ATS Garage/OTA Connect docs build. The somewhat ugly ifdef::[] blocks are because github's processor doesn't let you do includes, so we have to check whether the renderer is github's or the one that builds the docsite and avoid includes in the github case.

PRO-5383 Update script references in HSM provisioning doc

---

src/libaktualizr/package_manager/ostreemanager.cc

Fixes https://github.com/advancedtelematic/aktualizr/issues/670
The changes produce output at loglevel INFO like:
ostree-pull: Receiving metadata objects: 3
ostree-pull: Receiving metadata objects: 4
ostree-pull: Receiving metadata objects: 6
ostree-pull: Receiving metadata objects: 9
ostree-pull: Receiving metadata objects: 11
ostree-pull: Receiving objects: 44%
ostree-pull: Receiving objects: 83%
ostree-pull: Receiving objects: 90%
ostree-pull: Receiving objects: 93%
ostree-pull: Receiving objects: 97%
ostree-pull: Writing objects: 1
ostree-pull: 13 metadata, 16 content objects fetched; 44683 KiB transferred in 23 seconds

ostree: Log status updates of pull

---

src/libaktualizr/config/config.cc
src/libaktualizr/config/config_test.cc

Change-Id: I6c3cd33078ac4d83b01c3e5bf08a0d96c9d75ed7

Fix typo that caused ipuptane_port to be ignored

---

src/libaktualizr/uptane/root.cc

After doing a key rotation described here:
https://docs.atsgarage.com/prod/rotating-signing-keys.html
We started seeing the LOG_INFO message. It seemed a bit concerning
to people until we dug into it more. I think this message is probably
more useful as a LOG_DEBUG. Additionally, if we are going to warn
about a key I think we ought to show it.

uptane: Change logging for unknown keys

---

Dockerfile
Dockerfile.deb-stable
Dockerfile.deb-testing
Dockerfile.noostree
Dockerfile.nop11
scripts/get_garage_sign.py

Plain `sorted()` sorts lexicographically

Fix finding the latest garage-sign version

---

CMakeLists.txt
src/aktualizr_secondary/uptane_test.cc
src/libaktualizr/asn1/asn1-cerstream.cc
src/libaktualizr/asn1/asn1-cerstream.h
src/libaktualizr/opcuabridge/common.h
src/libaktualizr/package_manager/ostreemanager_test.cc
src/libaktualizr/primary/initializer.cc
src/libaktualizr/primary/initializer.h
src/libaktualizr/storage/sqlstorage.cc
src/libaktualizr/uptane/managedsecondary.cc
src/libaktualizr/uptane/managedsecondary.h
src/sota_tools/garage_deploy.cc

There used to be a typo, so I fixed it + the warnings. Also, let's enable warnings when compiling with clang since it shares most of its compile options with gcc.

Reenable `-Wshadow`

---

README.adoc
src/libaktualizr/asn1/CMakeLists.txt

It's currently used only for a test, so we don't need to require it in all cases. Example: building with yocto.

Make absence of asn1c non fatal

---

src/external_secondaries/test_isotp_interface.cc
src/libaktualizr/crypto/p11engine.cc
src/libaktualizr/opcuabridge/opcuabridge_ostree_repo_sync_server.cc
src/libaktualizr/uptane/opcuasecondary.cc

sconfig is a member variable of SecondaryInterface, and message was getting
shadowed.

Fix errors on 'make qa' with all options turned on

---

Dockerfile
Dockerfile.deb-stable
Dockerfile.deb-testing
Dockerfile.noostree
Dockerfile.nop11
README.adoc
scripts/get_garage_sign.py

Python dateutil isn't packaged for Yocto, which makes this fail when built in meta-updater

Drop python dateutil

---

src/libaktualizr/http/httpclient.cc

Minor fix that appears to fix a seemingly unimportant problem with reusing the curl object.

Clear field when not used to fix valgrind complaints.

---

src/libaktualizr/package_manager/ostreemanager.cc

`ostree_sysroot_query_deployments` could fail and not update the
pointer. In that case, the loop after that would compare uninitialized
memory with other pointers

Fix a potential comparison with uninitialized pointer

---

src/libaktualizr/config/config.h

We send the IP Uptane discovery packet once, and 2 seconds seems enough to have
aktualizr be started by systemd and respond.  We don't currently retry sending
the discovery packet, so this delay won't help if systemd hasn't started
listening on the UDP port of the secondary yet.

Only wait 2s for discovery responses

---

src/aktualizr_info/aktualizr_info_config.cc
src/aktualizr_info/aktualizr_info_config.h
src/aktualizr_secondary/CMakeLists.txt
src/aktualizr_secondary/aktualizr_secondary_config.cc
src/aktualizr_secondary/aktualizr_secondary_config.h
src/libaktualizr/config/config.cc
src/libaktualizr/config/config.h
src/libaktualizr/utilities/config_utils.h
tests/CMakeLists.txt

Also use it for the Config(vector<path>) constructor, which cert_provider uses. Previously, a nonexistent config would be silently ignored. Now it is as least not silent.
The idea is that if config files/dirs specified directly on the commandline do not exist, you should tell the user, because that probably matters.
This does mean that if you use this in meta-updater, the implicit prov test should fail just like the HSM test. This is intentional. It should fail if it can't find the config file. Currently it is sometimes using an empty config, which mostly works, but is maybe not a good idea.

Move config dir checking to a common function.

---

thirdparty.spdx

Technically this isn't a "real" boost library, it's just a header that
we took from the internet and copied into our code, but still, it
counts.

Add another boost component I'd forgotten about.

---

CMakeLists.txt

Defaults to ON on Linux, OFF on other platforms
@jochenschneider: could you make a quick test on MacOS? (should configure successfully without setting `BUILD_SYSTEMD`)

Fix BUILD_SYSTEMD=on option

---

docs/hsm-provisioning.adoc

Thanks for the catch, @jerrytrieu

Fix: Add missing $ in HSM device gateway registration doc

---

src/aktualizr_repo/repo.cc

SHA-512 are needed for small secondaries.

aktualizr-repo: add sha512 hashes

---

src/aktualizr_secondary/aktualizr_secondary.cc
src/libaktualizr/primary/sotauptaneclient.cc
src/libaktualizr/uptane/fetcher.cc
src/libaktualizr/uptane/tuf.cc
src/libaktualizr/uptane/tuf.h

This replaces Target::format(), and brings the logic about the meaning of that
field inside the Target class itself.

Introduce Target::IsOstree()

---

config/sql/migration/migrate.08.sql
config/sql/schema.sql
src/libaktualizr/storage/fsstorage.cc
src/libaktualizr/storage/invstorage.h
src/libaktualizr/storage/sqlstorage.cc
src/libaktualizr/storage/sqlstorage.h
src/libaktualizr/storage/sqlstorage_test.cc
src/libaktualizr/storage/storage_common_test.cc

More tests (store data twice in tests, mostly) which uncovered two issues
- one small bug in FSStorage
- one use of some sql syntax unsupported on xenial's version
Also:
* generalize transactions when doing SELECT then modify
* uses unique_mark trick for two tables
* simplify `device_info` handling and remove `dbInit()`

SQLite coverage + fixes

---

src/libaktualizr/primary/eventsinterpreter.cc
src/libaktualizr/primary/eventsinterpreter_test.cc

This will send a lot of redundant data every time aktualizr runs with that flag, but that might be reasonable anyway if the data changed since the last run.
This probably isn't a perfect solution, but since there is no specific requirement at present, I'd rather keep it simple while sending the messages that were previously being skipped in manual runs.

SendDeviceData also for --running-mode=check.

---

tests/CMakeLists.txt
tests/build_with_options.sh

They are redundant with the docker env testing we do + they can launch a
large number of workers inside an already parallel build process

Remove 'cmake in cmake' tests

---

src/libaktualizr/storage/sqlstorage.cc

Was causing lot of confusion in the logs.
Sorry, I introduced these for the most part. Basically if `: unknown error` shows up in the logs, it's most likely a false positive message.

Silence a lot of false positive sql errors

---

partial/CMakeLists.txt
src/CMakeLists.txt
src/external_secondaries/CMakeLists.txt
src/external_secondaries/example_flasher.cc
src/external_secondaries/example_flasher.h
src/external_secondaries/validate_secondary_interface_test.cc

Instead of just making them not fail the build (all these warnings are
distracting)

Silence warnings in partial external code

---

docs/hsm-provisioning.adoc

Replaced path "root.crt" with ${device_dir}/root.crt

PRO-5519: fixing reference to root.crt

---

src/libaktualizr/crypto/crypto.cc
src/libaktualizr/primary/commands_test.cc
src/libaktualizr/uptane/uptane_test.cc

Got blessed with an automatic update from gcc 7 to 8 this morning.
../src/libaktualizr/crypto/crypto.cc:150:77: error: type qualifiers ignored on cast result type [-Werror=ignored-qualifiers]
const auto sign_size = static_cast<const unsigned int>(RSA_size(rsa.get()));
And
../src/libaktualizr/uptane/uptane_test.cc:128:37: error: catching polymorphic type ‘class Uptane::IllegalThreshold’ by value [-Werror=catch-value=]
} catch (Uptane::IllegalThreshold ex) {

gcc8 warnings

---

src/libaktualizr/uptane/exceptions.h
src/libaktualizr/uptane/root.cc
src/libaktualizr/uptane/uptane_test.cc

There is one issue in vector tests. The test 'director_targets_zero_threshold' expects 'The role root had an illegal signature threshold.' which is incorrect. The problem is not in the json file because 'director_targets_zero_threshold.json' contains the correct error. So the problem is that `POST /director_targets_zero_threshold/step` returns following result:
```
{
83: 	"director" : 
83: 	{
83: 		"targets" : 
83: 		{
83: 			"file.txt" : 
83: 			{
83: 				"is_success" : true
83: 			}
83: 		},
83: 		"update" : 
83: 		{
83: 			"err" : "IllegalThreshold::Root",
83: 			"err_msg" : "The role root had an illegal signature threshold.",
83: 			"is_success" : false
83: 		}
83: 	},
83: 	"image_repo" : 
83: 	{
83: 		"targets" : 
83: 		{
83: 			"file.txt" : 
83: 			{
83: 				"is_success" : true
83: …
```

Fixed 5 vector tests

---

src/libaktualizr/primary/sotauptaneclient.cc
src/libaktualizr/uptane/uptane_test.cc

There was a missing element that caused this to always return an empty
string. I have extended a couple tests to catch this. This was also the
root of the issue in which aktualizr would continually think it found
new updates even after successfully installing them.

Fix filepath in the manifest.

---

CMakeLists.txt

This small change allows to reuse aktualizr repository as cmake subdirectory from another projects

Make dependancies visible in parent scope

---

src/libaktualizr/http/httpclient.cc

This should fix HSM support
Was forgotten because masked by another issue.
There are similar issue sitting in curl bugs: https://github.com/curl/curl/issues/2485 (this one was fixed). I'll see if the problem we have is still present on upstream and possibly fill a report.
We'll have to keep the workaround for a while though.

Apply curl bug workaround for GET requests

---

docs/aktualizr-repo.adoc
src/aktualizr_repo/run/create_repo.sh
src/aktualizr_repo/run/serve_repo.py

Tested with meta-updater rocko and raspberrypi. Uptane metadata exchange works after minor fixes to cert_provider (following). OSTree not tested yet (would require more flexibility in `aktualizr-repo` utility wrt. adding packages to images repo).

Scripts to use aktualizr-repo as a replacement to the backend

---

src/libaktualizr/uptane/root.cc
src/libaktualizr/uptane/uptane_secondary_test.cc

Unknown signatures are fine as long as there are still enough known
signatures to pass the threshold. To keep tuf-test-vectors happy,
though, we now throw the BadKeyId exception if there is only one
signature and its KeyId is unknown.
We urgently need tests that actually test the case of multiple
signatures, some recognized and some not.

Do not throw BadKeyId on every unknown KeyId.

---

src/libaktualizr/uptane/root.cc

When role thresholds are used, it is required that the multiple signatures come
from different keys. It should not be possible for one role to just sign the
metadata twice.
Previously, the check was on the _value_ of the signature, but this is
meaningless when signatures are non-deterministic or when an attacker can craft
two signatures that serialise differently. The correct check is to compare
keyids: these come from root.json, and attackers can't create new ones at
random.

Fix duplicate signature validation

---

src/libaktualizr/uptane/tuf.cc

Fixes inconsistent metadata error for secondaries. ~~Still doesn't install anything though (hmi mode, secondary added directly with `AddSecondary`).~~ Sorry, forgot the final `FetchMeta`.

Only test for consistency of what is present

---

.travis.yml
Dockerfile
Dockerfile.deb-testing
Dockerfile.noostree
Dockerfile.nop11

It ended up being `/ostree/aktualizr` which doesn't make sense.
Relevant docker documentation extract:
The WORKDIR instruction can be used multiple times in a Dockerfile. If
a relative path is provided, it will be relative to the path of the
previous WORKDIR instruction

Fix docker WORKDIR mixup

---

scripts/test_install_aktualizr_and_update.sh

In the current state of things, aktualizr-info needs one aktualizr run
(or `--allow-migrate`) so that the storage db exists and can be read

Fix `test_install_aktualizr_and_update.sh`

---

src/libaktualizr/package_manager/ostreemanager.cc
src/libaktualizr/package_manager/ostreemanager.h
src/load_tests/treehub.cc

Use templated `using` declarations to avoid defining these one-off
opaque pointer types. Instead, define a proxy to the correctly
specialized `unique_ptr`
Inspired by [this comment](https://github.com/advancedtelematic/aktualizr/pull/913#discussion_r210855383)

Make GObject smart pointers more usable

---

src/libaktualizr/utilities/utils_test.cc

Should fail once every few hundred million times instead of once every
three thousands

Make GenPrettyNameSane more reliable

---

src/libaktualizr/http/httpclient.cc
src/libaktualizr/utilities/utils.h
src/sota_tools/authenticate_test.cc
src/sota_tools/deploy.cc
src/sota_tools/garage_check.cc
src/sota_tools/garage_push.cc
src/sota_tools/oauth2.cc
src/sota_tools/ostree_http_repo.cc
src/sota_tools/ostree_object.cc
src/sota_tools/ostree_object.h
src/sota_tools/ostree_ref.cc
src/sota_tools/rate_controller.cc
src/sota_tools/request_pool.cc
src/sota_tools/treehub_server.cc
tests/sota_tools/test-bare-mode-repo
tests/sota_tools/test-invalid-repo

* Require credentials, no longer silently accept an undocumented default
option. Fix associated tests.
* Remove an unused getenv system call.
* More const-correctness and error checking.
Note that the return code from `curl_easy_setopt` is almost never checked. Is that worth changing?

Minor improvements to garage-push.

---

docs/selectively-triggering-aktualizr.adoc

Adding documentation of "campaign_check" and "campaign_accept" which
needs developer review.
I'm not entirely sure about my explanation for "accept". In the UI, there are some campaigns that the end-user (ie: motorist) has to accept before installing, and some campaigns that are allowed to auto install. Does this "accept" refer to the same thing?
Also, why is the "full" mode not documented anywhere?

Adding documentation of two new campaign related options

---

config/sota_hsm_prov.toml
docs/hsm-provisioning.adoc
src/cert_provider/main.cc

Having a different name than all other cases (`/var/sota/token`) makes life more difficult.
meta-updater and doc changes should also come forward.

Do HSM prov through `/var/sota/import`

---

src/libaktualizr/crypto/crypto_test.cc
src/libaktualizr/crypto/p11engine.cc
src/libaktualizr/crypto/p11engine.h

If a path is provided, try that. If that doesn't work, try the new path
for openssl-1.1. If that doesn't work, try the old default location.
Also add a test.
This is part of the work to get HSM support working on master again. meta-updater PR is at https://github.com/advancedtelematic/meta-updater/pull/391.

Try a few different locations for finding the p11 engine library.

---

src/libaktualizr/campaign/campaign.cc
src/libaktualizr/campaign/campaign.h
src/libaktualizr/campaign/campaign_test.cc
src/libaktualizr/campaign/test/campaigns_sample.json
src/libaktualizr/primary/aktualizr.h
src/libaktualizr/primary/aktualizr_test.cc
src/libaktualizr/primary/sotauptaneclient.cc
src/libaktualizr/utilities/events.cc
src/libaktualizr/utilities/events.h
tests/httpfake.h
tests/test_data/repo/campaigner/campaigns.json

Previously, the api was only usable from the CLI

Send campaigns metadata in CampaignCheckComplete

---

config/sota_hsm_prov.toml
config/sota_implicit_prov.toml
config/sota_implicit_prov_ca.toml
src/cert_provider/main.cc
tests/hsm_prov_test.py
tests/implicit_prov_test.py

- sota_implicit_prov is deprecated
- HSM provisioning should not import certificate and private key, they
belong to HSM, not to storage
- All the imported data should be under /var/sota/import
- Make cert provider respect path to import directory

Changes to provisioning configs for delayed provisioning

---

.gitmodules

Now includes Phil's fix! Using the old repo with a commit outside master was causing issues with bitbake.

Use upstream version of HdrHistogram

---

CMakeLists.txt
cmake-modules/CodeCoverage.cmake
tests/CMakeLists.txt

CMake binary dir, third party code and `tests/` were not ignored anymore
which made our coverage rate look very bad.
* bump CodeCoverage.cmake from https://github.com/bilke/cmake-modules
* fix COVERAGE_LCOV_EXCLUDES to use the new format
(see https://github.com/linux-test-project/lcov/commit/e32aab1b4c85503a6592a91326c4b362613e1d66)

Fix coverage with recent lcov versions (>=1.13)

---

docker/Dockerfile.ubuntu.xenial

It is now needed for the full run of the test suite (test_uptane)

Add lshw to xenial Dockerfile

---

src/libaktualizr/uptane/secondaryconfig.h

Eventually I'd like to get rid of secondary_type, but this hack will allow us safely inherit SecondaryConfig right now.

Don't throw on unknown secondary types

---

src/sota_tools/CMakeLists.txt
src/sota_tools/authenticate_test.cc
src/sota_tools/deploy_test.cc
src/sota_tools/ostree_http_repo_test.cc
src/sota_tools/ostree_object.cc
src/sota_tools/ostree_object.h
src/sota_tools/ostree_object_test.cc
tests/fake_http_server/ssl_noauth_server.py
tests/fake_http_server/ssl_server.py
tests/sota_tools/treehub_deploy_server.py

Unit tests for OSTreeObject class.
Really only covers the constructor, MakeTestRequest, and Upload. These are the components that are easiest to verify and have the most external interaction. Testing CurlDone or the various OSTree parsing bits might be interesting, but it is quite difficult to decouple from other parts of the code, and the whole of it is already covered by higher-level tests. I'll take suggestsions for improvements, but I think this is a good start.

Test/ota 815/ostree object

---

cmake-modules/FindAsn1c.cmake

Apparently APER fork of asn1c has some trouble with yocto paths, so the easiest way to fix the issue for Sachertorte is to override one path.

Allow to redefine the path to ASN1C skeletons

---

CHANGELOG.md
config/CMakeLists.txt
config/sota_ubuntu.toml
config/systemd/aktualizr-ubuntu.service
docs/deb-package-install.adoc
docs/debugging-tips.adoc
src/aktualizr_primary/main.cc
src/hmi_stub/main.cc
src/libaktualizr/config/config.cc
src/libaktualizr/config/config.h
src/libaktualizr/config/config_test.cc
tests/CMakeLists.txt

It allows us to treat `secondary_configs_dir` as a regular configuration option, which can be set in the main configuration and not only from the command line.
Will need changes in meta-updater and probably docs. Shout if you don't agree!

Read secondary configs json from one directory

---

config/CMakeLists.txt

We end up removing these files in meta-updater, so bettter not creating them in the first place

Only ship ubuntu config files with BUILD_DEB=on

---

src/hmi_stub/main.cc
src/libaktualizr/primary/aktualizr.cc
src/libaktualizr/primary/aktualizr.h
src/libaktualizr/primary/sotauptaneclient.h
src/libaktualizr/uptane/fetcher.cc
src/libaktualizr/uptane/fetcher.h
src/libaktualizr/utilities/events.h
src/libaktualizr/utilities/results.h

Sorry for the confusion of making a PR on a PR, but I realized we'd missed a requirement because of mutual misunderstanding (as in, I didn't realize we needed it until an hour ago) and I knew I could kick it out quickly. All this really does is add return values for pause/resume, since it is possible that they can succeed or fail for various reasons.

Return values for pause and resume.

---

src/libaktualizr/primary/aktualizr_test.cc
src/sota_tools/authenticate_test.cc
src/sota_tools/ostree_http_repo_test.cc
tests/test_utils.cc
tests/test_utils.h

Avoid having to add a new string argument all the time and do not supply extraneous empty arguments to subprocesses

Make TestHelperProcess variadic

---

src/libaktualizr/uptane/fetcher.cc
src/libaktualizr/utilities/utils.cc
src/libaktualizr/utilities/utils.h
src/libaktualizr/utilities/utils_test.cc

Needed for Sachertorte, but a good thing to have in general probably.

fetcher: urlencode target names

---

src/libaktualizr/utilities/types.h

This is part of our external API (in the general sense), we should not rely on C's tricks to define this enum.

Assign explicit num code to UpdateResultCode

---

src/libaktualizr/http/httpclient.cc

Timeout for all libcurl operations is set to 60 sec,
which is not suitable for download, as it could take
much longer. To prevent slow retrieval attack we set
CURLOPT_LOW_SPEED_LIMIT and CURLOPT_LOW_SPEED_TIME.

Disable timeout for download operation 

---

docs/README.adoc

Tagged doxygen docs are already pushed:
* [2018.8](https://advancedtelematic.github.io/aktualizr/2018.8/index.html)
* [2018.9](https://advancedtelematic.github.io/aktualizr/2018.9/index.html)
* [2018.11](https://advancedtelematic.github.io/aktualizr/2018.11/index.html)
* [2018.12](https://advancedtelematic.github.io/aktualizr/2018.12/index.html)
* [2018.13](https://advancedtelematic.github.io/aktualizr/2018.13/index.html)

Add instructions for how to build and push tagged doxygen docs

---

src/libaktualizr/http/httpclient_test.cc
src/libaktualizr/uptane/fetcher_test.cc
src/libaktualizr/uptane/ipsecondary_discovery_test.cc
src/libaktualizr/uptane/uptane_network_test.cc
src/sota_tools/authenticate_test.cc
src/sota_tools/deploy_test.cc
src/sota_tools/ostree_http_repo_test.cc
src/sota_tools/ostree_object_test.cc
src/sota_tools/treehub_server_test.cc
tests/fake_http_server/ssl_noauth_server.py
tests/fake_http_server/ssl_server.py
tests/test_utils.cc
tests/test_utils.h

Lots of tests sleep for 3 or 4 seconds in the expectation that the test server will be ready in that time. However, our CI regularly fails when that assumption is not true. So instead of increasing the time, just poll the server for readiness and sleep only as long as necessary.
I'm not sure this is bulletproof yet, and it seems valgrind doesn't play nicely. But I think this is a better solution than just sleeping.

Only sleep as long as it takes for the server to be ready.

---

src/aktualizr_primary/main.cc
src/hmi_stub/main.cc
src/libaktualizr/primary/sotauptaneclient.cc

If there are updates, still print at info level. I also silenced the log message in aktualizr-primary and hmi-stub that we got the event; it was redundant.
Fixes #1021.

Change message about no new updates to debug level.

---

src/aktualizr_primary/main.cc

We did not wait for the result of the futures after issuing commands like "CheckUpdates".
This broke the existing behaviour of `aktualizr check`.
Bug introduced in 79283a3c77a584d9a7f5e48f83297c4201e394fe

Fix races in aktualizr with running modes

---

src/libaktualizr/crypto/keymanager.cc
src/libaktualizr/crypto/keymanager.h
src/libaktualizr/http/httpclient.cc
src/libaktualizr/http/httpclient.h
src/libaktualizr/http/httpinterface.h
src/libaktualizr/primary/initializer.cc
tests/httpfake.h

For `copyCertsToCurl` it's just nice to be able to apply it to bare `HttpInterface` instances.
For `downloadAsync` it can be necessary to access curl handler from the caller. In the proxy we use it to set response code to what we've got from the server before we have returned from `curl_easy_perform`, which happens only after the whole file has been downloaded.

Small changes for Angel Delight project

---

src/libaktualizr/http/httpclient.cc
src/libaktualizr/http/httpclient.h
src/libaktualizr/http/httpinterface.h
src/libaktualizr/package_manager/ostreemanager.cc
src/libaktualizr/package_manager/ostreemanager.h
src/libaktualizr/uptane/fetcher.cc
src/libaktualizr/uptane/fetcher.h
src/libaktualizr/uptane/fetcher_test.cc
tests/fake_http_server/fake_http_server.py
tests/httpfake.h

There are several problems with pause-resume fetcher API and the corresponding fetcher test that I see at the moment.
1. Fetcher test currently uses `large_interrupted` file for pause/resume. With `large_interrupted` server aborts after transferring half of a file (1000 bytes). This should lead to the `The target's calculated hash did not match the hash in the metadata` error and, after that, the upper layer may choose to retry. However, currently, the test succeeds, because while committing the first half to the db, fetcher gets `pause` event, which makes it retry silently after `resume` is called. This behavior itself is not a problem, the problem is that it is also correct for the test to fail, if `pause` comes after the first chunk is committed.
2. Race condition between …

Fixes for fetcher

---

src/libaktualizr/primary/aktualizr.cc
src/libaktualizr/primary/aktualizr.h
src/libaktualizr/primary/aktualizr_test.cc

Hide events::Channel from testing Aktualizr constructor

---

src/aktualizr_repo/repo_test.cc

They used to be run with all key types, including big RSA.
This was our longest running test, despite testing one of our less critical piece of code. Let's just use the fastest key type we have.

Only run aktualizr-repo tests with ed25519

---

actions.md
docs/configuration.adoc
docs/selectively-triggering-aktualizr.adoc
scripts/test_aktualizr_repo.sh
scripts/test_install_aktualizr_and_update.sh
src/aktualizr_primary/main.cc
src/libaktualizr/config/config.cc
src/libaktualizr/config/config.h
src/libaktualizr/config/config_test.cc
src/libaktualizr/primary/aktualizr.cc
src/libaktualizr/primary/aktualizr.h
src/libaktualizr/primary/aktualizr_test.cc
src/libaktualizr/primary/sotauptaneclient.h
src/libaktualizr/uptane/uptane_test.cc
src/libaktualizr/utilities/config_utils.h
src/libaktualizr/utilities/types.cc
src/libaktualizr/utilities/types.h
tests/auto_prov_test.py
tests/hsm_prov_test.py
tests/implicit_prov_test.py

aktualizr still has an input parameter (--run-mode) that does the same thing, but this is no longer wired directly into libaktualizr; it exists purely in the wrapper outside it. This should be much cleaner and simpler to use.
Note that once upon a time I advocated for all aktualizr commandline options to be also represented in the config. I no longer believe this to be a good idea for things that only matter outside of libaktualizr. An internal "run mode" for libaktualizr does not make sense. It should be driven by the code outside of the API.

Get rid of running modes.

---

src/libaktualizr/primary/aktualizr_test.cc

This PR fixes APICheck test fails. 
But the problem was in Aktualizr class where we didn't disconnects from connected slots at destruction.
Signed-off-by: Serhiy Stetskovych <patriotyk@gmail.com>

Disconnect all slots on Aktualizr destructor

---

cmake-modules/AddAktualizrTest.cmake
partial/CMakeLists.txt
src/aktualizr_repo/CMakeLists.txt
src/aktualizr_secondary/CMakeLists.txt
src/sota_tools/CMakeLists.txt

Make it possible to directly specify libraries that should be linked to a test.
This makes it easy to avoid recompiling SOTA_TOOLS_LIB_SRC for multiple tests,
and makes the add_aktualizr_test invocation more explicit. It also avoids
explicitly specifying target_include_directories, because cmake knows about any
public include dependencies for libraries.
Signed-off-by: Phil Wise <phil@phil-wise.com>

Introduce LIBRARIES argument to add_aktualizr_test

---

src/libaktualizr/uptane/CMakeLists.txt
src/libaktualizr/uptane/secondaryconfig.cc
src/libaktualizr/uptane/secondaryconfig.h

I think this code will get more complex when adding Docker support, and now
seems like a good time to get the definition out of the header file.
Signed-off-by: Phil Wise <phil@phil-wise.com>

Move non-trivial SecondaryConfig ctor out of header

---

CMakeLists.txt
cmake-modules/FindLibfiu.cmake
docs/README.adoc
docs/debugging-tips.adoc
docs/fault-injection.adoc
src/libaktualizr/package_manager/packagemanagerfake.cc
src/libaktualizr/utilities/CMakeLists.txt
src/libaktualizr/utilities/fault_injection.h
src/libaktualizr/utilities/fiu-local.h

Requires libfiu-dev on Debian derived distros.
Then:
```
cmake .. -DFAULT_INJECTION=on
make aktualizr
fiu-run -c 'enable name=fake_package_install' aktualizr -c . once
```

Add PoC fault injection in fake installer

---

cmake-modules/AddAktualizrTest.cmake
src/libaktualizr/uptane/CMakeLists.txt
src/libaktualizr/uptane/fetcher.cc
src/libaktualizr/uptane/fetcher.h
src/libaktualizr/uptane/fetcher_death_test.cc
src/libaktualizr/uptane/fetcher_test.cc
tests/test_utils.cc

A test scenario for the use-case when aktualizr process gets killed while being in a `pause` state. When the fetcher is called again, it's expected to start the download from the point it was paused on.
Currently, a delay of 15 seconds between `pause` call and killing the process is needed, as we have no reliable way to know when all background operations are completed, so we can resume later.
The PR also includes a fix for a stack overflow issue, that is triggered by this test on `resume`.

Test: fetcher death

---

CMakeLists.txt
src/libaktualizr/primary/reportqueue.cc
src/libaktualizr/primary/reportqueue.h

I've played a bit with a [ThreadSanitizer](https://github.com/google/sanitizers/wiki/ThreadSanitizerCppManual). There is a considerable amount of false positives, as ThreadSanitizer requires all libraries to be rebuild, and I didn't do that. But it still was able to find some interesting stuff. 
There are two issues with the current syncronization scheme of ReportQueue:
Member `shutdown_` is modified and checked out of the critical section, which may lead to various race conditions, e.g.:
```
Run() checks that shutdown is false
~ReportQueue() sets shutdown_ to true
~ReportQueue() locks mutex and does cv.notify_all()
Run() locks mutex and starts to wait on the CV
```
`flushQueue()` checks `report_queue_.empty()` out of the critical section and uses a different mutex, not the one than is …

Fixes for ReportQueue

---

tests/CMakeLists.txt

It will fail, as it requires libdpkg support.

Do not run memory test if BUILD_DEB is off.

---

tests/auto_prov_test.py
tests/hsm_prov_test.py
tests/implicit_prov_test.py
tests/prov_test_common.py

There is no need to launch `aktualizr once` as a background process before checking for provisioning as it should terminate by itself.
I'm not sure of the original intent but it should hopefully work this way.

Remove instances of popen_subprocess in prov tests

---

CMakeLists.txt
docker/Dockerfile-test-install.ubuntu.bionic
docker/Dockerfile-test-install.ubuntu.xenial
docker/Dockerfile.debian.testing
docker/Dockerfile.ubuntu.bionic
docker/Dockerfile.ubuntu.xenial
src/libaktualizr/utilities/utils_test.cc

I'm not sure if we should keep linking with static libraries for the debian case, or make it dynamic everywhere.
This might also break meta-updater due to changed run-time dependencies.
Otherwise, I see no benefits in linking boost statically.

Build with shared boost libraries

---

src/libaktualizr/storage/sqlstorage_base.cc
src/libaktualizr/storage/sqlstorage_test.cc
tests/run_aktualizr_info_tests.sh

We don't know what can happen when the software is running on an unknown version.

Fail when db migration fails

---

CHANGELOG.md
actions.md
src/hmi_stub/main.cc
src/libaktualizr/primary/aktualizr.cc
src/libaktualizr/primary/aktualizr.h
src/libaktualizr/primary/aktualizr_test.cc
src/libaktualizr/primary/events.h
src/libaktualizr/primary/reportqueue.cc
src/libaktualizr/primary/reportqueue.h
src/libaktualizr/primary/results.h
src/libaktualizr/primary/sotauptaneclient.cc
src/libaktualizr/primary/sotauptaneclient.h
src/libaktualizr/uptane/fetcher.cc

Now succeeds at all time: pauses current download as well as the api queue.
I still need to write some tests

Increase scope of pause api

---

src/aktualizr_repo/director_repo.cc
src/aktualizr_repo/director_repo.h
src/aktualizr_repo/image_repo.cc
src/aktualizr_repo/image_repo.h
src/aktualizr_repo/main.cc
src/aktualizr_repo/repo_test.cc
src/aktualizr_repo/uptane_repo.cc
src/aktualizr_repo/uptane_repo.h
src/libaktualizr/primary/aktualizr.h
src/libaktualizr/uptane/CMakeLists.txt
src/libaktualizr/uptane/uptane_delegation_test.cc
tests/uptane_repo_generation/CMakeLists.txt
tests/uptane_repo_generation/delegation_basic.sh

@patrickvacek  Those tests fails because there is some issues in delegation implementation I think.
So there is 3 tests, and 2 of them fails. The problem is when we check updates with delegation then we remove delegation and fetch again and we get an error "Hash verification for targets metadata failed". The problem is the same if we download targets before revoking delegation. But if we install delegated updates before revoke, the everything is ok.
I also tried to reproduce this issue by commenting the first block of code where we run aktualizr with delegation, to check does aktualizr can work with repository with revoked delegations, and it works well. So revoke functionality doesn't break the repo.

Feat/ota 678/delegation revoke tests

---

src/libaktualizr/storage/embed_schemas.py
src/libaktualizr/storage/sqlstorage_base.cc

Useful for custom projects, especially when they have only
the first version of their database

storage: support empty rollback migrations

---

src/aktualizr_repo/image_repo.cc
src/aktualizr_repo/image_repo.h
src/aktualizr_repo/main.cc
src/aktualizr_repo/repo.cc
src/aktualizr_repo/repo.h
src/aktualizr_repo/uptane_repo.cc
src/aktualizr_repo/uptane_repo.h
src/libaktualizr/primary/sotauptaneclient.cc
src/libaktualizr/primary/sotauptaneclient.h
src/libaktualizr/storage/invstorage.h
src/libaktualizr/storage/sqlstorage.cc
src/libaktualizr/storage/sqlstorage.h
src/libaktualizr/uptane/imagesrepository.cc
src/libaktualizr/uptane/imagesrepository.h
src/libaktualizr/uptane/tuf.cc
src/libaktualizr/uptane/tuf.h
src/libaktualizr/uptane/tuf_test.cc
src/libaktualizr/uptane/uptane_delegation_test.cc
tests/uptane_repo_generation/delegation_nested.sh

Also, this enables nested delegations

Refactor delegations to hopefuly be more secure

---

config/sql/migration/migrate.18.sql
config/sql/rollback/rollback.18.sql
config/sql/schema.sql
src/libaktualizr/storage/invstorage.h
src/libaktualizr/storage/sqlstorage.cc
src/libaktualizr/storage/sqlstorage.h
src/libaktualizr/storage/sqlstorage_base.h
src/libaktualizr/storage/storage_common_test.cc
src/libaktualizr/uptane/fetcher.cc

Signed-off-by: Serhiy Stetskovych <patriotyk@gmail.com>

Store image files on the filesystem

---

src/libaktualizr/storage/sqlstorage.cc

Not worth an ERROR, happens all the time in normal operation

Move "missing installation result" log to TRACE

---

CMakeLists.txt

At least required on older Ubuntu

Link with dl when using libfiu

---

src/libaktualizr/primary/sotauptaneclient.cc

Skip primary while sending images to secondary ECUs

---

src/libaktualizr/storage/sqlstorage_base.cc
src/libaktualizr/storage/sqlstorage_base.h

Instead of applying forward migrations.
Also, insert all backward migrations, not only those between we migrated from.
For the command  `time build/run-valgrind "build/src/libaktualizr/storage/t_sqlstorage" "src/libaktualizr/storage/test" --gtest_filter=sqlstorage.migrate_from_fs`, here is before and after:
```
==15663== HEAP SUMMARY:
==15663==     in use at exit: 35,188 bytes in 237 blocks
==15663==   total heap usage: 40,509 allocs, 40,272 frees, 10,669,084 bytes allocated
==15663==
==15663== LEAK SUMMARY:
==15663==    definitely lost: 0 bytes in 0 blocks
==15663==    indirectly lost: 0 bytes in 0 blocks
==15663==      possibly lost: 0 bytes in 0 blocks
==15663==    still reachable: 18,144 bytes in 37 blocks
==15663==                       of which reachable via heuristic:
==15663== …
```

Directly bootstrap empty DB from current schema

---

src/libaktualizr/package_manager/ostreemanager.cc

Uses a glib autofree pointer.
Leak found in #1107.

Fix a leak in OstreeManager::install

---

docs/implicit-provisioning.adoc

In meta-updater, the variable SOTA_CLIENT_PROV for implicit
provisioning needs to be set to `aktualizr-ca-implicit-prov`.
Signed-off-by: Stefan Agner <stefan.agner@toradex.com>

fix implicit provisioning documentation

---

src/CMakeLists.txt
src/aktualizr_lite/CMakeLists.txt
src/aktualizr_lite/main.cc
src/aktualizr_lite/test_lite.sh
src/aktualizr_repo/image_repo.cc
src/aktualizr_repo/image_repo.h
src/aktualizr_repo/main.cc
src/aktualizr_repo/uptane_repo.cc
src/aktualizr_repo/uptane_repo.h
src/libaktualizr/primary/sotauptaneclient.h

This PR is meant to address the functionality discussed in issue #1056. I'm not super happy about the lack of any new test coverage, but I was a little concerned it would require so much mocking that it might not provide much value. However, I'd be more than happy to work on that if you guys think its needed.
I've tested this against two different services:
1) Foundries.io's OTA Connect Deployment
https://api.foundries.io/lmp/repo/release/api/v1/user_repo/targets.json
2) An "aktualizr-lite" only docker-compose setup
https://github.com/doanac/ota-compose

Create new "aktualizr-lite" command

---

src/cert_provider/main.cc

Write the gateway URL file to the default base path (/var/sota/import)
or the configured base path.
Signed-off-by: Stefan Agner <stefan.agner@toradex.com>

Make sure cert provider writes gateway URL file where expected

---

scripts/run_docker_test.sh

Resolve: './scripts/run_docker_test.sh: line 49: DOCKER_OPTS[@]: unbound variable'
Signed-off-by: Ben Clouser <ben.clouser@toradex.com>
for issue:
https://github.com/advancedtelematic/aktualizr/issues/1124

Fix unbound variable DOCKER_OPTS[@] in run_docker_test.sh

---

tests/CMakeLists.txt

They used to rely on invalid config / failed provisioning.

Force some argument parsing tests to terminate

---

CMakeLists.txt
src/libaktualizr/config/config.cc
src/libaktualizr/package_manager/CMakeLists.txt
src/libaktualizr/package_manager/androidmanager.cc
src/libaktualizr/package_manager/androidmanager.h
src/libaktualizr/package_manager/packagemanagerconfig.h
src/libaktualizr/package_manager/packagemanagerfactory.cc
src/libaktualizr/telemetry/telemetryconfig.cc
src/libaktualizr/uptane/managedsecondary.cc
src/libaktualizr/utilities/config_utils.h
src/libaktualizr/utilities/utils.cc
src/libaktualizr/utilities/utils.h

* build script update required by atkualizr-android
* package manager for android
* log system integration

Android support

---

src/libaktualizr/primary/sotauptaneclient.cc

- stop logging it when the manifest put is inhibited by a pending install
- more detailed output when it couldn't be sent to the server

Better "could not put manifest" error

---

src/aktualizr_lite/main.cc
src/aktualizr_lite/test_lite.sh

Set the required permission (700) for the DB/storage folder (<tmp-dir>/sota) in test_lite.sh.
Set '1' as a default and error exit code instead of -1.

Set the required permission for the DB/storage folder

---

tests/CMakeLists.txt

Dev activity seems to have sped up recently, should help us get rid of some cruft.
I've just checked and it doesn't emit warnings with clang-tidy anymore, so we could check our test files as well (after a cleanup).

Bump googletest version

---

actions.md
src/aktualizr_info/aktualizr_info_test.cc
src/aktualizr_info/main.cc
src/libaktualizr/storage/invstorage.h
src/libaktualizr/storage/sqlstorage.cc
src/libaktualizr/storage/sqlstorage.h

1. Added an option `--delegate` to aktualizr-info aimed to print delegations metadata;
2. Added corresponding tests.

OTA-2320: Add an option to aktualizr-info to print delegations metadata

---

src/libaktualizr/utilities/utils.cc
src/libaktualizr/utilities/utils_test.cc

The property was lost when rewritten from Utils::glob

Make Utils::getDirEntriesByExt return sorted results

---

src/libaktualizr/primary/sotauptaneclient.cc
src/libaktualizr/primary/sotauptaneclient.h
src/libaktualizr/uptane/CMakeLists.txt
src/libaktualizr/uptane/iterator.cc
src/libaktualizr/uptane/iterator.h

Iterating targets really isn't dependent on the SotaUptaneClient and
future code in the package manager will need to be able to iterate
through targets to function. Moving it now will help remove a future
circular dependency.

Move target iterator logic into uptane module

---

CHANGELOG.md
CMakeLists.txt
actions.md
cmake-modules/AddAktualizrTest.cmake
config/sql/migration/migrate.19.sql
config/sql/rollback/rollback.19.sql
config/sql/schema.sql
docs/fault-injection.adoc
scripts/fiu
src/libaktualizr/package_manager/packagemanagerfake.cc
src/libaktualizr/package_manager/packagemanagerfake_test.cc
src/libaktualizr/primary/aktualizr.h
src/libaktualizr/primary/aktualizr_test.cc
src/libaktualizr/primary/sotauptaneclient.cc
src/libaktualizr/primary/sotauptaneclient.h
src/libaktualizr/storage/schema_migration_test.sh
src/libaktualizr/storage/sqlstorage.cc
src/libaktualizr/storage/sqlstorage_test.cc
src/libaktualizr/storage/storage_common_test.cc
src/libaktualizr/uptane/uptane_test.cc
src/libaktualizr/utilities/fault_injection.h
src/libaktualizr/utilities/types.cc
src/libaktualizr/utilities/types_test.cc
tests/CMakeLists.txt
tests/fiuinfo_test.cc

Based on #1144.
In a nutshell:
- keep a stable ecu order (what's given in StoreEcuSerials)
- device installation result code contains a concatenation of `ecu_type:error` in case of error
- added functionality on top of libfiu, uses temporary files as storage for strings
Will add a test for the changes in `SotaUptaneClient::computeDeviceInstallationResult` when ready

Feat/ota 2282/more failure simulation

---

src/libaktualizr/uptane/fetcher_test.cc

Way too verbose (~300kB of text)

Remove trace logging from test_fetcher

---

src/libaktualizr/primary/sotauptaneclient.cc

It was saying it tried -1 times. Now it should be accurate.

Fix log message about download failure retry count.

---

src/libaktualizr/package_manager/CMakeLists.txt
src/libaktualizr/package_manager/fetcher_test.cc

Currently, we are copying an ostree sysroot directory created by make_ostree_sysroot CMake target to use as a destination local repo for OSTree pull. For some reason, sometimes it was causing a problem on some deployments similar to the problem described and fixed by @patriotyk in https://github.com/advancedtelematic/aktualizr/pull/1007#issuecomment-441233660
This PR replaces the copy, as it's should be even faster to create an empty sysroot in a temp dir, and it also seems to fix the problem.
Signed-off-by: Eugene Smirnov <evgenii.smirnov@here.com>

fetcher_test: create temporary repo for OSTree

---

actions.md
src/libaktualizr/primary/aktualizr.h
src/libaktualizr/primary/aktualizr_test.cc
src/libaktualizr/primary/events.h
src/libaktualizr/primary/sotauptaneclient.cc

1. Test event sending if download fails;
2. Fix the download result if partial download failure.

OTA-1684: Test events sending if target downloading fails

---

CMakeLists.txt

Apparently clang is not friendly to this flag. This could be specific to certain versions, and it may be possible to make this work in another way. But for now I want to unblock @koshelev.

Only set -Wl,--as-needed for gcc

---

actions.md
docs/fault-injection.adoc
src/libaktualizr/package_manager/packagemanagerfake.cc
src/libaktualizr/primary/aktualizr.h
src/libaktualizr/primary/aktualizr_test.cc
src/libaktualizr/primary/sotauptaneclient.cc
src/libaktualizr/primary/sotauptaneclient.h
src/libaktualizr/storage/sqlstorage.cc
src/libaktualizr/storage/storage_common_test.cc
src/libaktualizr/uptane/virtualsecondary.cc
src/libaktualizr/utilities/fault_injection.h
src/libaktualizr/utilities/types.h

1. Added  tests for two cases:
a) installation failure;
b) installation finalization failure.
2. Fixed two bugs
a) taking into account  the `need completion` case  in the procedure that computes and stores an installation result;
b) return false if there is no any ECU installation result records in DB in order to make it consistent with other DB methods.

OTA-1684: Test installation and installation finalization failures

---

src/aktualizr_lite/main.cc
src/libaktualizr/logging/android_log_sink.cc
src/libaktualizr/logging/default_log_sink.cc
src/libaktualizr/logging/logging.cc
src/libaktualizr/logging/logging.h

All the young kids have discovered ansi escape sequences and are
producing colorful logs for TTYs. This may be your project's first PR
that needs a screenshot to explain:
https://imgur.com/t0R4lO1

logging: Add optional ansi color-escaping for logs

---

src/aktualizr_lite/main.cc
src/libaktualizr/primary/sotauptaneclient.h
src/libaktualizr/uptane/iterator.cc

I was testing aktualizr-lite today and noticed what I think may be a new regression. If the repo server is offline, you'll get a core-dump like:
~~~
info: Refreshing target metadata
error: curl error 7 (http code 0): Couldn't connect to server
error: curl error 7 (http code 0): Couldn't connect to server
error: curl error 7 (http code 0): Couldn't connect to server
error: Unable to update latest metadata, using local copy
info: Updates available to raspberrypi3-64:
Segmentation fault (core dumped)
~~~
This fix does 2 things:
1) Adds exception handling for the situation in iterator.cc to make debugging future issues easier
2) Updates aktualizr-lite to be able to use the offline data if possible

Fix null pointer bug in aktualizr-lite

---

src/sota_tools/deploy.cc

Verification steps:
make check & make qa
Bitbaking and running 'happy path' scenarios on qemu, see this PR https://github.com/advancedtelematic/meta-updater/pull/510 for more details.

OTA-2418: Remove example.com URL from automated garage-sign usage

---

src/libaktualizr/storage/CMakeLists.txt

The `sql_schemas_target` is not generated anymore but was still present in the OUTPUT section of `add_custom_command` rule. That was causing `make` to rebuild the target every time.
Looks like the issue didn't appear when building with `ninja`.

Remove unexisting CMake target

---

src/libaktualizr/package_manager/fetcher_test.cc

So that it can be run on temporary file systems (ptest for example)

Use bare-user-only in test_fetcher

---

src/cert_provider/cert_provider_test.cc

On OpenSSL 1.1.1b 26 Feb 2019, the line shows as:
RSA Private-Key: (1024 bit, 2 primes)
Instead of:
RSA Private-Key: (1024 bit)
One character diff PR!

Fix cert_provider_test with recent versions of openssl

---

.travis.yml
scripts/build_ubuntu.sh
tests/glib.supp

From flatpack project.
An example of these was found when running the suite under ptest.

Use more recent glib suppression list

---

src/aktualizr_repo/repo.cc
src/aktualizr_repo/repo_test.cc
src/libaktualizr/uptane/imagesrepository.cc
src/libaktualizr/uptane/tuf.cc

Uptane (and TUF) no longer require them. If they are there, we will use
them, and if not, we skip them. This provides no real security benefit,
but may help detect implementation faults.
For more information, see:
https://github.com/uptane/uptane-standard/issues/90
https://github.com/uptane/uptane-standard/pull/92
Please also review https://github.com/advancedtelematic/tuf-test-vectors/pull/49. That needs to get merged first.

 Don't require hashes and sizes of Targets objects in Snapshot metadata.

---

src/aktualizr_primary/CMakeLists.txt
src/aktualizr_primary/main.cc
src/aktualizr_primary/secondary.cc
src/aktualizr_primary/secondary.h
src/aktualizr_primary/secondary_config.cc
src/aktualizr_primary/secondary_config.h
src/aktualizr_secondary/aktualizr_secondary.cc
src/aktualizr_secondary/aktualizr_secondary_common.cc
src/aktualizr_secondary/socket_server.cc
src/libaktualizr-posix/asn1/asn1_message.cc
src/libaktualizr-posix/asn1/asn1_message.h
src/libaktualizr-posix/asn1/messages/ipuptane_message.asn1
src/libaktualizr-posix/ipsecondarydiscovery.cc
src/libaktualizr-posix/ipuptanesecondary.cc
src/libaktualizr-posix/ipuptanesecondary.h
src/libaktualizr/config/config.cc
src/libaktualizr/config/config.h
src/libaktualizr/uptane/secondaryconfig.h
src/libaktualizr/uptane/secondaryinterface.h

1. Tiny IpUptaneSecondary refactoring 
- to make it working with a fake package manager;
- to get serial & hw-id from Secondary during initialization;
2. Pre-configure Secondary with IP addresses by using a json configuration file;
3. Initialize Aktualizr app with Secondaries.

OTA-2536: Preconfigure IpUptaneSecondary with IP address

---

src/libaktualizr/crypto/p11engine.h
src/libaktualizr/http/httpclient.cc
src/libaktualizr/http/httpclient.h
src/libaktualizr/package_manager/packagemanagerfake.cc
src/libaktualizr/package_manager/packagemanagerfake_test.cc
src/libaktualizr/primary/CMakeLists.txt
src/libaktualizr/primary/aktualizr.h
src/libaktualizr/primary/aktualizr_test.cc
src/libaktualizr/primary/empty_targets_test.cc
src/libaktualizr/primary/sotauptaneclient.cc
src/libaktualizr/primary/sotauptaneclient.h
src/libaktualizr/uptane/CMakeLists.txt
src/libaktualizr/uptane/director_test.cc
src/libaktualizr/uptane/directorrepository.cc
src/libaktualizr/uptane/directorrepository.h
src/libaktualizr/uptane/uptane_delegation_test.cc
src/libaktualizr/uptane/uptane_test.cc
src/sota_tools/ostree_object.h
tests/httpfake.h

Two main fixes:
1. Check for updates even if sending the manifest fails.
2. Persist the last non-empty targets metadata received from the Director to make sure we always know what the last thing we were expected to install was.
There are tests for both in addition to some other much smaller things found while working on this.

Fix/ota 2451/empty targets

---

src/libaktualizr/primary/aktualizr.h
src/libaktualizr/primary/empty_targets_test.cc
src/libaktualizr/primary/sotauptaneclient.cc
src/libaktualizr/uptane/directorrepository.cc
src/libaktualizr/uptane/directorrepository.h
src/libaktualizr/uptane/tuf.h

As backend sends empty director targets in some unexpected situations,
we've implemented a client-side mitigation in
02deeb5cc45e2a1fac4f6e3eb515a396cd14c1c3.
One unwanted side-effect is that after a failed installation, we'll keep
taking into account the targets containing the new version, hence
retrying installations in a loop until the backend asks to install
something new.
Second fix is to drop director targets after installation end, until
we've come to an agreement on a proper solution on both sides.
Note: would probably need an accompanying unit test, on the way :)

Fix issue with never-ending install retries

---

src/aktualizr_secondary/socket_server.cc
src/libaktualizr-posix/asn1/asn1_message.h
src/libaktualizr-posix/asn1/asn1_test.cc
src/libaktualizr-posix/asn1/messages/ipuptane_message.asn1
src/libaktualizr-posix/ipuptanesecondary.cc

Tiny improvement to avoid two RPC calls during a secondary client initialization, i.e. get serial, hw-id and pub-key within a single RPC call.

OTA-2536: Get a pub key along with hw_id and serial

---

.travis.yml

The new default:
https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment
+ remove deprecated sudo flag
https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
Would be curious to see if it fixes our problem with deploying the last release.

Move Travis build env to Xenial

---

src/aktualizr_primary/secondary.cc
src/aktualizr_primary/secondary_config.cc
src/aktualizr_primary/secondary_config.h
src/aktualizr_secondary/aktualizr_secondary.cc
src/aktualizr_secondary/aktualizr_secondary.h
src/aktualizr_secondary/aktualizr_secondary_config.cc
src/aktualizr_secondary/aktualizr_secondary_config.h
src/aktualizr_secondary/socket_server.cc
src/libaktualizr-posix/asn1/asn1_message.cc
src/libaktualizr-posix/asn1/asn1_message.h
src/libaktualizr-posix/ipuptanesecondary.cc
src/libaktualizr-posix/ipuptanesecondary.h
src/libaktualizr/utilities/utils.cc
src/libaktualizr/utilities/utils.h

1. Add ability to specify params that are common across secondaries of the same type (connection wait timeout);
2. Primary waits for a connection from Secondary if it fails to connect to it. Secondary tries to connect to Primary at a startup time.

Refact/ota 2487/ipsecondaries initialization

---

actions.md
src/aktualizr_info/aktualizr_info_test.cc
src/aktualizr_info/main.cc

Print currently installed and pending image versions on secondary ECUs

OTA-2540: Print installed and pending version on Secondary

---

CMakeLists.txt
tests/CMakeLists.txt
tests/aktualizr_cycle_simple.cc
tests/fake_http_server/fake_test_server.py
tests/ipsecondary_test.py
tests/test_io_failure.py

What the test is doing: run a provisioning + update cycle with possible failing syscall (should be ~ 1 io syscall per run), then if an error occured, run it again with the same state but without injected error. The update should go through.
Right now the test uses the fake package manager, it could be more interesting to run it with ostree somehow (though more challenging).
I'll soon launch a long test with an atomicity bug and  see if it's caught as expected!

Probabilistic IO failure test

---

tests/CMakeLists.txt
tests/ipsecondary_test.py

Fix the issue with test_ip_secondary test executed in scope of the ptest.

OTA-2540: SRC dir as a param for the IP Secondary test

---

src/libaktualizr/config/config_test.cc
tests/test_data/config_dirs/one_dir/a.toml
tests/test_data/config_dirs/one_dir/z.toml
tests/test_data/config_dirs/second_one_dir/a.toml
tests/test_data/config_dirs/second_one_dir/y.toml
tests/test_data/config_dirs/second_one_dir/z.txt

those data are used for unit test of config module,
easy to create in unit test, not necessary put these
files in git repository

remove test_data/config_dirs, create it on the fly

---

src/aktualizr_info/aktualizr_info_config.h
src/aktualizr_secondary/aktualizr_secondary_config.h
src/cert_provider/CMakeLists.txt
src/libaktualizr/CMakeLists.txt
src/libaktualizr/bootloader/CMakeLists.txt
src/libaktualizr/bootloader/bootloader.cc
src/libaktualizr/bootloader/bootloader_config.cc
src/libaktualizr/bootloader/bootloader_config.h
src/libaktualizr/config/CMakeLists.txt
src/libaktualizr/package_manager/CMakeLists.txt
src/libaktualizr/package_manager/packagemanagerconfig.cc
src/libaktualizr/package_manager/packagemanagerconfig.h
src/libaktualizr/storage/CMakeLists.txt
src/libaktualizr/storage/invstorage.cc
src/libaktualizr/storage/storage_config.cc
src/libaktualizr/storage/storage_config.h
src/libaktualizr/telemetry/CMakeLists.txt
src/libaktualizr/uptane/CMakeLists.txt

Put aktualizr-cert-provider in garage_deploy.deb

---

ci/gitlab/.gitlab-ci.yml
scripts/selfupdate_server.py
scripts/test_aktualizr_repo.sh
scripts/test_install_aktualizr_and_update.sh
scripts/test_install_garage_deploy.sh

Initially made the change because using docker volumes was broken on gitlab CI yesterday (seems to have been fixed now). But I also think it's a little bit cleaner now anyway.
I'm also thinking about removing these install tests from Jenkins and Travis, so that we can continue to clean it up some more and not have to deal with the `/persistent` business.

Split pkg tests

---

CMakeLists.txt
scripts/build_ubuntu.sh

Was added in 299475fac6c29ff969ecc06a12b2833d92bf2538 to fix some .deb
lint warning (lintian), but bitbake doesn't like it.

Revert stripping of executable in release mode

---

docs/posix-secondaries-bitbaking.adoc
docs/posix-secondaries.adoc

OTA-2294: Primary and Secondary baking doc update with specifics for RPi target

---

src/aktualizr_lite/main.cc

This is a bit of an edge case, but I've found it useful to run
devices in the lite mode, but to still restrict who can access
the tuf/treehub repos via TLS.

aktualizr-lite: Support using TLS keys

---

CMakeLists.txt
src/aktualizr_lite/main.cc
src/aktualizr_primary/main.cc
src/aktualizr_secondary/main.cc
src/cert_provider/main.cc
src/hmi_stub/main.cc
src/libaktualizr/http/httpclient.cc
src/libaktualizr/utilities/CMakeLists.txt
src/libaktualizr/utilities/aktualizr_version.cc
src/libaktualizr/utilities/aktualizr_version.h
src/sota_tools/CMakeLists.txt
src/sota_tools/garage_check.cc
src/sota_tools/garage_deploy.cc
src/sota_tools/garage_push.cc
src/sota_tools/garage_tools_version.cc
src/sota_tools/garage_tools_version.h

Would be nice to have that as part of CI, it could maybe halve the test times. I just need to figure out why caching seems to be disabled on our shared runners.
In the meantime, it can already be used for development. The test case is:
```
apt install ccache
[...]
cd build1; cmake .. -DXXXX && ninja
cd build2; cmake .. -DXXXX && ninja  # (with same CMake options), should be MUCH faster
```

Support for ccache

---

src/sota_tools/CMakeLists.txt
src/sota_tools/check.cc
src/sota_tools/check.h
src/sota_tools/garage_check.cc
src/sota_tools/garage_deploy.cc

 using garage-check automatically at the end of garage-deploy

---

src/libaktualizr/package_manager/dockerappmanager_test.cc

Commit 5146f1980e4460ce880146d890b52885609942a7 removed the
newTestClient constructor. It was moved to uptane_test_common, but that
code seems to depend on virtual-secondary stuff that's not required
by package-manager code. I've copied the logic of this constructor
directly into this test to get it working again.

docker-app-mgr: Fix test regression

---

src/aktualizr_lite/CMakeLists.txt
src/aktualizr_lite/main.cc
src/aktualizr_lite/test_lite.sh
src/aktualizr_lite/version.h
src/aktualizr_lite/version_test.cc

You can't assume the targets will be ordered latest->oldest. This
creates a version comparison helper that tries its best to compare
things.

aktualizr-lite: Fix logic for finding latest version

---

CHANGELOG.md

Can it be automated or maybe we have some tools for it already ?
As alternative, we can introduce a rule requiring a PR owner to update CHANGELOG.md in scope of his/her PR so it will be staying up-to-date all the time ?

Update CHANGELOG for 2019.5 release

---

src/libaktualizr/http/httpclient.cc
src/libaktualizr/http/httpclient.h
src/libaktualizr/http/httpclient_test.cc

This allows custom users of libaktualizr to pass custom headers
with HTTP requests sent to the server.

httpclient: Add ability to pass custom headers

---

src/aktualizr_info/main.cc
tests/prov_test_common.py

Add --wait-until-provisioned option to aktualizr-info

---

src/libaktualizr/package_manager/fetcher_test.cc
src/libaktualizr/package_manager/packagemanagerinterface.cc

Prevents a divide-by-zero error.
I found this while seeing what happens when aktualizr tries to download an OSTree target with the fake package manager. With this fix, it "works" as much as downloading anything else "works" with the fake package manager.

Don't download targets with a length of 0.

---

src/aktualizr_primary/main.cc

It was only being sent on the check run mode, but it should also be sent on once and full (the default).

Send device data before UptaneCycle or RunForever.

---

docs/aktualizr-repo.adoc
src/aktualizr_repo/director_repo.cc
src/aktualizr_repo/director_repo.h
src/aktualizr_repo/image_repo.cc
src/aktualizr_repo/image_repo.h
src/aktualizr_repo/main.cc
src/aktualizr_repo/repo_test.cc
src/aktualizr_repo/uptane_repo.cc
src/aktualizr_repo/uptane_repo.h
src/libaktualizr/primary/CMakeLists.txt
src/libaktualizr/primary/custom_url_test.cc
src/libaktualizr/primary/empty_targets_test.cc
src/libaktualizr/primary/sotauptaneclient.cc
src/libaktualizr/primary/sotauptaneclient.h
src/libaktualizr/uptane/tuf.cc
src/libaktualizr/uptane/tuf.h
tests/metafake.h

The most interesting part is in sotauptaneclient.cc, where if the custom URL is not set in the Director target metadata, we check if it is set in the Images repo target metadata and use that if it is.
A lot of the changes relate to aktualizr-repo, where I added parameters to set the custom URL.

Fix/ota 3057/url determination

---

src/libaktualizr/primary/CMakeLists.txt
src/libaktualizr/primary/sotauptaneclient.cc
src/libaktualizr/primary/target_mismatch_test.cc
src/libaktualizr/uptane/uptane_test.cc
tests/uptane_vector_tests.cc

Note that this will soon be followed up with a PR that will move `uptaneOfflineIteration` to be used before downloading and installing so that metadata will get quickly re-checked before allowing either of those operations to proceed. We can optionally hold this back until that work is ready. That work will also expand the new target_mismatch_test.cc file.

Fix/ota 3059/target check sooner

---

docs/configuration.adoc
src/libaktualizr/bootloader/bootloader.cc
src/libaktualizr/bootloader/bootloader.h
src/libaktualizr/bootloader/bootloader_config.cc
src/libaktualizr/bootloader/bootloader_config.h

This is replacement for https://github.com/advancedtelematic/aktualizr/pull/1148 to trigger the gitlab CI. 
This patch mainly aims to add a graceful way to reboot the system by
executing a user preferred reboot command rather than calling reboot
system call. The reboot command could be set in 'bootloader' section of
a config file, it defaults to be '/sbin/reboot'.
Signed-off-by: Mykhaylo Sul <ext-mykhaylo.sul@here.com>

Configurable reboot command

---

src/aktualizr_repo/image_repo.cc

Caught by @eu-smirnov. After some review, I can't find any reason to keep the directory. It isn't used.

Don't create a directory that never gets used.

---

src/libaktualizr-c/test/CMakeLists.txt

By default, cmake adds all paths to the shared libraries during the linking process to rpath and removes it only on install step. This makes bitbake unhappy.
Signed-off-by: Eugene Smirnov <evgenii.smirnov@here.com>

libaktualizr-c: don't set rpath for api-test

---

tests/CMakeLists.txt

Test target "aktualizr-cycle-simple" indirectly depends on OSTree library since it use OstreeManager class.

TEST Target: aktualizr-cycle-simple depends on OSTree lib

---

.ort.yml

The important part is to ignore the third-party libraries pulled in. ORT
mostly complains about Python libraries used by tuf-test-vectors. The
test code in the src directory is probably fine.

Added exclusion of test code.

---

docs/provisioning-methods-and-credentialszip.adoc
src/sota_tools/server_credentials.cc
tests/sota_tools/cert_generation/api_gateway.url
tests/sota_tools/cert_generation/generate-zips.sh
tests/sota_tools/cert_generation/tufrepo.url

Continue to use the old URLs provided by treehub.url and the ostree.server field of treehub.json.
This is a partial revert of 67949117.

Do not use the api_gateway.url.

---

src/aktualizr_lite/CMakeLists.txt
src/aktualizr_lite/main.cc
src/aktualizr_lite/ostree_mock.cc
src/aktualizr_lite/test_lite.sh
src/libaktualizr/package_manager/ostreemanager.cc
src/libaktualizr/primary/sotauptaneclient.h

This is a 3 part change I've been carrying out-of-tree for a few weeks that I think makes aktualizr-lite act a little more like aktualizr. The first change allows aktualizr-lite to call getCurrent in CI. The second change finalizes installs in a similar way to the sotauptaneclient which then lets us change aktualizr-lite to use getCurrent the in last commit.

aktualizr-lite: Improve logic for pacman->getCurrent()

---

CHANGELOG.md
actions.md
src/libaktualizr/primary/aktualizr.cc
src/libaktualizr/primary/aktualizr.h
src/libaktualizr/primary/aktualizr_test.cc
src/libaktualizr/storage/invstorage.h
src/libaktualizr/storage/sqlstorage.cc
src/libaktualizr/storage/sqlstorage.h
src/libaktualizr/storage/sqlstorage_base.h
src/libaktualizr/storage/storage_common_test.cc

Add api calls to list and delete targets in storage.
Tests in test_aktualizr forthcoming.

Clean all targets

---

src/CMakeLists.txt
src/aktualizr_get/CMakeLists.txt
src/aktualizr_get/get.cc
src/aktualizr_get/get.h
src/aktualizr_get/get_test.cc
src/aktualizr_get/main.cc

I find myself carefully crafting `wget` commands to debug issues
between my device and device-gateway. This has gotten more complex
now that my team is using HSMs. This adds a simple tool to work
a bit like wget.

Create new "aktualizr-get" command

---

src/aktualizr_primary/main.cc

This is a partial revert of 1df4c1652ee50b467bbcb09d519fb7bd9b558e09.
I overzealously added a SendDeviceData before the call to RunForever,
despite that RunForever also calls SendDeviceData. This removes that
redundancy.
This does not change the behavior of "aktualizr once" (which uses
UptaneCycle). It still calls SendDeviceData before UptaneCycle, which
seems to roughly match user expectations.

Don't send device data twice by default.

---

src/libaktualizr/primary/CMakeLists.txt
src/libaktualizr/primary/download_nonostree_test.cc
src/libaktualizr/primary/sotauptaneclient.cc
src/libaktualizr/primary/sotauptaneclient.h
src/libaktualizr/uptane/exceptions.h

Draft code, just some thoughts to address this issue.

fix/ota-2421/disallow downloading non-OSTree binaries

---

docs/Doxyfile.in

Just a typo, my own fault while trying to help resolve merge failures.

Fix path to uptane-generator for Doxygen.

---

docs/ota-client-guide/modules/ROOT/pages/fault-injection.adoc
src/libaktualizr/package_manager/CMakeLists.txt
src/libaktualizr/package_manager/packagemanagerfake.cc
src/libaktualizr/package_manager/packagemanagerfake.h
src/libaktualizr/package_manager/packagemanagerfake_test.cc
src/libaktualizr/primary/aktualizr_test.cc
src/libaktualizr/primary/empty_targets_test.cc
src/libaktualizr/primary/sotauptaneclient.cc
src/libaktualizr/utilities/fault_injection.h
src/libaktualizr/utilities/types.cc
src/libaktualizr/utilities/types.h

This should inform the Director that the update failed.
This appears to fix the bug, but it is not perfect:
1) ~~There is no test, because we don't have a way to fake a download failure. It's probably doable with libfiu and the fake package manager, though.~~ This is now covered by tests.
2) There is the same problem with empty targets metadata that occurs with installation failure. It ~~could be~~ has been handled the same way, ~~although~~ despite that I don't like the solution of dropping metadata.
3) The installation report does not contain any information about how, why, or which download failed. That could be improved if anyone wants to see that.
We might want to consider merging testing and merging this as is anyway just to get the fix out the door, but further consideration is …

Report failed downloads in an installation report.

---

src/aktualizr_get/main.cc
src/aktualizr_lite/main.cc
src/aktualizr_primary/main.cc
src/aktualizr_secondary/main.cc
src/cert_provider/main.cc

Deprecated since openssl 1.1.0
See https://www.openssl.org/docs/man1.1.0/man3/SSL_load_error_strings.html

Remove deprecated function call

---

docs/ota-client-guide/modules/ROOT/nav.adoc
docs/ota-client-guide/modules/ROOT/pages/add-ota-functonality-existing-yocto-project.adoc
docs/ota-client-guide/modules/ROOT/pages/build-configuration.adoc
docs/ota-client-guide/modules/ROOT/pages/supported-boards.adoc

Preparing content so that it gets included from the meta updater repo and added to the developer guide (currently the source content is on the branch "meta-updater/docs/OTA-3594/antora-merge")
The first two items are:
* The "local.conf variables descriptions which are now in the "Reference" chapter
* The "supported software" topic which now pulls directly from meta-updater (instead of being a copy)
Signed-off-by: Merlin Carter <merlin.carter@here.com>

OTA-3594: Including first two pieces of content from meta-updater

---

src/libaktualizr/primary/aktualizr.cc

If API is used in asynchronous mode we cannot be sure
that parameters are still valid when we execute the lambda
function in different thread.
Signed-off-by: Eugene Smirnov <evgenii.smirnov@here.com>

libaktualizr API: capture parameters by-copy

---

src/libaktualizr/http/httpclient.cc
src/libaktualizr/utilities/utils.cc
src/libaktualizr/utilities/utils.h

Fixes https://github.com/advancedtelematic/aktualizr/issues/1273
Some versions of OE don't explicitly set a default path to the
CA certs directory. This ensures its set and can be overidden if
needed.

httpclient: Always set path to CA certs

---

src/aktualizr_lite/main.cc
src/libaktualizr/package_manager/CMakeLists.txt
src/libaktualizr/package_manager/dockerappmanager.cc
src/libaktualizr/package_manager/dockerappmanager.h
src/libaktualizr/package_manager/ostreemanager.cc
src/libaktualizr/package_manager/ostreemanager.h
src/libaktualizr/package_manager/packagemanagerfake_test.cc
src/libaktualizr/package_manager/packagemanagerinterface.cc
src/libaktualizr/package_manager/packagemanagerinterface.h
src/libaktualizr/primary/aktualizr_fullostree_test.cc
src/libaktualizr/primary/aktualizr_test.cc
src/libaktualizr/primary/download_nonostree_test.cc
src/libaktualizr/primary/sotauptaneclient.cc
src/libaktualizr/primary/sotauptaneclient.h
src/libaktualizr/uptane/iterator.cc
src/libaktualizr/uptane/iterator.h
src/libaktualizr/uptane/uptane_test.cc
tests/uptane_vector_tests.cc

~~This is still a work in progress, as there is additional work I'd like to include before merging. Also, `test_aktualizr-lite` is failing because of my changes and I'd like to discuss with @doanac how to reach a mutually satisfactory solution.~~
As to the changes, the biggest part is to recheck the Uptane metadata before downloading or installing a target. `uptaneIteration()` is now exclusively used during the check for updates, and it actually fetches the necessary metadata. `uptaneOfflineIteration()` is now exclusively used during downloading and installing to verify the integrity of the stored metadata. If a user then attempts to install a target that doesn't match the stored metadata, it will be rejected.
That stipulation required a lot of reworking of the Uptane tests, because …

Fix/ota 3060/check targets before download

---

docs/ota-client-guide/modules/ROOT/pages/aktualizr-config-options.adoc
docs/ota-client-guide/modules/ROOT/pages/build-raspberry.adoc

Specify it explicitly instead of relying on the default, since going forward we don't want to surprise users by changing their release branch. That should only be done with careful consideration.
@merltron / @tkfu does it make sense to have a note or a page describing the risks of changing branches? (Things like kernel/bootloader compatibility and the size of the update from one branch to another?)

Bump default Yocto branch in docs to thud.

---

src/libaktualizr/primary/aktualizr.h

This is just a really dumb little PR for the docs--there was an asterisk missing, so doxygen wasn't picking up the documentation for `Initialize`.

Fixed doxygen rendering for Initialize()

---

docs/ota-client-guide/modules/ROOT/nav.adoc
docs/ota-client-guide/modules/ROOT/pages/_partials/config-descriptions.adoc
docs/ota-client-guide/modules/ROOT/pages/aktualizr-config-options.adoc
docs/ota-client-guide/modules/ROOT/pages/build-quemu.adoc
docs/ota-client-guide/modules/ROOT/pages/build-raspberry.adoc
docs/ota-client-guide/modules/ROOT/pages/deploy-checklist.adoc
docs/ota-client-guide/modules/ROOT/pages/metadata-expiry.adoc
docs/ota-client-guide/modules/ROOT/pages/recommended-clientconfig.adoc

- Putting different ways of configuring into
tabs ie("local.conf" vs "sota_local.toml") and adding more content reuse.
- Minor fix to deploy checklist (added xref)
- Minor fix to env setup command
- restored missing ECU events from nav
Example of tabbed approach:
Signed-off-by: Merlin Carter <merlin.carter@here.com>

OTA-3682: using tabbed approach for config variants (.conf vs .toml)

---

docs/ota-client-guide/antora.yml

Just a lil' change to prepare for our versioning setup
renaming the version id from "dev" to "latest" (currently 2019.06) so it's more obvious in the URL what version of the docs you're looking at.
eg: 
"https://docs.ota.here.com/ota-client/latest/developer-tools.html"
instead of
"https://docs.ota.here.com/ota-client/dev/developer-tools.html"
Signed-off-by: Merlin Carter <merlin.carter@here.com>

OTA-3682: renaming "dev" version id

---

ci/gitlab/.gitlab-ci.yml

I forgot why I opted for `CI_COMMIT_REF_NAME` but I don't see why it would be useful outside of tags.

Only trigger github release on tags

---

CHANGELOG.md
actions.md
config/sql/migration/migrate.20.sql
config/sql/rollback/rollback.20.sql
config/sql/schema.sql
src/aktualizr_info/main.cc
src/aktualizr_lite/main.cc
src/aktualizr_lite/ostree_mock.cc
src/aktualizr_primary/main.cc
src/libaktualizr/package_manager/androidmanager.cc
src/libaktualizr/package_manager/debianmanager.cc
src/libaktualizr/package_manager/ostreemanager.cc
src/libaktualizr/package_manager/packagemanagerfake.cc
src/libaktualizr/primary/CMakeLists.txt
src/libaktualizr/primary/aktualizr.cc
src/libaktualizr/primary/aktualizr.h
src/libaktualizr/primary/aktualizr_helpers.cc
src/libaktualizr/primary/aktualizr_helpers.h
src/libaktualizr/primary/aktualizr_test.cc
src/libaktualizr/primary/events.h
src/libaktualizr/primary/sotauptaneclient.cc
src/libaktualizr/primary/sotauptaneclient.h
src/libaktualizr/storage/invstorage.cc
src/libaktualizr/storage/invstorage.h
src/libaktualizr/storage/sqlstorage.cc
src/libaktualizr/storage/sqlstorage.h
src/libaktualizr/storage/sqlstorage_test.cc
src/libaktualizr/storage/storage_common_test.cc
src/libaktualizr/uptane/uptane_test.cc
src/uptane_generator/repo.cc

This adds a mechanism to remove old downloaded targets.
Here, "old" is what was before the current and the previous installed version and the cleaning is done at the end of the installation.
It's only enabled when using aktualizr's executable but can be added through the API as well.
~~This first version is simple. I was planning to add a more complex logic based on the previous log of installed versions (spinned off here: https://github.com/advancedtelematic/aktualizr/tree/feat/install-log) but now I'm not sure it's worth the trouble.~~
~~Main problem with this version is that it will probably make problems with rollbacks.~~
Also, we'd probably want to have something similar for ostree. (already here?)

Add automatic removal of old installed targets

---

src/sota_tools/check.cc
src/sota_tools/check.h
src/sota_tools/garage_deploy.cc
src/sota_tools/ostree_http_repo.h
src/sota_tools/ostree_object.cc
src/sota_tools/ostree_object.h
src/sota_tools/ostree_object_test.cc
src/sota_tools/request_pool.cc
src/sota_tools/request_pool.h
src/sota_tools/treehub_server.cc
src/sota_tools/treehub_server.h
tests/sota_tools/test-server-500
tests/sota_tools/test-server-500_after_20
tests/sota_tools/test-server-error_every_10
tests/sota_tools/treehub_server.py

fix/ota-2183/Enable streaming of garage-push/deploy uploads

---

docs/ota-client-guide/modules/ROOT/examples/sota-local.toml

It would be ideal if this file and and config/sota-local.toml were in fact the same file instead of duplicated. Can we get away with one being a softlink to the other?

Fix/update secondary config example.

---

README.adoc

It's used for downloading garage-sign.

Document that the garage tools need python3.

---

docs/ota-client-guide/modules/ROOT/examples/sota-local.toml

Backport of https://github.com/advancedtelematic/aktualizr/pull/1340 to the 2019.5 docs.
Does it matter that the release tag is 2019.5 but the docs branch is 2019.05-docs?

Fix/update secondary config example (2019.05-docs)

---

CHANGELOG.md
docs/README.adoc
docs/ota-client-guide/modules/ROOT/pages/cross-deploy-images.adoc
docs/ota-client-guide/modules/ROOT/pages/install-garage-sign-deploy.adoc

Removed garage-deploy-version from cross-deploy-images.adoc, since it wasn't actually being used.

Update changelog and docs for 2019.7 release.

---

docs/ota-client-guide/modules/ROOT/pages/build-configuration.adoc

Fixing includes and xrefs that had necessary or obsolete component ids.
(@tkfu  - Since this is a general fix, I assume once this is merged to master, I can backport it to 2019.7,  2019.6,  2019.5 with having to do a PR each time?)
Signed-off-by: Merlin Carter <merlin.carter@here.com>

OTA-3746: Fixing incorrect xrefs and inclues

---

docs/ota-client-guide/modules/ROOT/pages/release-process.adoc

1. Explain how to fix a broken release if absolutely necessary.
2. Improve/simplify the doxygen part.
3. OTF is now automatically triggered, so manual testing is no longer necessary.
4. Add section about updating meta-updater.

Update release process doc.

---

docs/ota-client-guide/antora.yml
docs/ota-client-guide/modules/ROOT/pages/build-configuration.adoc
docs/ota-client-guide/modules/ROOT/pages/enable-device-cred-provisioning.adoc
docs/ota-client-guide/modules/ROOT/pages/enable-device-cred-provtest.adoc
docs/ota-client-guide/modules/ROOT/pages/generate-devicecert.adoc
docs/ota-client-guide/modules/ROOT/pages/generate-selfsigned-root.adoc
docs/ota-client-guide/modules/ROOT/pages/libaktualizr-getstarted.adoc
docs/ota-client-guide/modules/ROOT/pages/libaktualizr-why-use.adoc
docs/ota-client-guide/modules/ROOT/pages/meta-updater-dev-config.adoc
docs/ota-client-guide/modules/ROOT/pages/ostree-usage.adoc
docs/ota-client-guide/modules/ROOT/pages/release-process.adoc
docs/ota-client-guide/modules/ROOT/pages/schema-migrations.adoc
docs/ota-client-guide/modules/ROOT/pages/security.adoc
docs/ota-client-guide/modules/ROOT/pages/simulate-device-cred-provtest.adoc
docs/ota-client-guide/modules/ROOT/pages/use-your-own-deviceid.adoc
docs/ota-client-guide/modules/ROOT/pages/useful-bitbake-commands.adoc

This PR is to clean up some asciidoc syntax issues that were making antora barf up a bunch of warnings (and in some cases errors). That looks ugly on CI, and it also means that it's easy to miss a warning or error that we actually care about. Because I want to get rid of all the errors, I had to backport this to all the branches we build (that's why there are multiple PRs).
Mainly there were 3 issues:
This comes from something that's a good practice in Markdown, but a bad habit in asciidoc. In asciidoc, you should either make an ordered list like this:
```
. some item
. something else
. item 3
```
or this:
```
1. some item
2. something else
3. item 3
```
The first option will automatically number the list for you, and you don't have to worry about it. The second option will also …

Fix asciidoc syntax issues to clean up warnings

---

docs/ota-client-guide/modules/ROOT/pages/build-configuration.adoc
docs/ota-client-guide/modules/ROOT/pages/enable-device-cred-provisioning.adoc
docs/ota-client-guide/modules/ROOT/pages/enable-device-cred-provtest.adoc
docs/ota-client-guide/modules/ROOT/pages/generate-devicecert.adoc
docs/ota-client-guide/modules/ROOT/pages/generate-selfsigned-root.adoc
docs/ota-client-guide/modules/ROOT/pages/libaktualizr-getstarted.adoc
docs/ota-client-guide/modules/ROOT/pages/libaktualizr-why-use.adoc
docs/ota-client-guide/modules/ROOT/pages/meta-updater-dev-config.adoc
docs/ota-client-guide/modules/ROOT/pages/ostree-usage.adoc
docs/ota-client-guide/modules/ROOT/pages/release-process.adoc
docs/ota-client-guide/modules/ROOT/pages/schema-migrations.adoc
docs/ota-client-guide/modules/ROOT/pages/security.adoc
docs/ota-client-guide/modules/ROOT/pages/simulate-device-cred-provtest.adoc
docs/ota-client-guide/modules/ROOT/pages/use-your-own-deviceid.adoc
docs/ota-client-guide/modules/ROOT/pages/useful-bitbake-commands.adoc

This PR is to clean up some asciidoc syntax issues that were making antora barf up a bunch of warnings (and in some cases errors). That looks ugly on CI, and it also means that it's easy to miss a warning or error that we actually care about. Because I want to get rid of all the errors, I had to backport this to all the branches we build (that's why there are multiple PRs).
Mainly there were 3 issues:
This comes from something that's a good practice in Markdown, but a bad habit in asciidoc. In asciidoc, you should either make an ordered list like this:
```
. some item
. something else
. item 3
```
or this:
```
1. some item
2. something else
3. item 3
```
The first option will automatically number the list for you, and you don't have to worry about it. The second option will also …

Fix asciidoc syntax issues to clean up warnings (2019.7)

---

docs/ota-client-guide/modules/ROOT/pages/build-configuration.adoc
docs/ota-client-guide/modules/ROOT/pages/enable-device-cred-provisioning.adoc
docs/ota-client-guide/modules/ROOT/pages/enable-device-cred-provtest.adoc
docs/ota-client-guide/modules/ROOT/pages/generate-devicecert.adoc
docs/ota-client-guide/modules/ROOT/pages/generate-selfsigned-root.adoc
docs/ota-client-guide/modules/ROOT/pages/libaktualizr-getstarted.adoc
docs/ota-client-guide/modules/ROOT/pages/libaktualizr-why-use.adoc
docs/ota-client-guide/modules/ROOT/pages/meta-updater-dev-config.adoc
docs/ota-client-guide/modules/ROOT/pages/ostree-usage.adoc
docs/ota-client-guide/modules/ROOT/pages/release-process.adoc
docs/ota-client-guide/modules/ROOT/pages/schema-migrations.adoc
docs/ota-client-guide/modules/ROOT/pages/security.adoc
docs/ota-client-guide/modules/ROOT/pages/simulate-device-cred-provtest.adoc
docs/ota-client-guide/modules/ROOT/pages/use-your-own-deviceid.adoc
docs/ota-client-guide/modules/ROOT/pages/useful-bitbake-commands.adoc

This PR is to clean up some asciidoc syntax issues that were making antora barf up a bunch of warnings (and in some cases errors). That looks ugly on CI, and it also means that it's easy to miss a warning or error that we actually care about. Because I want to get rid of all the errors, I had to backport this to all the branches we build (that's why there are multiple PRs).
Mainly there were 3 issues:
This comes from something that's a good practice in Markdown, but a bad habit in asciidoc. In asciidoc, you should either make an ordered list like this:
```
. some item
. something else
. item 3
```
or this:
```
1. some item
2. something else
3. item 3
```
The first option will automatically number the list for you, and you don't have to worry about it. The second option will also …

Fix asciidoc syntax issues to clean up warnings (2019.6)

---

ci/gitlab/.gitlab-ci.yml

There are two commits here: one to add the trigger, and one to exclude docs branches from unnecessary test jobs that suck up a lot of time. Obviously, this will need to be backported to all the current docs branches for it to actually work, but I wanted to open up the PR here first for review, and then cherry-pick it to the other branches once it's approved.

Add build pipeline triggers for docs branches

---

src/libaktualizr/primary/CMakeLists.txt
src/libaktualizr/primary/aktualizr_fullostree_test.cc
tests/CMakeLists.txt
tests/ostree_mock.c
tests/sota_tools/treehub_server.py
tests/test_backend_failure.py
tests/test_fixtures.py

- free aktualizr_fullostree_test from the ostree_mock library and its preload
- make the ostree_mock universal so it can be used by any test, not just C/C++ written, e.g. by python-based integration tests like test_backend_failure.
- test aktualizr if failures happens during ostree objects download from Treehub in case of ostree updates.
Signed-off-by: Mykhaylo Sul <ext-mykhaylo.sul@here.com>

OTA-2743: Aktualizr test in case of ostree update with failures

---

config/sql/migration/migrate.21.sql
config/sql/rollback/rollback.21.sql
config/sql/schema.sql
src/libaktualizr/storage/sqlstorage.cc
src/libaktualizr/storage/storage_common_test.cc
src/libaktualizr/uptane/tuf.h

This is my stab at fixing #1292.

Store target's custom meta data when installing

---

docs/ota-client-guide/modules/ROOT/pages/_partials/aktualizr-version.adoc
docs/ota-client-guide/modules/ROOT/pages/install-garage-sign-deploy.adoc
docs/ota-client-guide/modules/ROOT/pages/simulate-device-basic.adoc

Reasoning for this change: easier inter-component behaviour. I was reviewing some things, and discovered that one of our get started pages was still referencing 2019.5 as the most current version of aktualizr. We don't want to have to make changes in any non-aktualizr repo when we bump the version, so we create a file that can be used as an include in other components to make sure they are pointing to the latest version.

DOCS: use a single file for configuring the aktualizr version

---

docs/ota-client-guide/modules/ROOT/pages/build-qemu.adoc
docs/ota-client-guide/modules/ROOT/pages/build-raspberry.adoc
docs/ota-client-guide/modules/ROOT/pages/pushing-updates.adoc

* Make it more clear we don't recommend using a VM as a build machine
* Update apt-get to apt
* Remove warning about the build machine needing to be x86-64

Dogfooding survey fixes

---

src/aktualizr_primary/main.cc
src/libaktualizr/primary/aktualizr.cc
src/libaktualizr/primary/aktualizr.h
src/libaktualizr/utilities/CMakeLists.txt
src/libaktualizr/utilities/sig_handler.cc
src/libaktualizr/utilities/sig_handler.h
src/libaktualizr/utilities/sighandler_test.cc
tests/CMakeLists.txt
tests/test_aktualizr_kill.py
tests/test_fixtures.py

@mike-sul Here is a try for handling signals more cleanly. I resurrected a very old branch of mine. Is it close to what you had in mind?
Right now, it's only enabled in aktualizr's `RunForever` loop. Adding it to other parts of the code might be possible but would need more thinking.

Signal handling

---

src/aktualizr_lite/main.cc

Aktualizr-lite: return only not-nulled target to avoid crash

---

docs/ota-client-guide/modules/ROOT/nav.adoc
docs/ota-client-guide/modules/ROOT/pages/comparing-full-filesystem-update-strategies.adoc
docs/ota-client-guide/modules/ROOT/pages/ostree-and-treehub.adoc

* Moves the "comparing update strategies" doc to its own page
* Fixes a misplaced comma in a page title
* Fixes an incorrect heading level causing page to appear as "Untitled" in window bar
* Minor updates to the section about directly flashing to acknowledge microcontroller ECU use cases

DOCS: Misc fixes to updating methods

---

src/libaktualizr/uptane/tuf_test.cc
tests/sota_tools/test-server-500

It's gone and therefore useful to nobody. No reason to keep around
distracting comments, especially when the context was already provided.

Remove references to old Jira.

---

docs/ota-client-guide/modules/ROOT/pages/release-process.adoc

This sort of thing is impossible to automate, and the docs are
extensive enough that a thorough review is a lot to ask, but it's worth
considering for a moment if there are docs that need updating.
(Cherry-picked from af6ac9d7b5200097a95483ecdceeb990c3f68db6 in master)
Should fix the conflict seen in https://github.com/advancedtelematic/aktualizr/pull/1356/.

Add note about reviewing docs when making a release.

---

CMakeLists.txt
scripts/build_ubuntu.sh

So we'll have 2019.8-0-g5443f810 instead of just 2019.8

Use `git describe --long` for versions

---

src/libaktualizr/package_manager/packagemanagerinterface.cc
tests/test_backend_failure.py

Fallback to a full file download if a byte range request fails (a server does not support it).
Ideally, this logic should be "behind" HttpInterface interface and encapsulated in HttpClient implementation of this interface. Unfortunately, there is an additional user context for the download process that is owned by a client (DownloadMetaStruct in packagemanagerinterface.cc)  which has to be managed/reset in case of download retry and which is opaque within HttpClient.

OTA-3716: Full file download If a byte range request fails

---

src/libaktualizr/uptane/directorrepository.cc
src/libaktualizr/uptane/imagesrepository.cc
tests/test_backend_failure.py

It makes aktualizr behave properly if root.json is malformed (invalid json, or missing mandatory field).
But it doesn't fix the case when director or imagerepo is hacked and a hacker set the version filed to 1 in root.json.

OTA-3717: Yield an error if root.json is malformed

---

src/libaktualizr/http/httpclient.cc
tests/test_backend_failure.py

Limit number of HTTP redirects to 10

---

src/libaktualizr/primary/sotauptaneclient.cc
src/libaktualizr/uptane/uptane_test.cc

Fixes https://saeljira.it.here.com/browse/OTA-3379 
Only works in production, not sit, due to https://saeljira.it.here.com/browse/OTA-3936
Will change device-gateway so that legacy devices can still use `/core/system_info`

Use latest endpoint for /system_info

---

.github/workflows/main.yml
docs/ota-client-guide/modules/ROOT/pages/release-process.adoc

Github has CI now! And they have agents running macOS!
So, this PR automates almost all of [this process](https://docs.ota.here.com/ota-client/latest/release-process.html#_update_the_homebrew_recipe_for_aktualizr). Normally the only thing you need to change in the build part of the recipe is the version; we can do that with sed. Homebrew provides tooling for generating the bottle, and for modifying the recipe to include the bottle, so we use that to generate a complete recipe that's ready to submit as a PR against https://github.com/advancedtelematic/homebrew-otaconnect. (The recipe shows up in the build log, and is attached to the CI run as an artifact.) The last step automates adding the bottle to the newly-generated release, which makes the generated recipe with the `bottle do` block …

Add github CI action to build and upload macOS package

---

src/libaktualizr/primary/sotauptaneclient.cc
src/libaktualizr/primary/sotauptaneclient.h

Make the reportHwInfo call be like reportNetworkInfo and only send
things when they've changed.

sotauptaneclient: Make reportHwInfo smarter

---

src/libaktualizr/http/httpclient.cc
src/libaktualizr/http/httpclient.h
src/libaktualizr/http/httpclient_test.cc

We have a custom client that needs to update HTTP headers after the
object has been instantiated. This shouldn't touch any current code
paths in aktualizr itself.
Signed-off-by: Ricardo Salveti <ricardo@foundries.io>

httpclient: Expose method to update headers

---

src/libaktualizr/package_manager/packagemanagerconfig.h

By default, aktualizr will be built with the PackageConfig::kNone, the PackageConfig::kOstree is used only when the -DBUILD_OSTREE is defined.
This fix has no effect on meta-updater.

PackageConfig: using fake package manager for non-ostree build

---

src/libaktualizr/package_manager/docker_fake.sh
src/libaktualizr/package_manager/dockerappmanager.cc
src/libaktualizr/package_manager/dockerappmanager.h
src/libaktualizr/package_manager/dockerappmanager_test.cc
src/libaktualizr/package_manager/packagemanagerconfig.cc

There's a bug where:
1) sota.toml is configured with 2 docker apps: "app1, app2"
2) update is applied, so we are now running both app1 and app2
3) sota.toml is updated with 1 docker app: "app1"
At this point the current logic will leave that app running forever.
This change finds apps that have been removed, stops them, and removes
them from the filesystem.

dockerappmanager: Handle removed apps

---

include/libaktualizr-c.h
src/libaktualizr-c/libaktualizr-c.cc
src/libaktualizr-c/test/api-test.c

Signed-off-by: Mykola Chekhovoi <ext-mykola.chekhovoi@here.com>

OTA-3213 Pause()/Resume()/Abort() C APIs

---

src/libaktualizr/utilities/CMakeLists.txt
src/libaktualizr/utilities/xml2json.h
src/libaktualizr/utilities/xml2json_test.cc
src/sota_tools/CMakeLists.txt
src/sota_tools/garage_push.cc

New version of #1438, with a custom written conversion routine.

repo manifest upload (reworked)

---

src/aktualizr_primary/main.cc

It was replaced by secondary-config-file in aktualizr long ago (see e37947f34114555acb02c088cda074897c62ae36).

Remove obsolete secondary-configs-dir input parameter.

---

src/libaktualizr/primary/aktualizr.cc
src/libaktualizr/primary/aktualizr.h

This worked fine on x86-64 but causes fatal issues on ARM/raspberrypi

Fix a use-after-move in Aktualizr()

---

README.adoc

It's used at build time via embed_schemas.py

Add python3 to the list of minimum dependencies

---

tests/test_fixtures.py

Try harder while getting aktualizr status/info

---

config/sql/migration/migrate.22.sql
config/sql/rollback/rollback.22.sql
config/sql/schema.sql
src/libaktualizr/primary/initializer.cc
src/libaktualizr/primary/initializer.h
src/libaktualizr/primary/sotauptaneclient.cc
src/libaktualizr/storage/invstorage.h
src/libaktualizr/storage/sqlstorage.cc
src/libaktualizr/storage/sqlstorage.h
src/libaktualizr/uptane/uptane_test.cc

According to the standard of Uptane, add counter for
ECU version report. Currently, only added for primary.
It's name in the manifest is "report_counter", in the
payload of primary ecu version report.
Signed-off-by: cheng.xiang <ext-cheng.xiang@here.com>

Add ecu_version_report counter for primary

---

src/libaktualizr/logging/default_log_sink.cc

This allows libaktualizr to log to STDERR if LOG_STDERR is defined
in the environment. A handy way this can be used is for something
like aktualizr-get:
LOG_STDERR=1 aktualizr-get ....
This allows you to understand what is logging (stderr's fd) and what
is the output (stdout's fd).

logging: Allow logger to use STDERR

---

src/aktualizr_secondary/CMakeLists.txt
src/aktualizr_secondary/aktualizr_secondary.cc
src/aktualizr_secondary/aktualizr_secondary.h
src/aktualizr_secondary/aktualizr_secondary_common.h
src/aktualizr_secondary/aktualizr_secondary_metadata.cc
src/aktualizr_secondary/aktualizr_secondary_metadata.h
src/aktualizr_secondary/uptane_verification_test.cc
src/libaktualizr/primary/sotauptaneclient.cc
src/libaktualizr/uptane/directorrepository.cc
src/libaktualizr/uptane/directorrepository.h
src/libaktualizr/uptane/fetcher.cc
src/libaktualizr/uptane/fetcher.h
src/libaktualizr/uptane/imagesrepository.cc
src/libaktualizr/uptane/imagesrepository.h
src/libaktualizr/uptane/tuf.h
src/libaktualizr/uptane/uptanerepository.h
src/virtual_secondary/partialverificationsecondary.cc

OTA-3969: Do the full verification of metadata on the IP Secondary

---

docs/ota-client-guide/modules/ROOT/pages/release-process.adoc
scripts/make_src_archive.sh

It is now done automatically by our gitlab instance, and not just on new releases!

Remove reference to updating the Uptane fork.

---

src/libaktualizr/package_manager/dockerappmanager.cc

docker-app was changed between the original testing in 0.6 and the
current 0.8 to not accept the short-hand argument for the parameters
file. This change uses the long for which is easier to read and
"just works".

docker-app: Fix bad parameters file logic

---

docs/ota-client-guide/modules/ROOT/pages/posix-secondaries-bitbaking.adoc

The tables on the [secondary bitbaking page](https://docs.ota.here.com/ota-client/latest/posix-secondaries-bitbaking.html) were pretty ugly and awful; this more-or-less fixes the column formatting.

DOCS: Fix wonky column widths in secondary bitbake guide

---

src/libaktualizr/package_manager/dockerappmanager.h
src/libaktualizr/uptane/fetcher.cc
src/libaktualizr/uptane/fetcher.h

This is subtle so I'm keeping what's really two changes as one commit:
The issue is that DockerAppManger's constructor needs to create a
"fake fetcher" that's not really used but required for constructing
member variables and they don't have access to the global Config. Only
the PackageManagerConfig. Calling the `Config` default constructor
results in a call to `postUpdateValues` that then calls
`logger_set_threshold` with the default logging level, INFO.
This commit updates the Fetch constructor to only use the values that
it needs from the globabl config: repo-server and director-server. The
DockerAppMgr constructor then doesn't to create a fake global config.

Fix logging issue from bug #1477

---

CHANGELOG.md
src/aktualizr_secondary/aktualizr_secondary_common.cc
src/aktualizr_secondary/aktualizr_secondary_config.cc
src/aktualizr_secondary/aktualizr_secondary_config.h
src/libaktualizr/storage/invstorage.h

OLPSUP-8795: Import the initial hash from file for IP Secondary

---

tests/test_fixtures.py

Perhaps, it will improve/decrease the test running time. 

Use ED25519 scheme to sign metadata in the test uptane repo

---

src/libaktualizr/uptane/fetcher.h

Updated after reading contributing guidelines.
Hey All,
I am curious what you think of this PR.
We have run into an issue where we are pushing a whole lot of images and run over the 1MB limit on the targets.json metadata file. We don't anticipate it growing much more than 1MB as we are pruning our nightly images from the previous month, but we kept having issues at the end of each month where we would bump against the limit.
Additionally, I am more than happy to learn that we are doing something stupid :) Perhaps there is a better way to handle large numbers of images???
Thanks,
Ben

Increase size of targets metadata file accepted

---

tests/uptane_test_common.h

It should not use the default which reads in /var/sota/import.
ptest has been broken since 3515a2f3a984f7cd8cd68057f1113406686363d4, as
Aktualizr's constructor will call `importData` even if given a storage
object as an argument. It ended up importing the global installed
version running on the embedded system.
Before that, tests were side-stepping the import step, so the issue was
never revealed.

Fix import path in tests

---

src/libaktualizr/package_manager/dockerappmanager.cc
src/libaktualizr/package_manager/dockerappmanager.h
src/libaktualizr/package_manager/dockerappmanager_test.cc

The original `handleRemovedApps` method only checks apps configured
in the device's sota.toml. However, there is the case where a
Docker App could be *removed* from the installation Target. In this
case the proper action would be to remove this from the device.

packagemanager: Remove running apps not defined in the Target

---

src/libaktualizr/crypto/crypto.cc
src/libaktualizr/uptane/uptane_test.cc
src/uptane_generator/repo.cc

More careful error checking around key generation

---

config/secondary/virtualsec.json
docs/ota-client-guide/modules/ROOT/examples/virtualsec.json
src/aktualizr_primary/main.cc

ISSUE-1504: Virtual Secondary config

---

src/libaktualizr/storage/sql_utils.h

Since a blob-data may contain null terminator, we have to explicitly specify the size of bytes sequence for the string.

sqlite utils fix an issue with reading blob-data

---

src/libaktualizr/primary/CMakeLists.txt
src/libaktualizr/primary/metadata_fetch_test.cc
src/libaktualizr/uptane/imagesrepository.cc
src/libaktualizr/uptane/imagesrepository.h

Also test that we don't fetch anything from the Image repo if the Director does not indicate that there are updates.
~~This should probably wait until https://github.com/advancedtelematic/aktualizr/pull/1501 is merged, since that will change how root metadata is fetched.~~
I did some manual testing to verify that the bandwidth savings are real. Note that my account has a rather large `targets.json` in the Image repo, so this demonstrates it well. I did a rather naive comparison by counting the bytes dumped to the log for each server response. (This is flawed for many reasons but should still give a reasonable idea of the benefit.) I did this three times: once for initialization (no updates, only Director metadata fetched), again for an update (all metadata fetched), and a third time for a …

Don't fetch Snapshot or Targets metadata if we already have the latest.

---

CMakeLists.txt
cmake-modules/AddAktualizrTest.cmake
docs/ota-client-guide/modules/ROOT/pages/libaktualizr-getstarted.adoc
fuzz/CMakeLists.txt
src/aktualizr_get/CMakeLists.txt
src/aktualizr_info/CMakeLists.txt
src/aktualizr_lite/CMakeLists.txt
src/aktualizr_primary/CMakeLists.txt
src/aktualizr_secondary/CMakeLists.txt
src/libaktualizr-posix/CMakeLists.txt
src/libaktualizr/CMakeLists.txt
src/libaktualizr/package_manager/CMakeLists.txt
src/libaktualizr/storage/CMakeLists.txt
src/load_tests/CMakeLists.txt
src/sota_tools/CMakeLists.txt
src/uptane_generator/CMakeLists.txt
tests/CMakeLists.txt
tests/run_debian_tests.sh

Besides the obvious reuse we have between aktualizr and aktualizr-info, it might be time to ship libaktualizr as a standalone library.
For now, `aktualizr_static_lib` still exists, we might remove it at a later point.
This will also allow some simplifications in #1498.

Switch to dynamic libraries

---

docker/Dockerfile.aktualizr

Otherwise, /usr/local/lib doesn't end up being used for some reason...

Run ldconfig at the end of Dockerfile.aktualizr

---

src/libaktualizr/package_manager/fetcher_test.cc
src/libaktualizr/package_manager/packagemanagerinterface.cc
src/libaktualizr/storage/invstorage.h
src/libaktualizr/storage/sqlstorage.cc
src/libaktualizr/storage/sqlstorage.h

There is no reason to download a file that we don't have space for on disk. I've set 1MB as reserved so that we can still (hopefully) do the database operations to let libaktualizr send a manifest to the server.
This should help with the problems observed with non-OSTree images (see https://github.com/advancedtelematic/meta-updater/pull/637) when additional overhead isn't provided to the qemu image.

Check disk space before downloading files.

---

src/libaktualizr-posix/ipuptanesecondary.cc

Also include the serial to make it somewhat more useful.
Note that this is based against https://github.com/advancedtelematic/aktualizr/pull/1518, not master. This was a small change I made while testing/debugging it.

Reduce repetitive logging to debug level.

---

.clang-tidy

This lint has caused problems in the past and is going in the way of some refactors.

Remove clang-tidy's modernize-pass-by-value

---

CMakeLists.txt
README.adoc
src/libaktualizr/crypto/crypto.cc

Before our code used RSA_generate_key() deprecated since 0.9.8 while checking for OpenSSL < 1.1.0
We also did not epxlicitly check whether OpenSSL's random number generator was properly seeded.
Let's make sure that library users won't generate predictable keys by accident:
* get rid of deprecated function
* explicitly check for random number generator state

Require OpenSSL >= 1.0.2 explicitly

---

src/libaktualizr/package_manager/fetcher_test.cc
src/libaktualizr/package_manager/packagemanagerinterface.cc

Otherwise the download failure will not be properly reported to the backend.

Catch the disk space availability exception.

---

src/aktualizr_secondary/aktualizr_secondary.cc
src/aktualizr_secondary/aktualizr_secondary.h
src/aktualizr_secondary/aktualizr_secondary_factory.cc
src/aktualizr_secondary/aktualizr_secondary_factory.h
src/aktualizr_secondary/aktualizr_secondary_ostree_test.cc
src/aktualizr_secondary/aktualizr_secondary_test.cc
src/aktualizr_secondary/update_agent_ostree.cc
src/libaktualizr/uptane/manifest.cc
src/libaktualizr/uptane/manifest.h
tests/ipsecondary_test.py
tests/test_fixtures.py

Secondary implementation improvement

---

docs/ota-client-guide/modules/ROOT/pages/simulate-device-basic.adoc

This page is used as an include in another component; this was making
the xrefs fail to resolve. Solution was to explicitly specify the
component the links point to. (See
https://docs.antora.org/antora/2.1/asciidoc/page-to-page-xref/ for
more details on why this happens.)

DOCS: Use fully-qualified xrefs on virtual secondary page

---

src/aktualizr_lite/helpers.cc
src/aktualizr_lite/helpers.h
src/aktualizr_lite/main.cc
src/libaktualizr/primary/sotauptaneclient.cc
src/libaktualizr/primary/sotauptaneclient.h
src/libaktualizr/uptane/tuf.h

With the introduction of commit
fead283be7813688f9f69037d2c879a9857157c5
SotaUptaneClient::downloadImage now requires the Target to have
EcuSerial information that would normally come from Uptane. When running
aktualizr-lite, the Target is taken directly from the TUF targets and
does not include this information.
This change allows aktualizr-lite to:
1) Set primary ECU information in the SotaUptaneClient
This change isn't too bad (splitting logic into smaller pieces).
However, it would make more sense if this was a private method.
2) Set Ecu information on the Uptane::Target object.

aktualizr-lite: Include primary ECU for target download

---

src/aktualizr_secondary/aktualizr_secondary.cc
src/aktualizr_secondary/update_agent_ostree.cc
src/libaktualizr/package_manager/debianmanager.h
src/libaktualizr/package_manager/ostreemanager.cc
src/libaktualizr/package_manager/ostreemanager.h
src/libaktualizr/package_manager/packagemanagerfake.cc
src/libaktualizr/package_manager/packagemanagerfake.h
src/libaktualizr/package_manager/packagemanagerfake_test.cc
src/libaktualizr/package_manager/packagemanagerinterface.h
src/libaktualizr/primary/CMakeLists.txt
src/libaktualizr/primary/metadata_expiration_test.cc
src/libaktualizr/primary/sotauptaneclient.cc
src/libaktualizr/uptane/directorrepository.cc
src/libaktualizr/utilities/types.cc
src/libaktualizr/utilities/types.h
src/uptane_generator/director_repo.cc
src/uptane_generator/director_repo.h
src/uptane_generator/main.cc
src/uptane_generator/repo.cc
src/uptane_generator/uptane_repo.cc
src/uptane_generator/uptane_repo.h
tests/test_fixtures.py
tests/test_update.py

- Apply pending update even if its metadata are expired provided that it
was installed before the expiration
- Add tests for the target metadata expiration use-case

OLPSUP-9046: Handle expired Director's target metadata

---

docs/ota-client-guide/modules/ROOT/pages/libaktualizr-getstarted.adoc
src/aktualizr_secondary/CMakeLists.txt
src/libaktualizr/CMakeLists.txt
src/sota_tools/CMakeLists.txt

Use set_target_properties so that we don't confuse the name of library
and executable targets.

Give better names to shared libraries

---

docs/ota-client-guide/modules/ROOT/pages/aktualizr-config-options.adoc
src/libaktualizr/config/config.cc
src/libaktualizr/config/config.h
src/libaktualizr/primary/aktualizr_test.cc
src/libaktualizr/primary/sotauptaneclient.cc
src/libaktualizr/primary/sotauptaneclient.h
tests/ipsecondary_test.py
tests/test_fixtures.py

As we want to track this value on the backend, it needs to show up in
our main configuration object which gets sent when aktualizr starts.

Add configuration paramater for wait-for-secondary

---

src/libaktualizr/package_manager/packagemanagerfactory.cc
src/libaktualizr/package_manager/packagemanagerfactory_test.cc

Also fix pacman factory tests when compiled without deb or ostree.
The old behaviour was different in the case of imaginary pacman names
and existing but not compiled pacman. Now, it throws an exception in any
case.

Throw when trying to build a non-existing package manager

---

src/libaktualizr/utilities/types.cc

I've been experimenting with building aktualizr-lite out-of-tree with
aktualizr as a git submodule as described in the docs. I was getting the
following error without this fix:
../aktualizr/src/libaktualizr/utilities/types.cc:62:37: error: variable 'std::istringstream jsonss' has initializer but incomplete type
62 |   std::istringstream jsonss(json_str);
|                                     ^

libaktualizr: Fix bug when building out-of-tree app

---

src/libaktualizr/package_manager/debianmanager_test.cc
src/libaktualizr/package_manager/fetcher_death_test.cc
src/libaktualizr/package_manager/packagemanagerfake_test.cc
src/libaktualizr/package_manager/packagemanagerinterface.cc
src/libaktualizr/storage/invstorage.h
src/libaktualizr/storage/sql_utils.h
src/libaktualizr/storage/sqlstorage.cc
src/libaktualizr/storage/sqlstorage.h
src/libaktualizr/storage/storage_common_test.cc
src/libaktualizr/uptane/uptane_test.cc

This can be considered a hotfix for the issue with download resume after a nongraceful shutdown (OLPSUP-9401).
I plan to follow up this PR with another one, removing usage of target_images table for binary downloads and possibly moving this functionality to (Binary) package manager.

Fix for binary download resume

---

docs/ota-client-guide/modules/ROOT/pages/account-setup.adoc

In a separate section, describe that, instead of creating multiple
accounts, users can create up to 10 additional env using only
one account. Add a beta icon to that feature.
Relates-to: OTA-4601, OTA-4604

Add the Additional environments subsection

---

src/libaktualizr/primary/sotauptaneclient.cc

Skip trying to fetch(download) target if the ```FlowControlToken``` state is set to ```pause``` or ```abort```.
So we try to fetch target against only in case if the ```PackageManagerInterface::fetchTarget(...)``` returns FALSE and the ```FlowControlToken STATE == running```.

fix: disable trying fetch target in case of abort or pause

---

CMakeLists.txt
src/libaktualizr/storage/sqlstorage.cc

The issue was reported by a customer. This function:
https://github.com/advancedtelematic/aktualizr/blob/3c09519c97f8a40d9a84c62d02559dac18416c93/src/libaktualizr/storage/sqlstorage.cc#L1633
gives incorrect results on 32-bit systems.
The root cause is that both `f_bsize` and `f_bavail` members of statvfs struct are 4 bytes long. Hence, the result of this expression
https://github.com/advancedtelematic/aktualizr/blob/3c09519c97f8a40d9a84c62d02559dac18416c93/src/libaktualizr/storage/sqlstorage.cc#L1640
is also 4 byte long and overflows on 4GB.
This fix makes aktualizr use 64-bit filesystem interface. Member `f_bavail` becomes 8 bytes long and the expression evaluates correctly.
This has no effect on 64-bit architectures.

Fix available space check for 32-bit systems

---

CHANGELOG.md
src/aktualizr_secondary/aktualizr_secondary.cc
src/aktualizr_secondary/aktualizr_secondary.h
src/aktualizr_secondary/aktualizr_secondary_config.cc
src/aktualizr_secondary/aktualizr_secondary_config.h
src/aktualizr_secondary/main.cc
src/aktualizr_secondary/secondary_tcp_server.cc
src/aktualizr_secondary/secondary_tcp_server.h
src/aktualizr_secondary/secondary_tcp_server_test.cc
src/aktualizr_secondary/update_agent.h
src/aktualizr_secondary/update_agent_file.cc
src/aktualizr_secondary/update_agent_file.h
src/aktualizr_secondary/update_agent_ostree.cc
src/aktualizr_secondary/update_agent_ostree.h
src/libaktualizr/utilities/utils.h
tests/CMakeLists.txt
tests/ipsecondary_test.py
tests/test_fixtures.py

Aktualizr secondary auto reboot

---

src/libaktualizr/primary/sotauptaneclient.cc
src/libaktualizr/storage/storage_common_test.cc

Because of this, primary was rebooting needlessly.
Bug found here: https://github.com/advancedtelematic/meta-updater/pull/696

Only return hasPendingInstall() for primary

---

config/sql/migration/migrate.24.sql
config/sql/rollback/rollback.24.sql
config/sql/schema.sql
src/libaktualizr/primary/reportqueue.cc
src/libaktualizr/primary/reportqueue.h
src/libaktualizr/primary/reportqueue_test.cc
src/libaktualizr/primary/sotauptaneclient.h
src/libaktualizr/storage/invstorage.h
src/libaktualizr/storage/sql_utils.h
src/libaktualizr/storage/sqlstorage.cc
src/libaktualizr/storage/sqlstorage.h
src/libaktualizr/storage/sqlstorage_base.cc
src/libaktualizr/storage/sqlstorage_base.h
src/libaktualizr/storage/sqlstorage_test.cc

It's for OTA-3637. Store reports in database when events generated
and delete them after sent them to server.
Signed-off-by: cheng.xiang <ext-cheng.xiang@here.com>

Store reports in the database

---

src/libaktualizr/package_manager/packagemanagerinterface.cc
src/libaktualizr/storage/sqlstorage.cc

Previously, if a binary download was initiated, you'd see a slightly confusing and daunting message like "No file 'xyz' with matched hash in the database". Now that only appears if the file was expected to be present and was not. Also added some similar messages (mostly at debug level) for other failure and edge cases.

Improve logging of binary downloads.

---

src/libaktualizr/package_manager/dockerapp_bundles.cc
src/libaktualizr/package_manager/dockerapp_standalone.cc

Let's create a way of preserving images which are not currently
being used by marking them with the following label:
aktualizr-no-prune=1
An example use-case for this would be keeping around an image used
for manual debugging (it isn't always running).
Signed-off-by: Michael Scott <mike@foundries.io>

libaktualizr: dockerapp: dont prune label aktualizr-no-prune

---

docs/ota-client-guide/modules/ROOT/pages/aktualizr-config-options.adoc
docs/ota-client-guide/modules/ROOT/pages/build-raspberry.adoc

Thud in poky has been moved to community support only. We are still supporting it in our repos for now, but new users should use a newer release branch.
We should consider putting the branchname in a common place as a variable as we've done for some other things.

Move the default branch to zeus.

---

src/libaktualizr/primary/metadata_fetch_test.cc
src/libaktualizr/primary/sotauptaneclient.cc
src/libaktualizr/uptane/directorrepository.cc
src/libaktualizr/uptane/directorrepository.h
src/libaktualizr/uptane/exceptions.h
src/libaktualizr/uptane/imagerepository.cc
src/libaktualizr/uptane/imagerepository.h
src/libaktualizr/uptane/tuf.cc
src/libaktualizr/uptane/uptane_test.cc
src/libaktualizr/uptane/uptanerepository.h

Depends on https://github.com/advancedtelematic/tuf-test-vectors/pull/69.

Feat/ota 4118/director targets sanity

---

src/libaktualizr-posix/ipuptanesecondary.cc
src/libaktualizr/primary/sotauptaneclient.cc
tests/ipsecondary_test.py
tests/test_fixtures.py

- run aktualizr in a full mode while waiting for a secondary reboot after its ostree rootfs update in the scope of ip secondary test;
- fix a minor issue with catching errors that might occur during fetching Secondary's manifest on Primary withing its UptaneCycle loop.

fix: run aktualizr in a full mode while waiting for a secondary reboot

---

src/aktualizr_info/aktualizr_info_test.cc
src/aktualizr_info/main.cc
src/aktualizr_secondary/secondary_tcp_server.cc
tests/prov_test_common.py
tests/test_fixtures.py

Changed log in aktualizr-secondary and aktualizr-info
In aktualizr-secondary, print manifest, meta, and status like download success/fail,
installation success/fail.
Added a parameter "--secondary" for aktualizr-info to make the log for secondary
database looks better.
Signed-off-by: cheng.xiang <ext-cheng.xiang@here.com>

Improve logging in aktualizr-secondary

---

CHANGELOG.md
docs/README.adoc
docs/ota-client-guide/antora.yml
docs/ota-client-guide/modules/ROOT/nav.adoc
docs/ota-client-guide/modules/ROOT/pages/_partials/aktualizr-version.adoc
docs/ota-client-guide/modules/ROOT/pages/account-setup.adoc
docs/ota-client-guide/modules/ROOT/pages/add-ota-functonality-existing-yocto-project.adoc
docs/ota-client-guide/modules/ROOT/pages/aktualizr-config-options.adoc
docs/ota-client-guide/modules/ROOT/pages/build-agl.adoc
docs/ota-client-guide/modules/ROOT/pages/build-qemu.adoc
docs/ota-client-guide/modules/ROOT/pages/build-raspberry.adoc
docs/ota-client-guide/modules/ROOT/pages/customise-targets-metadata.adoc
docs/ota-client-guide/modules/ROOT/pages/debugging-tips.adoc
docs/ota-client-guide/modules/ROOT/pages/ostree-usage.adoc
docs/ota-client-guide/modules/ROOT/pages/pushing-updates.adoc
docs/ota-client-guide/modules/ROOT/pages/reporting-problems.adoc
docs/ota-client-guide/modules/ROOT/pages/rotating-signing-keys.adoc
docs/ota-client-guide/modules/ROOT/pages/troubleshooting-bsp-integration.adoc
docs/ota-client-guide/modules/ROOT/pages/troubleshooting.adoc

In https://github.com/advancedtelematic/aktualizr/pull/1603, I'd wondered why we didn't have a common variable for Yocto branches. Turns out we already do for versions, so I bumped it!

Feat/prep 2020.4

---

src/aktualizr_secondary/aktualizr_secondary_test.cc
src/libaktualizr/primary/aktualizr_test.cc
src/libaktualizr/primary/sotauptaneclient.cc
src/libaktualizr/primary/sotauptaneclient.h
src/libaktualizr/uptane/uptane_test.cc
src/virtual_secondary/virtualsecondary.cc
src/virtual_secondary/virtualsecondary.h

The test is done with a simple fiu_fail

Secondary metadata error

---

docs/ota-client-guide/modules/ROOT/nav.adoc
docs/ota-client-guide/modules/ROOT/pages/_partials/recommended-steps.adoc
docs/ota-client-guide/modules/ROOT/pages/account-setup.adoc
docs/ota-client-guide/modules/ROOT/pages/add-environments.adoc
docs/ota-client-guide/modules/ROOT/pages/client-provisioning-methods.adoc
docs/ota-client-guide/modules/ROOT/pages/cross-deploy-images.adoc
docs/ota-client-guide/modules/ROOT/pages/deploy-checklist.adoc
docs/ota-client-guide/modules/ROOT/pages/evaluation-to-prod.adoc
docs/ota-client-guide/modules/ROOT/pages/install-garage-sign-deploy.adoc
docs/ota-client-guide/modules/ROOT/pages/intro-prep.adoc

Removed the beta icon next to the title "Additional Environments" and updated the page to only recommend creating multiple environments instead of multiple accounts.
Information added about the number of environments that can be created.
Signed-off-by: amma <awuraaamma.okyere-boateng@here.com>

Editing mulltiple accounts page with environment info

---

docs/ota-client-guide/antora.yml

The docs can't be published because of the conflicting versions between `2020.4-docs` and `2020.5-docs` branches. Since the latter seems to now be the latest version, the former needs to be "downgraded".

Update the Antora docs to keep track of the latest version.

---

ci/gitlab/.gitlab-ci.yml

At first run, this release job https://main.gitlab.in.here.com/olp/edge/ota/connect/client/aktualizr/-/jobs/2203603 has failed because I left some changes (2020.5 tag) in the locally cached aktualizr repo what led to the repo update failure (the local tag and the new remote tag pointed to different revisions/commits).
So, I added an additional step to the CI job - remove the locally caches aktualizr repo to make sure that we have "clean" repo before starting the brewing process.

clean the cached aktualizr repo before brewing

---

docs/ota-client-guide/modules/ROOT/pages/build-qemu.adoc

Normally I wouldn't bother with a PR for a minor fix like this, but I wanted to ping @ammaboateng and @HalynaDumych because this was caused by an asciidoc behaviour that might not be obvious: this page included content from another page that had the `{yocto-version}` attribute substitution in it, but didn't include the definition of the attribute, causing a broken link.
Note that this will be fixable in a cleaner way when Antora 2.3 is released, because support for component-scoped attributes was added: https://gitlab.com/antora/antora/issues/251

Fix broken yocto link

---

docs/ota-client-guide/modules/ROOT/pages/add-meta-updater-to-vendors-sdk.adoc
docs/ota-client-guide/modules/ROOT/pages/add-ota-functonality-existing-yocto-project.adoc
docs/ota-client-guide/modules/ROOT/pages/aktualizr-config-options.adoc
docs/ota-client-guide/modules/ROOT/pages/build-agl.adoc
docs/ota-client-guide/modules/ROOT/pages/build-qemu.adoc
docs/ota-client-guide/modules/ROOT/pages/build-raspberry.adoc
docs/ota-client-guide/modules/ROOT/pages/customise-targets-metadata.adoc
docs/ota-client-guide/modules/ROOT/pages/pushing-updates.adoc
docs/ota-client-guide/modules/ROOT/pages/setup-boot-image-for-ostree.adoc
docs/ota-client-guide/modules/ROOT/pages/troubleshooting-bsp-integration.adoc
docs/ota-client-guide/modules/ROOT/pages/troubleshooting.adoc

This was a tricky one, even though the actual fix is fairly small. I've been troubleshooting it for most of the day, though, so I want to make sure it's explained in a PR (and again, I'm tagging @ammaboateng and @HalynaDumych).
It's possible to include content in Antora using the asciidoc `include::[]` directive in two different ways: by [resource ID](https://docs.antora.org/antora/2.1/page/resource-id/), or by (relative) path. In general, we should always be including by resource ID, because inheriting by resource ID means that we retain the context from the page where the include occurs.
To include a page via resource ID, there's a small syntax difference from the xref syntax: for disambiguation purposes, you need to include the **family**--includes could be pages, partials, examples, …

Fix include syntax for partials

---

docs/ota-client-guide/modules/ROOT/pages/yocto-release-branches.adoc

~~Depends on https://github.com/advancedtelematic/updater-repo/pull/38~~.

Docs: List dunfell as a supported Yocto branch.

---

tests/CMakeLists.txt

It's long and slow and isn't really something we necessarily *need* to cover in ptest.

Skip test_ip_secondary test in ptest.

---

src/sota_tools/deploy.cc
src/sota_tools/garage_deploy.cc
src/sota_tools/ostree_object.cc
src/sota_tools/ostree_object.h
src/sota_tools/request_pool.cc
src/sota_tools/request_pool.h

Now prints out runtime, total number of HEAD and PUT requests, and total amount of data uploaded.
We can't improve it if we can't measure it. :)

garage-deploy: Add statistics.

---

src/aktualizr_secondary/msg_dispatcher.cc
src/aktualizr_secondary/secondary_tcp_server.cc

close a connection if an unsupported/unknown message is received otherwise a client(IpUptaneSecondary) get stuck at recv() in Asn1Rpc().
As a matter of fact, this issue was introduced by this commit https://github.com/advancedtelematic/aktualizr/commit/3c1b3c868fe1b13f782336fb27adcb7337935e54 and the given fix makes the secondary behaves exactly as it did before the commit was merged.

Fix/ota 4814/secondary unknown msg support

---

docs/README.adoc
docs/client-provisioning-methods.adoc
docs/configuration.adoc
docs/deb-package-install.adoc
docs/debugging-tips.adoc
docs/ecu_events.adoc
docs/fault-injection.adoc
docs/integrate-libaktualizr.adoc
docs/posix-secondaries-bitbaking.adoc
docs/posix-secondaries.adoc
docs/provision-with-device-credentials.adoc
docs/provisioning-methods-and-credentialszip.adoc
docs/rollback.adoc
docs/schema-migrations.adoc
docs/security.adoc
docs/selectively-triggering-aktualizr.adoc
docs/uptane-generator.adoc

I think these softlinks are no longer necessary. I haven't used them in ages and they mostly just get in the way at this point.

Docs: Remove softlinks and slightly clean up the docs README.

---

CHANGELOG.md
src/sota_tools/ostree_http_repo.cc
src/sota_tools/ostree_http_repo.h

Reuse provides a huge performance boost because certs don't have to be re-read and fewer objects get destroyed and recreated.

ostree_http_repo: Reuse curl handle.

---

src/libaktualizr/storage/sql_utils.h

We've talked about it but it got forgotten somehow.
It's maybe not required for our current use but I figured it should not hurt.

Add a SQL busy handler with 2 seconds timeout

---

CMakeLists.txt

It was added in https://github.com/advancedtelematic/aktualizr/pull/1034 for the Android support, but it doesn't appear to be used anywhere.

Remove dependency on zlib.

---

src/libaktualizr/package_manager/fetcher_test.cc
src/libaktualizr/package_manager/packagemanagerinterface.cc
tests/httpfake.h

We now create the file and leave it empty during download, which sort of makes sense, and then we can successfully "install" it. Previously this failed because verifyTarget failed.

Fix installation of 0-byte files.

---

docs/ota-client-guide/modules/ROOT/pages/build-agl.adoc

This includes some fixes that mean we need fewer additional configuration steps.

build-agl: Bump AGL version to icefish 9.0.1.

---

src/aktualizr_secondary/secondary_rpc_test.cc
src/libaktualizr-isotp/isotpsecondary.cc
src/libaktualizr-isotp/isotpsecondary.h
src/libaktualizr-posix/ipuptanesecondary.cc
src/libaktualizr-posix/ipuptanesecondary.h
src/libaktualizr/primary/sotauptaneclient.cc
src/libaktualizr/uptane/secondaryinterface.h
src/libaktualizr/uptane/uptane_test.cc
src/virtual_secondary/managedsecondary.cc
src/virtual_secondary/managedsecondary.h
src/virtual_secondary/partialverificationsecondary.cc
src/virtual_secondary/partialverificationsecondary.h
src/virtual_secondary/virtualsecondary.cc
src/virtual_secondary/virtualsecondary.h

Note that this is based on https://github.com/advancedtelematic/aktualizr/pull/1642. We are treating that as a feature branch for the moment and this should be merged into that. I originally tried to do this by skipping the original removal of sendFirmware and rebasing, but it was too much of a mess. This was much easier and ultimately rather straightforward.

Refactor/ota 4814/restore send firmware

---

src/libaktualizr/primary/sotauptaneclient.cc

Signed-off-by: Kostiantyn Bushko <kostiantyn.bushko@yahoo.com>
By moving dropping director's targets into the ```SotaUptaneClient:::AssembleManifest()```,  means that any failure in the  ```SotaUptaneClient::uptaneInstall(...)``` call, will lead to drop the director's targets. 
Any installation result code, except ```kOk``` is considered as a state when we must drop the director's target.

ref: disable dropping director's targets in the install's call

---

src/libaktualizr/package_manager/fetcher_test.cc
src/libaktualizr/package_manager/packagemanagerfake.cc
src/libaktualizr/uptane/tuf.cc
src/libaktualizr/uptane/tuf.h

Previously the download would succeed due to the empty length but the installation would fail. Better to fail as early as possible.

Refuse to download OSTree targets with the fake/binary package manager.

---

CHANGELOG.md
src/libaktualizr/uptane/uptane_test.cc
src/libaktualizr/uptane/uptanerepository.cc

This reverts commit b322fa5a7f9188b399f14bd73c3cb2d3423778b0.
This is no longer required by the backend, and it's just a waste of bandwidth.
I've manually tested that provisioning indeed does not require this call anymore.

Revert "Fetch unnumbered Director root once as a workaround."

---

src/libaktualizr/package_manager/docker_fake.sh
src/libaktualizr/package_manager/dockerapp_standalone.cc

Grabbing the docker-app render STDOUT isn't safe. If that file has
docker-compose *warnings*, they'll be included and then produce invalid
YAML. We should write the YAML directly to disk if we are going to
persist.

dockerapp: Handle warnings from Compose gracefully

---

src/libaktualizr/package_manager/dockerapp_bundles.cc
src/libaktualizr/package_manager/dockerapp_standalone.cc
src/libaktualizr/package_manager/dockerappmanager_test.cc

Compare current against target OSTree hash and skip the install call if
the same.
Signed-off-by: Ricardo Salveti <ricardo@foundries.io>

dockerapp: avoid multiple current ostree installs

---

src/libaktualizr/crypto/keymanager.cc
src/libaktualizr/crypto/keymanager_test.cc

fix keymanager: use ed25519 for to sign manifest

---

ci/gitlab/.gitlab-ci.yml

This will stop scheduling e2e tests.

trigger device-farm instead of test-driver

---

src/libaktualizr/primary/aktualizr_test.cc
src/libaktualizr/primary/initializer.cc
src/libaktualizr/primary/initializer.h
src/libaktualizr/primary/sotauptaneclient.cc
src/libaktualizr/storage/sqlstorage.cc
src/libaktualizr/storage/storage_common_test.cc

I might be wrong, but to me call to `saveSecondaryInfo` in `addSecondary` seems unnecessary.
If a device is not yet registered, it will do nothing but producing "Can't save Secondary key: unknown error" message, as there is no serial yet for this secondary in DB. Otherwise the secondary info should  be already stored by `initEcuRegister()`.

Remove unnecessary call to saveSecondaryInfo

---

config/sql/migration/migrate.25.sql
config/sql/rollback/rollback.25.sql
config/sql/schema.sql
src/libaktualizr/primary/aktualizr_test.cc
src/libaktualizr/primary/sotauptaneclient.cc
src/libaktualizr/primary/sotauptaneclient.h
src/libaktualizr/storage/invstorage.h
src/libaktualizr/storage/sqlstorage.cc
src/libaktualizr/storage/sqlstorage.h
src/libaktualizr/uptane/uptane_test.cc
tests/test_update.py

We now stored hashes of the hardware/system information, list of installed packages, network information, and configuration in the database. The hardware and network data were previously stored locally in SotaUptaneClient, but this persists over restarts, so it saves even more bandwidth.
Note that at least on my laptop, one field in the output of lshw changes every time I call it, so the hardware info gets sent every time. Thankfully, I could not reproduce that problem on qemu.
I also removed sending the manifest as part of device data. There's no reason to; it is always sent as part of checking for updates, and there is never a time that device data is sent that isn't immediately followed by checking for updates.

Only send device data if it has changed

---

CHANGELOG.md
docs/README.adoc
docs/ota-client-guide/antora.yml
docs/ota-client-guide/modules/ROOT/pages/_partials/aktualizr-version.adoc

Looks like we don't have anything to get from the docs branch this time

Prepare changelog for upcoming release

---

src/libaktualizr/primary/aktualizr.cc
src/libaktualizr/primary/aktualizr.h
src/libaktualizr/primary/aktualizr_test.cc
src/libaktualizr/storage/invstorage.h
src/libaktualizr/storage/sqlstorage.cc
src/libaktualizr/storage/sqlstorage.h
src/libaktualizr/storage/storage_common_test.cc

This API call should be used after installation complete and before clear of installation result ```clearInstallationResults``` in the storage.
If the device installation result does not exist in the storage the invocation of this API won't have any negative effect it just returns a negative result of the execution.

Added API to direct update raw_roport in the installation result

---

tests/leak_test.cc

It appears that gcc 9 fixes the leak automatically, so valgrind doesn't detect it. Now we actually use the leaky variable, which seems to do the trick.
See the oe-selftest ptest results [here](https://main.gitlab.in.here.com/olp/edge/ota/connect/client/meta-updater/pipelines/825839) for proof that it works.

Fix the leak test (so that it keeps leaking).

---

src/cert_provider/cert_provider_shared_cred_test.cc
src/libaktualizr-c/test/api-test-utils/api-test-utils.cc
src/libaktualizr/bootstrap/bootstrap.cc
src/libaktualizr/config/config.cc
src/libaktualizr/config/config.h
src/libaktualizr/config/config_test.cc
src/libaktualizr/primary/initializer.cc
src/libaktualizr/primary/uptane_key_test.cc
src/libaktualizr/uptane/uptane_ci_test.cc
src/libaktualizr/utilities/utils.cc
src/libaktualizr/utilities/utils.h
src/libaktualizr/utilities/utils_test.cc
tests/config/basic.toml
tests/config/device_id.toml
tests/shared_cred_prov_test.py

It should never be needed again and presents a potential security risk if left available for an attacker who gains access to the device.
Also remove `treehub.json`. It shouldn't be there in the first place, but in the distant past it was often accidentally left there.
There is now an explicit config option to prevent this behavior if you don't want it, which should only be used for tests. Set `provision.mode = "SharedCredReuse"` to use that.

Remove shared cred p12 from the archive after provisioning

---

src/libaktualizr/primary/aktualizr_test.cc
src/libaktualizr/primary/sotauptaneclient.cc
src/libaktualizr/primary/sotauptaneclient.h
src/libaktualizr/uptane/uptane_delegation_test.cc
src/libaktualizr/uptane/uptane_network_test.cc
src/libaktualizr/uptane/uptane_serial_test.cc
src/libaktualizr/uptane/uptane_test.cc
src/virtual_secondary/virtualsecondary.cc
tests/uptane_test_common.h

Previously, only the last Secondary to report an error would get reported. Now we handle all Secondary metadata sending failures and combine them into the device report as is done for installation.

Improve error reporting for sending metadata to Secondaries

---

src/cert_provider/cert_provider_test.h
src/cert_provider/main.cc

Now it just uses the default name.

cert-provider: Fix error when gateway URL in config is empty.

---

docs/ota-client-guide/modules/ROOT/pages/aktualizr-config-options.adoc

I'm basing this on master instead of 2020.7 because the feature only exists on master. We're about to do a release anyway, so it'll get updated on the docs portal soon enough.

Document provision.mode options.

---

src/aktualizr_get/CMakeLists.txt
src/aktualizr_get/main.cc
src/aktualizr_info/CMakeLists.txt
src/aktualizr_lite/CMakeLists.txt
src/aktualizr_lite/main.cc
src/aktualizr_primary/CMakeLists.txt
src/aktualizr_secondary/CMakeLists.txt
src/cert_provider/CMakeLists.txt
src/sota_tools/CMakeLists.txt
src/uptane_generator/CMakeLists.txt
src/uptane_generator/main.cc
tests/CMakeLists.txt

Also actually test that the version printed is what we expect.
This is pretty minor but seems worth doing right.

Add consistent tests for --version and --help options of all tools.

---

src/libaktualizr/utilities/utils.cc
src/libaktualizr/utilities/utils.h
tests/uptane_test_common.h

gcc9 explicitly complains about the previous solution of casting the function parameter.

New StructGuard variant to support non-void return types.

---

src/aktualizr_primary/primary_secondary_registration_test.cc
src/libaktualizr/primary/reregistration_test.cc
tests/uptane_test_common.h

* Virtual Secondary initialization in aktualizr-primary via the config file was not covered.
* The IP Secondary migration and initialization in aktualizr-primary is now somewhat more thoroughly covered.

Add more tests for Secondary initialization.

---

src/libaktualizr/utilities/utils.cc

Instead of in /tmp, which can cause problems in some cases with docker.

Create temporary credential file alongside the existing one.

---

scripts/make_src_archive.sh

Also upgrade git_archive_all to 1.21.0 to fix some warnings.
This fixes a problem encountered while making the latest release (see https://main.gitlab.in.here.com/olp/edge/ota/connect/client/aktualizr/-/jobs/3979786).

make_src_archive.sh: Fix a bug if submodules weren't checked out.

---

src/aktualizr_secondary/secondary_rpc_test.cc
src/libaktualizr/primary/CMakeLists.txt
src/libaktualizr/primary/secondary_provider.h
src/libaktualizr/primary/secondary_provider_builder.h
src/libaktualizr/primary/sotauptaneclient.h

The reason for this PR is to remove the possibility of creation of the SecondaryProvider instance for libaktualizr's user.
Signed-off-by: Kostiantyn Bushko <kostiantyn.bushko@yahoo.com>

introducing builder for secondary provider

---

include/libaktualizr/aktualizr.h
include/libaktualizr/campaign.h
include/libaktualizr/types.h
src/libaktualizr/crypto/keymanager.cc
src/libaktualizr/crypto/p11engine.cc
src/libaktualizr/primary/sotauptaneclient.cc
src/libaktualizr/storage/sql_utils.h
src/libaktualizr/utilities/utils.cc

This list is not exhaustive, but should give a high-level view of what to expect.

Document exceptions thrown through the API.

---

docs/ota-client-guide/modules/ROOT/pages/_partials/aktualizr-version.adoc
docs/ota-client-guide/modules/ROOT/pages/yocto-release-branches.adoc

See also https://github.com/advancedtelematic/updater-repo/pull/41.

Bump the default Yocto branch to dunfell.

---

ci/gitlab/.gitlab-ci.yml

master is too unstable and not particularly useful for us at present.

Run ptest on CI on dunfell.

---

docs/ota-client-guide/modules/ROOT/examples/sota-local.toml

Found a couple of missing configuration parameters that are needed after upgrading aktualizr to 2020.8 on a Mac.

Add missing configuration values to simulate a device.

---

src/aktualizr_lite/CMakeLists.txt

When BUILD_OSTREE is false, aktualizr-lite doesn't exist. Disable the tests too.
Signed-off-by: Phil Wise <phil@phil-wise.com>

Only test aktualizr-lite if it is built

---

ci/gitlab/.gitlab-ci.yml

The corresponding functionality will be provided by SAST integration in
follow-up patches.

Get rid of veracode helpers

---

ci/gitlab/.gitlab-ci.yml
docker/Dockerfile.aktualizr

The 'dependencies' actually means the list of artifacts, while the dependencies
are expressed with 'needs' keyword which by default implies artifact list as
well.

Use proper syntax for gitlab job dependencies

---

src/cert_provider/CMakeLists.txt
src/cert_provider/main.cc
src/libaktualizr/crypto/crypto.cc
src/libaktualizr/crypto/crypto.h
src/libaktualizr/crypto/crypto_test.cc
src/libaktualizr/crypto/keymanager.cc
src/libaktualizr/storage/CMakeLists.txt
src/libaktualizr/storage/invstorage.cc
src/libaktualizr/storage/invstorage.h
src/libaktualizr/storage/storage_common_test.cc

We already allow it for the root CA.

Allow re-importing the client TLS certifcate.

---

docker/Dockerfile.ubuntu.focal

It's much newer than the version we compile manually.

Use default ostree package in Ubuntu Focal dockerfile.

---

CHANGELOG.md

For the record, I don't think it is worth it to go back and correct all of the phrasing/grammar/whatever from past releases, but while reviewing the doc, a few things were in need of obvious, basic improvement.

Changelog: Fix some typos and add a missing item.

---

include/libaktualizr/aktualizr.h
include/libaktualizr/types.h
src/libaktualizr/crypto/crypto.cc
src/libaktualizr/primary/initializer.cc
src/libaktualizr/primary/sotauptaneclient.cc
src/libaktualizr/storage/fsstorage_read.cc
src/libaktualizr/storage/invstorage.cc
src/libaktualizr/storage/sql_utils.h
src/libaktualizr/storage/sqlstorage.cc
src/libaktualizr/storage/sqlstorage_base.cc
src/libaktualizr/storage/storage_common_test.cc
src/libaktualizr/uptane/directorrepository.cc
src/libaktualizr/uptane/iterator.cc
src/libaktualizr/uptane/manifest.cc
src/libaktualizr/uptane/tuf.cc
src/libaktualizr/utilities/types.cc

Generally, only fatal exceptions should be thrown through the API. Non-fatal exceptions are caught inside libaktualizr and converted to error codes. Also:
* All Secondary communication is now wrapped in try-catches.
* JSON parsing is wrapped in try-catches when appropriate. (The Uptane code does most of the json parsing, and that's already covered by higher-level try-catches in SotaUptaneClient.)
* Uptane exceptions are no longer be exposed through the API.
* All SQL exceptions are thrown as SQLException or a subclass thereof (SQLInternalException).
* The list of exceptions thrown in aktualizr.h has been revised accordingly, and a few inaccuracies have been corrected.
* Some logging and error messages have been improved.
* Some unused types have been removed.
There is probably still room …

Improve libaktualizr API exceptions.

---

src/libaktualizr/package_manager/packagemanagerinterface.cc

Log into output download progress each 15sec for big binary files

OTA-4864 - improve binary file download progress logging

---

docs/ota-client-guide/modules/ROOT/pages/aktualizr-config-options.adoc

It was lost during the docs transition last year. See 056b80d4c749358daff8c13b14b1b3b1a7236300 or https://github.com/advancedtelematic/aktualizr/pull/1274 for the original feature.
Note this is targeted at the 2020.9-docs branch so that it'll be live on the portal sooner. It should get merged into master as part of making the next release.

Restore reboot_command to aktualizr config doc.

---

src/libaktualizr/package_manager/CMakeLists.txt
src/libaktualizr/package_manager/packagemanagerconfig.cc
src/libaktualizr/package_manager/packagemanagerconfig_test.cc

When the config is dumped out for the docker-app manager, the custom
config key/vals are printed val=key. eg:
"/tmp/sota/docker-apps" = docker_apps_root
This fixes the issue.

packagemanage: Fix output of pacman config

---

ci/gitlab/.gitlab-ci.yml

fixing broken CI. removed deprecated secrets-sast.  
https://gitlab.com/gitlab-org/gitlab/-/issues/234011 
Signed-off-by: Anatoliy Odukha <aodukha@gmail.com>

fixing broken CI. removed deprecated secrets-sast.

---

src/libaktualizr/primary/device_cred_prov_test.cc
src/libaktualizr/storage/invstorage.cc
src/libaktualizr/storage/storage_common_test.cc

do not throw exception if device id and CN in cert are different. E.g. if happens if we provides device_id in config. Added test to cover this case
Signed-off-by: Anatoliy Odukha <aodukha@gmail.com>

fixed checks for cert re-import

---

src/libaktualizr/primary/sotauptaneclient.cc

findTargetInDelegationTree() has a number of possibly thrown exceptions:
- SecurityException("image", "Rollback attempt on delegated targets")
- Uptane::Exception("image", "Inconsistent delegations")
- Uptane::DelegationMissing
- Uptane::DelegationHashMismatch
- VersionMismatch
Log the exceptions when caught
I was chasing a bug where our delegations didn't match what was in snapshots role. To learn this however, I had to add this extra logging. Aktualizr didn't otherwise report any errors, it would quietly report an installation failure of "Metadata_Verification_Failed". so the only way to see it from the client-logs was to run with `--loglevel 0`
It seems that most (but not all) exceptions do log something when they are thrown from `iterator.cc::getTrustedDelegation()`. I considered …

log exceptions when processing delegation metadata

---

docs/ota-client-guide/modules/ROOT/pages/build-configuration.adoc

Fix 404 error for broken URLs in 2020.9-docs

---

docs/ota-client-guide/modules/ROOT/pages/build-configuration.adoc

Fix 404 error for broken URLs in 2020.8-docs

---

docs/ota-client-guide/modules/ROOT/pages/bsp-integration.adoc

Docs was moved from https://source.denx.de/u-boot/u-boot/raw/master/doc/README.distro to https://source.denx.de/u-boot/u-boot/raw/master/doc/develop/distro.rst . 
Changed link.
Relates-To: OTA-5751
Signed-off-by: Vitalii Yevtushenko <ext-vitalii.yevtushenko@here.com>

Changed link to distroboot docs
